### ISSUE TITLE
Лидов–古在 mechanism test

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#1119]
@pdn4kd suggested a test that demonstrates the [Лидов–古在 mechanism](https://en.wikipedia.org/wiki/Kozai_mechanism).
It appears that we have everything we need for that (it's the perturbation of orbital elements in the circular-restricted three body problem), and `Лидов古在` sounds like a great identifier.

**Comment by eggrobin** [comment]
Update: @RCrockford has encountered something that furiously looks like Лидов–古在 mechanism on a Mercury orbiter. Note that 𝑎 is constant, so we are recognizably in Mercury orbit, and both 𝑒 and 𝑖 vary quite a bit, the former going up and the latter down. The reporting of the analyser is suboptimal when it comes to showing this sort of variation, we should have a way to inform the user whether the value oscillates or changes roughly monotonically over the relevant time period.

![](https://media.discordapp.net/attachments/480397772248580098/863020731041972244/unknown.png)
![](https://media.discordapp.net/attachments/480397772248580098/863023925314453574/unknown.png)

**Comment by RCrockford** [comment]
[persistent.zip](https://github.com/mockingbirdnest/Principia/files/6791100/persistent.zip)
The (rather prosaically named) craft Mercury Orbiter 1 is the craft in question for this effect.

**Comment by RCrockford** [comment]
https://1drv.ms/u/s!ApWZXOEZJxA5gqBx8-ryGvCUAcuMPw?e=VCMVwi
A quicksave with more history.

**Comment by pleroy** [comment]
Note for us: downloaded the save to `P:\...Principia\Save\1119`.

**Comment by eggrobin** [comment]
This does indeed look like the Лидов–古在 mechanism, with an exchange between eccentricity and inclination, conserving the quantity (1−𝑒<sup>2</sup>) cos<sup>2</sup>𝑖.
![butcher_e_i](https://user-images.githubusercontent.com/2284290/130372090-a806a360-d3c3-4cb4-bf3b-178c22f8c29c.png)

![butcher_constant](https://user-images.githubusercontent.com/2284290/130372089-70f7ada8-3a48-485a-99b2-395b344f1b05.png)
