### ISSUE TITLE
Phantom Acceleration

### ISSUE THREAD

**Issue by Minemoder5000** [mockingbirdnest/Principia#1138]
When in orbit around Kerbin, I found I could not time warp due to acceleration, nor use Hyperedit. I had no engines active so that was not the cause. When in deep space, I could time warp and even use Hyperedit. I haven't done any testing around other planets though, so it may be a Kerbin system issue only.

**Comment by SH42913** [comment]
Not the Kerbin only.
I got same trouble with RSS around Earth
http://puu.sh/tfExI/80d5a3e05c.png

And... Please, tell me how you avoid it?

**Comment by pleroy** [comment]
The removal of the `PhysicsBubble` in #1215 and all the work on the `PileUp`s (roughly from #1213 to #1246) should take care of the problem. Will be in Cardano.
