### ISSUE TITLE
Compatibilities with KSP1.2.1

### ISSUE THREAD

**Issue by msnbcorp** [mockingbirdnest/Principia#1150]
Hi, just to put a post it here to make it compatible with the lasts version of KSP.
Currently it give a 
Kerbal Space Program\GameData\Principia\x64\principia.dll:
System.BadImageFormatException:

error in the log.

;)

**Comment by ThomasKerman** [comment]
That error means nothing, it is always there, since Unity / KSP expect a CLR assembly (C# or other .NET lang), but principia uses a native .dll (C++) and a small C# adapter.

So nothing 1.2(.1) specific

**Comment by msnbcorp** [comment]
Hum, don't understand, you mean the error is launched but the program is loaded ? In fact i was able to check that the program is NOT loaded ...
I don't really understand why the error is launched as unity should mostly detect that it is a C# piece of code and absolutly not the fact that it could called a C++ ...

**Comment by pleroy** [comment]
Cardano, the first version of Principia to support KSP 1.2.2, is available [here](https://goo.gl/BCjxaF).
