### ISSUE TITLE
Principia doesn't start, solution isn't in FAQ.

### ISSUE THREAD

**Issue by Dehim1** [mockingbirdnest/Principia#1237]
Like the title says Principia doesn't start. I've got the 64 bit version of ksp 1.2.2.1622. I've got the principia dll in the right place, I've got the visual c++ redistributable packages and I've got the permissions of the ksp folder set to full control for everyone.

Thanks in advance,
-Dehim

**Comment by pdn4kd** [comment]
Principia currently targets 1.1.3, and work is ongoing to get it to play nice with 1.2. This probably should be in the FAQ for now, though.

**Comment by eggrobin** [comment]
Principia Cantor does not support KSP 1.2.x. We are currently working on updating the mod; the next version, Cardano, will target KSP 1.2.2.

**Comment by eggrobin** [comment]
[Added this to the FAQ.](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions/_compare/788d74e6c8da143f084f6d722957962d3b8b1e77...fd6bf9d0bf50906ed1253e03ca20914c74724b9e?short_path=a8e0ba5#diff-a8e0ba5460b9116993499c4eaac05898)

**Comment by Dehim1** [comment]
Thx for the quick reply and quick FAQ update! Do you have any idea about when we might see Cardano?

**Comment by pleroy** [comment]
Well, we've been on it for a looong time now (since August) and it was nearly ready when 1.2 came out.  And then we started to adapt to the new way of doing things in 1.2.  We'd really like to have it behind us.  Hopefully some time in April...

**Comment by pleroy** [comment]
Cardano, the first version of Principia to support KSP 1.2.2, is available [here](https://goo.gl/BCjxaF).

**Comment by Dehim1** [comment]
Awesome! Great job! Will check it out some time this week!
