### ISSUE TITLE
Is there a commit I can build that will work with 1.2.2?

### ISSUE THREAD

**Issue by zilti** [mockingbirdnest/Principia#1244]
I was wondering if there's a commit that'd work with 1.2.2. I know how to build the project, and already tried building both the latest commits in the master and Cardano branches. The Cardano behaves weirdly (like horrendous lag outside the atmosphere) and the latest master commit makes any vessel explode at 70km due to excessive G-Forces.

**Comment by pleroy** [comment]
Unfortunately no.  `master` will only work with 1.1.3 (and even so, it might not be bug-free); `Cardano` is work-in-progress trying to properly support 1.2.x.  We are actively working on `Cardano`, but we are still weeks away from having a proper release.  See also #1237.

**Comment by pleroy** [comment]
FWIW the "horrendous lag" is because the code is full of traces as we are trying to understand what KSP is doing to us.

**Comment by zilti** [comment]
I kinda assumed it was from some kind of tracing. Thanks for the reply, and thanks for developing that mod! I guess I'll have to be a bit more patient then :)

**Comment by pleroy** [comment]
Cardano, the first version of Principia to support KSP 1.2.2, is available [here](https://goo.gl/BCjxaF).
