### ISSUE TITLE
ksp crashed after change of reference frame in flight plan

### ISSUE THREAD

**Issue by azeroth1977** [mockingbirdnest/Principia#1293]
it was new game, has 1 vessel in orbit of kerbin.

Log file created at: 2017/03/28 22:19:06
Running on machine: AZEROTH-PIT
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   000007FEEB5A9A71  	principia__VesselGetPredictionAdaptiveStepParameters [0x000007FEEB5A9A70+177736]
    @   000007FEEB53098F  	principia__FlightPlanDelete [0x000007FEEB53098E+571678]
    @   000007FEEB57A81C  	principia__LogFatal [0x000007FEEB57A81B+111]
    @   000000002F3C2003  	(No symbol) [0x000000002F3C2002]
F0328 22:19:06.890900  4824 interface.cpp:642] Naming parent-direction rotating frame of root body

**Comment by pleroy** [comment]
The fix will be in Cartan, to be released around the new moon of April.  In the meantime, don't use the reference frame fixing the centre of a celestial and the line towards another celestial (e.g. Earth-Centred Sun-Aligned, ECSA).

**Comment by eggrobin** [comment]
More specifically, don't use this frame for manœuvres, and don't create a manœuvre when this frame is selected as the plotting frame. Using it as a plotting frame is otherwise fine.

**Comment by azeroth1977** [comment]
thanks
