### ISSUE TITLE
Crash into the sun when crossing SOI

### ISSUE THREAD

**Issue by maccollo** [mockingbirdnest/Principia#1302]
Sometimes, when crossing from one SOI to another, your vessel crashes into the sun.
This happens more frequently when your velocity is higher, and while hammering the warp button.

Reproduction steps:
Launch vessel from Kerbin into an escape trajectory, preferably with a very high C3.
Mash the warp button like you are playing Mario Party.
https://www.youtube.com/watch?v=FMA5vjxezPk

**Comment by Virindi-AC** [comment]
High timewarp is not required for this at all. I was trying a direct ascent to around eve/moho level and I exploded. If I ascend directly to moho it seems to happen nearly every time.

Sample: https://youtu.be/LcrvYbyNIgU

**Comment by pleroy** [comment]
Will be fixed in Cartan, to be released around the new moon of April.
