### ISSUE TITLE
Crash on EVA interaction

### ISSUE THREAD

**Issue by halfiuuu** [mockingbirdnest/Principia#1308]
So, while on kerbins orbit i try to go EVA to collect data from science things, and it crashes somehow right after collecting data, freezing and then windows tells me ksp.exe stopped working.

**Comment by pleroy** [comment]
Could you please give us your log file?  There is no way that we can analyze the problem from a 2-line description.  See https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs for details.  We need at least the INFO file that was active at the time of the crash (the one whose timestamp immediately precedes the crash).

**Comment by halfiuuu** [comment]
Now i've spotted that they didn't upload indeed... extenstions and stuff...
anyway, here comes whole glog, also, it didn't require collecting data, at some points just as the kerbal is about to touch the craft it goes freeze.
[pakf.zip](https://github.com/mockingbirdnest/Principia/files/907487/pakf.zip)

**Comment by halfiuuu** [comment]
Every crash i had was caused by the same thing, it crashed only at eva, so i do think that whole log will be more usefull

**Comment by pleroy** [comment]
Note to self: look at `INFO.20170407-212526.1152`.

**Comment by halfiuuu** [comment]
good luck with that one

**Comment by pleroy** [comment]
Decoded stack trace:


[`google/glog\src\utilities.cc:122`](https://github.com/mockingbirdnest/Principia/blob/6bf6f9ef93098c2831feff4525fa3908ae14b85c/google/glog\src\utilities.cc#L122)
[`google/glog\src\logging.cc:2034`](https://github.com/mockingbirdnest/Principia/blob/6bf6f9ef93098c2831feff4525fa3908ae14b85c/google/glog\src\logging.cc#L2034)
[`base/map_util.hpp:58`](https://github.com/mockingbirdnest/Principia/blob/6bf6f9ef93098c2831feff4525fa3908ae14b85c/base/map_util.hpp#L58)
[`ksp_plugin/plugin.cpp:503`](https://github.com/mockingbirdnest/Principia/blob/6bf6f9ef93098c2831feff4525fa3908ae14b85c/ksp_plugin/plugin.cpp#L503)
[`ksp_plugin/interface.cpp:778`](https://github.com/mockingbirdnest/Principia/blob/6bf6f9ef93098c2831feff4525fa3908ae14b85c/ksp_plugin/interface.cpp#L778)

**Comment by pleroy** [comment]
What happening is this: the EVA generates plenty of collisions (each time the Kerbal touches something).  If the collision involves a part that's physics-insignificant (a barometer in your case) we get confused because we don't track these parts.

**Comment by pleroy** [comment]
Will be fixed in Cartan, to be released around the new moon of April.
