### ISSUE TITLE
Velocity addition when transiting from space to atmosphere at Kerbin

### ISSUE THREAD

**Issue by SunScream** [mockingbirdnest/Principia#1366]
On transiting from space to atmosphere at Kerbin the spacecraft may experience a sudden increase in velocity of nearly 200m/s with stock KSP and Principia Cartan as the only mod installed.
![space](https://cloud.githubusercontent.com/assets/28628698/25994422/b1eb015a-3705-11e7-9de0-6110e6ef0f54.png)
![atmo](https://cloud.githubusercontent.com/assets/28628698/25994440/c44e3ce0-3705-11e7-9dc4-5c7e9a82b0ce.png)
This does not seem to happen to suborbital flights with the periapsis well below ground level. 
It does not seem to happen when the periapsis is raised to a point high in the atmosphere and the apoapsis is below ~84km. 
An apoapsis 85km or above and a periapsis of 45km will trigger the 200m/s addition as per attached example.
I have been able to reproduce this activity with differing vessels and with differing vessel attitudes at the transition point. The example attached also exhibits an attitude inversion when using the attitude control buttons for normal (radial out) and anti-normal (radial in) when in space, but rotates to the set attitude when transitioning to atmosphere. 
![bad attitude](https://cloud.githubusercontent.com/assets/28628698/25995037/4c532e1e-3708-11e7-81cf-0b3e9a4f1a7f.png)
I have been unable to get a save game just before the transition to atmosphere without inhibiting the 200m/s velocity increase, so this save is a few seconds before re-entry.

**Comment by SunScream** [comment]
Can't attach zipped save file & logs...

**Comment by SunScream** [comment]
https://github.com/SunScream/Principia-issues/blob/master/SaveState.zip

**Comment by pleroy** [comment]
@SunScream: Thanks a lot for the save and the detailed explanations.  It made it very easy for us to reproduce and debug the problem, we very much appreciate your help.  It turns out that the difference of 200 m/s is the surface speed of the planet, which was being added by KSP when it takes control of the vehicle in the atmosphere.  The fix is rather simple and can be found in #1371, which will go in the Catalan release.
