### ISSUE TITLE
Radial-in and radial-out are swapped

### ISSUE THREAD

**Issue by pleroy** [mockingbirdnest/Principia#1370]
(This is extracted from #1366 where it was incidentally mentioned by @SunScream.)

> The example attached also exhibits an attitude inversion when using the attitude control buttons for normal (radial out) and anti-normal (radial in) when in space, but rotates to the set attitude when transitioning to atmosphere.

![](https://cloud.githubusercontent.com/assets/28628698/25995037/4c532e1e-3708-11e7-81cf-0b3e9a4f1a7f.png)

**Comment by eggrobin** [comment]
@Iskie also reported that bug a while ago.
