### ISSUE TITLE
Body Targeting

### ISSUE THREAD

**Issue by NathanKell** [mockingbirdnest/Principia#1414]
For those of us who do not have Jebediah delusions of cowboying, the ability to target celestial bodies (and thus rely on MechJeb's relative inclination indicator and, more importantly, launch into plane of target functionality) would be useful.

**Comment by eggrobin** [comment]
This could also be used for more unification of reference frame selection in the vein of #1411, though it's not clear if we want that particular behaviour (when launching to the Moon's plane, it may still be useful to see the velocities in the ECI or ECEF frame).

**Comment by NathanKell** [comment]
During early launch I very definitely want to stay in ECEF if possible, yes.

**Comment by eggrobin** [comment]
Upon further reflection, the inability to target the celestial orbited by the current celestial (e.g. Earth from the Moon) means unification with our reference frame selection would be very clunky and lopsided. I will allow celestial targeting, but not interact with it (besides disabling the rendering of the occasional random patched conic thing).
As a separate issue, we may want to display nodes in the MCEA and EMB frames, they make sense there (the reference plane is physically significant). They may even make sense in the ECEF frame (to aim for equatorial orbits), but this sounds less obviously useful.

**Comment by eggrobin** [comment]
In the future, it may make sense for Principia to support a "warp to alignment with plane" feature, or indeed a "warp to [astronomical event here]"; this is something we can do (we have tests that look for eclipses), and it seems useful.
It is still a good idea to allow celestial targeting for the occasional conic-based mod that will depend on it however.

**Comment by NathanKell** [comment]
Agree, that'd be rather useful for a bunch of reasons!
