### ISSUE TITLE
Vessel relative velocities change when switching to EVA

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#1415]
Park 2 vessels close to each other with as less relative speed as possible. Perform EVA from anyone of the vessels. The other vessel starts moving away with relative speed of about 2-3 m/s (as reported by the target frame navball.) Attaching a save file where this can be immediately verified.
[Bug_report.txt](https://github.com/mockingbirdnest/Principia/files/1038642/Bug_report.txt)

**Comment by pleroy** [comment]
It appears that when Valentina gets out of the vessel a force of about 700 N is applied to her, apparently by the ladder.  When she lets go of the ladder, that force goes down to 0.  When she holds the ladder the two vessels move away from one another in an accelerated motion.  We suspect that 700 N is the weight that Valentina would have at that altitude (her mass is 93 kg).
