### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by maccollo** [mockingbirdnest/Principia#1422]
[Principia.zip](https://github.com/mockingbirdnest/Principia/files/1044745/Principia.zip)
Log files are provided in the zip. Not sure how it happens, but KSP was just running in the background at low or no timewarp. The save has two vessels, both in stable orbits.

**Comment by maccollo** [comment]
When trying to reload the save file again, it crashes right after the KSC scene loads.
[crashSave.zip](https://github.com/mockingbirdnest/Principia/files/1045355/crashSave.zip)

**Comment by pleroy** [comment]
Decoded stack trace:

[`google/glog\src\utilities.cc:122`](https://github.com/mockingbirdnest/Principia/blob/6346e82182385798f8ee55f2b54beb0a4b3a1393/google/glog\src\utilities.cc#L122)
[`google/glog\src\logging.cc:2034`](https://github.com/mockingbirdnest/Principia/blob/6346e82182385798f8ee55f2b54beb0a4b3a1393/google/glog\src\logging.cc#L2034)
[`physics/continuous_trajectory_body.hpp:215`](https://github.com/mockingbirdnest/Principia/blob/6346e82182385798f8ee55f2b54beb0a4b3a1393/physics/continuous_trajectory_body.hpp#L215)
[`physics/ephemeris_body.hpp:714`](https://github.com/mockingbirdnest/Principia/blob/6346e82182385798f8ee55f2b54beb0a4b3a1393/physics/ephemeris_body.hpp#L714)
[`ksp_plugin/plugin.cpp:1084`](https://github.com/mockingbirdnest/Principia/blob/6346e82182385798f8ee55f2b54beb0a4b3a1393/ksp_plugin/plugin.cpp#L1084)
[`ksp_plugin/interface.cpp:730`](https://github.com/mockingbirdnest/Principia/blob/6346e82182385798f8ee55f2b54beb0a4b3a1393/ksp_plugin/interface.cpp#L730)

**Comment by pleroy** [comment]
The culprit seems to be `Ephemeris::ForgetBefore` which fails to remove old checkpoints when their integration instance was not aligned on a Чебышёв series.  I know how to fix it, but I am having some trouble reproducing the bug in a small unit test.  Amusingly enough the save is fine, but the process of reading it fails systematically.

**Comment by eggrobin** [comment]
For future reference: the FATAL failure itself:
```
F0601 01:09:07.222102 17664 continuous_trajectory_body.hpp:215] Check failed: s.t_max() < checkpoint.t_max_ (+3.75024000000000000e+07 s vs. +3.74976000000000000e+07 s) 
```
