### ISSUE TITLE
KSP crash when reentering a vessel from EVA

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#1447]
Not sure exactly what is causing the crash.  I'm sending an orbital station to minmus, so it has a lot of parts. There are 3 crew capacity parts, the hitchiker storage, mobile processing lab and an mk1 lander module. If I EVA out of the mk1 lander module and then try to board the ship again, ksp is crashing. The problem doesn't happen if I EVA from the other two modules and get back in. The principia logs are showing a 'System.NullReferenceException.' The logs and the save file is attached.

The vessel in question is named VCASS Minmus Station. Jebediah can be found piloting the mk1 lander module; EVA him and try to board back the mk1 lander, instant crash. Mods installed: Principia, Kerbal Engineer Redux, Kerbal Alarm Clock, MechJeb 2. MechJeb is not installed on any of the crafts though, so it can be excluded while testing.
[bug_report.zip](https://github.com/mockingbirdnest/Principia/files/1083251/bug_report.zip)

**Comment by pleroy** [comment]
Decoded stack trace:

[`google/glog\src\utilities.cc:122`](https://github.com/mockingbirdnest/Principia/blob/6346e82182385798f8ee55f2b54beb0a4b3a1393/google/glog\src\utilities.cc#L122)
[`google/glog\src\logging.cc:2034`](https://github.com/mockingbirdnest/Principia/blob/6346e82182385798f8ee55f2b54beb0a4b3a1393/google/glog\src\logging.cc#L2034)
[`ksp_plugin/interface.cpp:637`](https://github.com/mockingbirdnest/Principia/blob/6346e82182385798f8ee55f2b54beb0a4b3a1393/ksp_plugin/interface.cpp#L637)

**Comment by Maxence1402** [comment]
Got a related bug, but while going on EVA in orbit around Minmus, either Jeb is off the lander (metres away), either KSP crashes. I didn't see this in the Catalan version (I'm using Cauchy).

**Comment by eggrobin** [comment]
The full FATAL failure:
```
F0618 00:47:19.120632  6052 interface.cpp:637] System.NullReferenceException: 

  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject ()

  at principia.ksp_plugin_adapter.PrincipiaPluginAdapter+<AdvanceAndNudgeVesselsAfterPhysicsSimulation>d__93.MoveNext () [0x00000] in <filename unknown>:0 
```

**Comment by eggrobin** [comment]
I am able to reproduce this at current master and now will investigate further.
@Maxence1402, the "Jeb of the lander" part of your issue is #1452, which is separate from this, and resolved at current master (the fix will be in Cayley).

**Comment by eggrobin** [comment]
I am able to reproduce this at current master and will now investigate further.
@Maxence1402, the "Jeb of the lander" part of your issue is #1452, which is separate from this, and resolved at current master (the fix will be in Cayley).

**Comment by scimas** [comment]
@eggrobin Just out of curiosity, was it not possible to reproduce it when I had originally posted the issue; indicating that either that specific save file or my ksp installation had a problem? And now you have found a sure fire way of reproducing the problem?

**Comment by eggrobin** [comment]
No, I just hadn't tried to reproduce that one up to now :-)
Reproducing is easy with your save and instructions actually, thanks!

**Comment by eggrobin** [comment]
What is happening is that the `currentCollisions` of a part contain a null. I do not understand why, but it is easy to skip it while reporting collisions, so I will make a pull request to fix this.

**Comment by pleroy** [comment]
Will be fixed in the Cayley release, to be released on the new moon, July 23rd.
