### ISSUE TITLE
Change color of the 'horizon band' of the inertial frame navball

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#1449]
Could that color be changed? Its almost exactly the same color as the maneuver marker and for equatorial orbits the maneuver aligns with that band a lot of the time. I have to really squint eyes to distinguish them. It would be a helpful enhancement.

**Comment by pleroy** [comment]
Ah, good point.  We'll change it to use the same blue as the horizon band on the surface navball.  That would probably be readable.
