### ISSUE TITLE
KSP crashing on quick-save with 't_max check failed' in principia logs

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#1450]
KSP is crashing almost everytime I try to quick-save on a particular craft. The logs are showing t_max check failed. Relevant logs and save file attached.
Craft name on which crash happens: Mun Rover
How to replicate: Fly (drive) Mun Rover around for 5 - 10 min and then try to quick save with F5. Crash happens and it doesn't quick save. Crash doesn't happen if you quick save almost immediately after taking control of the craft.
Mods installed: Principia, Kerbal Engineer Redux, Kerbal Alarm Clock, Transfer Window Planner, Module Manager and MechJeb2. MechJeb isn't installed on any crafts though.
[bug_report.zip](https://github.com/mockingbirdnest/Principia/files/1098712/bug_report.zip)

Edit after reading cauchy is released while I was typing this issue: this happened in catalan, haven't checked with cauchy yet.

**Comment by eggrobin** [comment]
Thanks for the report.
The FATAL check failure is
```
F0624 00:07:46.019421  5196 continuous_trajectory_body.hpp:215] Check failed: s.t_max() < checkpoint.t_max_ (+4.41600000000000000e+06 s vs. +4.41120000000000000e+06 s) 
```
which is the same as that of #1422.
Cauchy fixes #1422 (and the save affected by it is recoverable once switching to Cauchy), so hopefully this will be fixed by updating.

**Comment by scimas** [comment]
Yes, seems to be fixed, not getting crashes anymore.

**Comment by eggrobin** [comment]
Sounds good, closing as fixed in Cauchy.
