### ISSUE TITLE
RO/RP-0 Build Crashing While Loading

### ISSUE THREAD

**Issue by benjisaur** [mockingbirdnest/Principia#1451]
I've been crashing as I try to start a new save with an RO/RP-0 build.  I get this is the glog error message:

Log file created at: 2017/07/02 13:07:50
Running on machine: X
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FFEAC6FBCCD  	principia__GetPlottingFrame [0x00007FFEAC6FBCCC+222220]
    @   00007FFEAC670F9F  	principia__FlightPlanRemoveLast [0x00007FFEAC670F9E+568526]
    @   00007FFEAC6C18F4  	principia__LogFatal [0x00007FFEAC6C18F3+111]
    @   0000000012CDC2E8  	(No symbol) [0x0000000012CDC2E7]
F0702 13:07:50.790941 17080 interface.cpp:636] too many gravity models (2)

Log file created at: 2017/07/02 13:07:50
Running on machine: X
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0702 13:07:50.517406 17080 interface.cpp:457] Initialized Google logging for Principia
I0702 13:07:50.522907 17080 interface.cpp:458] Principia version 2017062403-Cauchy-0-gce5e0f57f4a8383df0f9f3d3a53c6388f3223595 built on 2017-06-17T12:29:06Z by Microsoft Visual C++ version 190024213 for Windows x86-64
I0702 13:07:50.534909 17080 interface.cpp:471] Base address is 00007FFEAC570000
I0702 13:07:50.552412 17080 interface.cpp:642] principia.ksp_plugin_adapter.PrincipiaPluginAdapter.OnAwake()
W0702 13:07:50.762938 17080 interface.cpp:648] No principia state found, creating one
I0702 13:07:50.777439 17080 interface.cpp:244] Destroying Principia plugin
I0702 13:07:50.777439 17080 interface.cpp:250] Plugin destroyed
I0702 13:07:50.780439 17080 interface.cpp:642] Set manageability threshold for Pluto to 110000 m; its atmosphere extends to 110000 m and timewarp is allowed above 5000 m
I0702 13:07:50.780439 17080 interface.cpp:642] Set manageability threshold for Charon to 1000 m; its atmosphere extends to 0 m and timewarp is allowed above 1000 m
I0702 13:07:50.780439 17080 interface.cpp:642] Set manageability threshold for Neptune to 1250000 m; its atmosphere extends to 1250000 m and timewarp is allowed above 5000 m
I0702 13:07:50.780439 17080 interface.cpp:642] Set manageability threshold for Triton to 110000 m; its atmosphere extends to 110000 m and timewarp is allowed above 1000 m
I0702 13:07:50.780439 17080 interface.cpp:642] Set manageability threshold for Uranus to 1400000 m; its atmosphere extends to 1400000 m and timewarp is allowed above 5000 m
I0702 13:07:50.780439 17080 interface.cpp:642] Set manageability threshold for Saturn to 2000000 m; its atmosphere extends to 2000000 m and timewarp is allowed above 5000 m
I0702 13:07:50.780439 17080 interface.cpp:642] Set manageability threshold for Iapetus to 1000 m; its atmosphere extends to 0 m and timewarp is allowed above 1000 m
I0702 13:07:50.780439 17080 interface.cpp:642] Set manageability threshold for Titan to 600000 m; its atmosphere extends to 600000 m and timewarp is allowed above 130000 m
I0702 13:07:50.780439 17080 interface.cpp:642] Set manageability threshold for Rhea to 2000 m; its atmosphere extends to 0 m and timewarp is allowed above 2000 m
I0702 13:07:50.780941 17080 interface.cpp:642] Set manageability threshold for Dione to 2000 m; its atmosphere extends to 0 m and timewarp is allowed above 2000 m
I0702 13:07:50.780941 17080 interface.cpp:642] Set manageability threshold for Tethys to 2000 m; its atmosphere extends to 0 m and timewarp is allowed above 2000 m
I0702 13:07:50.780941 17080 interface.cpp:642] Set manageability threshold for Enceladus to 1000 m; its atmosphere extends to 0 m and timewarp is allowed above 1000 m
I0702 13:07:50.780941 17080 interface.cpp:642] Set manageability threshold for Mimas to 1000 m; its atmosphere extends to 0 m and timewarp is allowed above 1000 m
E0702 13:07:50.780941 17080 interface.cpp:630] The timewarp limit for Jupiter vanishes
I0702 13:07:50.786942 17080 interface.cpp:642] Set manageability threshold for Jupiter to 1550000 m; its atmosphere extends to 1550000 m and timewarp is allowed above 0 m
I0702 13:07:50.786942 17080 interface.cpp:642] Set manageability threshold for Callisto to 10000 m; its atmosphere extends to 0 m and timewarp is allowed above 10000 m
I0702 13:07:50.786942 17080 interface.cpp:642] Set manageability threshold for Ganymede to 5000 m; its atmosphere extends to 0 m and timewarp is allowed above 5000 m
I0702 13:07:50.786942 17080 interface.cpp:642] Set manageability threshold for Europa to 5000 m; its atmosphere extends to 0 m and timewarp is allowed above 5000 m
I0702 13:07:50.786942 17080 interface.cpp:642] Set manageability threshold for Io to 10000 m; its atmosphere extends to 0 m and timewarp is allowed above 10000 m
I0702 13:07:50.786942 17080 interface.cpp:642] Set manageability threshold for Mars to 125000 m; its atmosphere extends to 125000 m and timewarp is allowed above 5000 m
I0702 13:07:50.786942 17080 interface.cpp:642] Set manageability threshold for Deimos to 200 m; its atmosphere extends to 0 m and timewarp is allowed above 200 m
I0702 13:07:50.786942 17080 interface.cpp:642] Set manageability threshold for Phobos to 200 m; its atmosphere extends to 0 m and timewarp is allowed above 200 m
I0702 13:07:50.787441 17080 interface.cpp:642] Set manageability threshold for Earth to 140000 m; its atmosphere extends to 140000 m and timewarp is allowed above 140000 m
I0702 13:07:50.787941 17080 interface.cpp:642] Set manageability threshold for the Moon to 5000 m; its atmosphere extends to 0 m and timewarp is allowed above 5000 m
I0702 13:07:50.787941 17080 interface.cpp:642] Set manageability threshold for Venus to 145000 m; its atmosphere extends to 145000 m and timewarp is allowed above 145000 m
I0702 13:07:50.787941 17080 interface.cpp:642] Set manageability threshold for Mercury to 5000 m; its atmosphere extends to 0 m and timewarp is allowed above 5000 m
    @   00007FFEAC6FBCCD  	principia__GetPlottingFrame [0x00007FFEAC6FBCCC+222220]
    @   00007FFEAC670F9F  	principia__FlightPlanRemoveLast [0x00007FFEAC670F9E+568526]
    @   00007FFEAC6C18F4  	principia__LogFatal [0x00007FFEAC6C18F3+111]
    @   0000000012CDC2E8  	(No symbol) [0x0000000012CDC2E7]
F0702 13:07:50.790941 17080 interface.cpp:636] too many gravity models (2)

I have not deleted or modified any files yet, I've downloaded "principia cauchy" build (with the Real Scale Solar System, x65, ect. files) and dumped the files in GameData -> Principia into my KSP GameData folder, then launched KSP.

**Comment by pleroy** [comment]
Most likely this is an installation problem.  Somehow you have two files describing your solar system.  Could be two installations of Principia for instance.

**Comment by pleroy** [comment]
No feedback after a month, closing.
