### ISSUE TITLE
Random crash when timewarping on Mun

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#1454]
Experienced a random principia crash when timewarping on Mun. In the attached save file, you can find 'Mun Rover' landed at Northwest crater. I had taken off from there towards Southwest crater and was on a suborbital trajectory. I had crossed into principia altitude and started timewarping when the game suddenly crashed. The logs show the error messages, but I'm not sure what went wrong. I tried reproducing the bug without success. Note that I had turned on infinite propellant cheat to perform the maneuver.
[bug_report.zip](https://github.com/mockingbirdnest/Principia/files/1121289/bug_report.zip)

**Comment by eggrobin** [comment]
The FATAL failure is a trapped C♯ exception;
```
 F0704 13:02:05.871377  3376 interface.cpp:636] System.NullReferenceException: 

  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject ()

  at principia.ksp_plugin_adapter.PrincipiaPluginAdapter+<AdvanceAndNudgeVesselsAfterPhysicsSimulation>d__93.MoveNext () [0x00000] in <filename unknown>:0
```
the C♯-side stack trace is the same as that of #1447, so this could be the same bug.

**Comment by eggrobin** [comment]
No news on that since Cayley was released, so I'll assume it's just an instance of #1447, fixed in Cayley.
