### ISSUE TITLE
Procedural SRB missing nozzle causes physics issues.

### ISSUE THREAD

**Issue by jbengtson** [mockingbirdnest/Principia#1460]
Using Principia Cauchy, KSP 1.2.2, Real Solar System, Realism Overhaul.

Launch vessel with a procedural SRB to orbit.
Return to Space Center.
Switch to vessel.
Nozzle will be missing from the procedural SRB.

If the SRB is attached to a decoupler and it is staged the SRB (and any other parts on that vessel) will be gin spinning uncontrollably. In addition, a craft with a procedural SRB that is in physics-less timewarp (100x in my case) that hits the atmosphere and drops out of timewarp will being spinning uncontrollably.

**Comment by eggrobin** [comment]
This is a resurgence of #1421, except it happens when the vessel is reloaded from a state saved in flight rather than when launching. [This condition](https://github.com/mockingbirdnest/Principia/blob/fa32b3820f84b9c2da66ef4b1f7de9fb703c8710/ksp_plugin_adapter/ksp_plugin_adapter.cs#L1153-L1157) will have to be adjusted, but we must be careful not to skip frames in situations where we should not.

**Comment by eggrobin** [comment]
This appears trickier than expected: #1421 was solved by skipping advancing time on frames where the active vessel's orbit driver's last update mode is `TRACK_Phys` and the current update mode is `IDLE`, of which there are two when loading the vessel on the pad. When loading the vessel in flight, we instead have two frames where the last update mode is `TRACK_Phys` and the current update mode is `UPDATE`, but skipping those does not solve the problem, and it further causes principia to crash on timewarp (skipping random frames probably break our expectations).

**Comment by eggrobin** [comment]
I have replicated this bug without Principia, so I think it's not ours, although the symptoms are the same as those of #1421, which was our fault. I will ask @Starwaster to reopen Starwaster/ProceduralParts#3 to track this.

@jbengtson, can you confirm that this occurs in the absence of Principia? (you may want to backup your save before removing Principia).
