### ISSUE TITLE
New RSS will include more planets and moons 

### ISSUE THREAD

**Issue by Bornholio** [mockingbirdnest/Principia#1531]
Previously needed RSSE to get these but new RSS with Paps Scaled space textures/biomes will include
    Titania, Oberon, Ariel, Umbriel, Miranda, Ceres, Vesta

Testing on otherwise Clean install (just RSS/Textures/Kopernicus/MM/MFI)

**Comment by Bornholio** [comment]
http://i.imgur.com/svzX68d.png
http://i.imgur.com/XXTtdfL.png
http://i.imgur.com/jeZBpdJ.png

Everything seems to be good.  Pap has one biome map to fix a small edge defect.

**Comment by pleroy** [comment]
Thanks for letting us know, and for the screenshots.  Closing this issue as it requires no action from us.
