### ISSUE TITLE
Crash when time accelerating

### ISSUE THREAD

**Issue by warmist** [mockingbirdnest/Principia#1561]
Sometimes ksp crashes when time accelerating. In this instance i've captured an asteroid and was starting mining. Full time accelerate crashed ksp. 
Logs: https://gist.github.com/warmist/2b6ad7c1a4925241b318a0e79841aa5e

**Comment by pleroy** [comment]
Decoded stack trace:


[`physics/discrete_trajectory_body.hpp:322`](https://github.com/mockingbirdnest/Principia/blob/c9d0610117bbfaa4633fa3f2d5b72b99547f7151/physics/discrete_trajectory_body.hpp#L322)
[`physics/discrete_trajectory_body.hpp:209`](https://github.com/mockingbirdnest/Principia/blob/c9d0610117bbfaa4633fa3f2d5b72b99547f7151/physics/discrete_trajectory_body.hpp#L209)
[`physics/body_centred_body_direction_dynamic_frame_body.hpp:99`](https://github.com/mockingbirdnest/Principia/blob/c9d0610117bbfaa4633fa3f2d5b72b99547f7151/physics/body_centred_body_direction_dynamic_frame_body.hpp#L99)
[`ksp_plugin/renderer.cpp:161`](https://github.com/mockingbirdnest/Principia/blob/c9d0610117bbfaa4633fa3f2d5b72b99547f7151/ksp_plugin/renderer.cpp#L161)
[`ksp_plugin/renderer.cpp:268`](https://github.com/mockingbirdnest/Principia/blob/c9d0610117bbfaa4633fa3f2d5b72b99547f7151/ksp_plugin/renderer.cpp#L268)
[`ksp_plugin/plugin.cpp:905`](https://github.com/mockingbirdnest/Principia/blob/c9d0610117bbfaa4633fa3f2d5b72b99547f7151/ksp_plugin/plugin.cpp#L905)
[`ksp_plugin/interface.cpp:679`](https://github.com/mockingbirdnest/Principia/blob/c9d0610117bbfaa4633fa3f2d5b72b99547f7151/ksp_plugin/interface.cpp#L679)

**Comment by warmist** [comment]
Also not sure if it's relevant but the game kept lagging (i.e. stopping for half a second) every few minutes.

**Comment by pleroy** [comment]
The periodic slowdown is probably due to autosaving: the Principia data occupies about 40 MiB, which is going to take a little while to write to the file.

Speaking of which: would you by any chance have the save that was created shortly before the crash?  (Around 17:30:30 according to the logs.)  The trajectory of the asteroid seems to be wedged, and we don't quite understand how it could get in that state.

**Comment by warmist** [comment]
Save was a bit older (17:22) and reloading it and playing did not crash again.

**Comment by pleroy** [comment]
Closing, see the comments in #1569.
