### ISSUE TITLE
incorrect ground speed on minmus

### ISSUE THREAD

**Issue by DaMichel** [mockingbirdnest/Principia#1591]
Hi,

apparently I ran into a bug. I landed a craft on Minmus. Although it stays still, its ground velocity is shown as nonzero. 

The overall UI behaves as if it was actually moving, i.e. timewarp is disabled and so on.

Furthermore, resources on the craft are not shown. 

And finally the game crashes when I try to go on EVA. I have to use the hatch GUI since the portait has the EVA button greyed out.

These issues disappeared when I loaded the save with Principia uninstalled.

You'll find a screenshot, output_log.txt and my savegame in my dropbox: https://www.dropbox.com/sh/dhozryc6295ax1x/AACx1OOTouVjS8P2UW9MBER_a?dl=0
That is the result of removing Principia, moving to another place on Minmus and then running Pincipia again. The craft is not quite stock. It has KAS parts on it.

I had no issues landing spaceplanes on Kerbin. Did it many times in this particular game.

Cheers,
Michael

**Comment by pleroy** [comment]
I am going to assume that this is the same issue as #1413, which hopefully will be fixed in the upcoming Chasles version.

In the future please include the log files mentioned [here](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs).  We need those files to be sure what happened.

**Comment by eggrobin** [comment]
Indeed, this is Minmus at 3126 m, above the 3km limit, so #1413 should occur.
As @pleroy said, we need the INFO log to investigate the crash itself.

**Comment by DaMichel** [comment]
Correction, the game freezes. It crashed once but I cannot reproduce that any more. So there is no error.log.
I can provide the principia logs though, as well as KSP.log. You'll find them in my dropbox folder.
Probably it is not even an issue in principia but KSP code getting confused about what is going on ;-)

**Comment by eggrobin** [comment]
Your Principia logs do indicate a crash (from Principia), this is probably due to Principia getting confused by unexpected collisions; this will hopefully be addressed by the changes in Chasles.

**Comment by DaMichel** [comment]
Oh well, okay then. I'm looking forward to the next version. You have been doing a really great job with this mod.

**Comment by pleroy** [comment]
Closing as this will likely be fixed in Chasles.  If the problem reappears with Chasles, please open a new bug.
