### ISSUE TITLE
Possible race condition in Makefile?

### ISSUE THREAD

**Issue by aw1621107** [mockingbirdnest/Principia#1604]
Compilation will sometimes fail with interesting messages, such as 

```
serialization/ksp_plugin.pb.cc:9042:1: error: extraneous closing brace ('}')
}  // namespace serialization
^
```

There's another one along the lines of "error: unknown namespace 'ncipia'", but I haven't seen it in a while, and unfortunately don't have the exact error message. Will update next time I see it.

These errors always show up in generated files, and usually don't occur again after a `make clean`.

I'm on macOS 10.13, building with Apple's Clang.

**Comment by pleroy** [comment]
Are you running with an option that causes `make` to execute actions in parallel?  That would be the only explanation for a "race condition".  The Makefile is certainly not ready to do that.  We see similar issues on Windows when building in parallel.  When that happens, just retry, we are not going to implement filesystem locking.

**Comment by aw1621107** [comment]
Yep, running `make -j <n>`. Didn't know that that isn't supported. Sorry!
