### ISSUE TITLE
Crash on loading savegame

### ISSUE THREAD

**Issue by DaMichel** [mockingbirdnest/Principia#1616]
I have a savegame that crashes on load with Principia.

There are the logs and the savegame.
https://www.dropbox.com/sh/nc5p2py8d038k5t/AAAXhMmPEgsaFyBOE3wQLmnoa?dl=0

The savegame might be a mess since I removed Principia a couple of times during the game. And unfortunately I use a bunch of mods. I hope this report is still useful.

Cheers

**Comment by eggrobin** [comment]
> I removed Principia a couple of times during the game.

That seems to be the issue, this desynchronizes the state of Principia with that of the game. See also [this post on the fora](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip122-130-131-principia%E2%80%94version-chasles-released-2017-10-19%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/&page=33&tab=comments#comment-3188865); your crash is similar to hypervelocity's.

**Comment by DaMichel** [comment]
Yes it was. Thank you!
However, please take it as a feature request to have automatic fixing of such borked savegames.

**Comment by pleroy** [comment]
I don't see us automatically fixing borked saves.  If at all possible, it would be a massive amount of work.  We'd rather focus on improving the mod in meaningful ways.

**Comment by DaMichel** [comment]
Sorry, I was not clear. What I mean is to have the work I did, namely removal of that particular section of the save game data done automatically.
