### ISSUE TITLE
Principia does not load.

### ISSUE THREAD

**Issue by nervvv** [mockingbirdnest/Principia#1626]
Hello, after I start a new save I always get error report that principia.dll could not be loaded, unknown error. I used KSP 1.2.2 and tryed two latest releases. I definitely have the principia.dll in the right folder.

**Comment by nervvv** [comment]
Ok, I solved it already. No-one said that the KSP folder has to sit on C disc.

**Comment by pleroy** [comment]
@nervvv said: "Ok, I solved it already. No-one said that the KSP folder has to sit on C disc."
