### ISSUE TITLE
FAQ incorrect regarding libc++ and libc++abi?

### ISSUE THREAD

**Issue by Olangu** [mockingbirdnest/Principia#1627]
The FAQ states that for Linux "You need libc++ and libc++abi 3.5-2."
In Debian Stable the libc++ 3.5-2 did not have the shared_mutex and some other functions. Using 4.0.1-2 from unstable did however work.

Is the FAQ outdated or do the libc++ 3.5-2 differ between Debian and Ubuntu?

**Comment by pleroy** [comment]
Sadly, the FAQ is outdated.  The currently required libc++ is 3.9.1-2.
