### ISSUE TITLE
Crash when entering vessel during EVA (Linux)

### ISSUE THREAD

**Issue by Olangu** [mockingbirdnest/Principia#1632]
Was on EVA near the Mun, when getting back into vessel it crashed.

Contents of log below:

Log file created at: 2017/11/25 15:34:52
Running on machine: tefnut
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @         0x418a2379  (unknown)
F1125 15:34:52.449827  2113 interface.cpp:668] System.NullReferenceException: 
  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject ()
  at principia.ksp_plugin_adapter.PrincipiaPluginAdapter+<AdvanceAndNudgeVesselsAfterPhysicsSimulation>d__105.MoveNext () [0x00000] in <filename unknown>:0

**Comment by Olangu** [comment]
[FATAL.20171125-153452.2113.txt](https://github.com/mockingbirdnest/Principia/files/1503145/FATAL.20171125-153452.2113.txt)
[INFO.20171125-144554.2113.txt](https://github.com/mockingbirdnest/Principia/files/1503146/INFO.20171125-144554.2113.txt)

**Comment by pleroy** [comment]
I notice that the version you are using is Chasles, and the crash looks furiously like #1618.  That bug has been fixed in the latest version, 陈景润, so I suggest to upgrade.  (If you manage to reproduce the problem with 陈景润, we are of course very interested to hear about it.)

**Comment by Olangu** [comment]
Oh! Sorry must have missed the new release.
Thanks!
