### ISSUE TITLE
Spacecraft orientation change during parent body transition

### ISSUE THREAD

**Issue by Damien212** [mockingbirdnest/Principia#1639]
Hi,

I'm experiencing a bug relating to a single part spin stabilized satellite instantaneously changing orientation during a parent body change. This satellite was supposed to escape the Earth and enter a heliocentric orbit.

The craft, when released from its launch vehicle facing Normal/Radial In with reference to the Sun (to keep solar panels aligned) should stay that way when leaving the Earth as parent and entering the Sun as parent. What actually happens is a split second freeze on parent body change and the craft is then pointing Sun Tangent/Prograde. So effectively a 90 degree turn.

I've recorded the bug happening here: https://youtu.be/swtIJAohGX8

KSP Version: 1.2.2
Principia Version: 陈景润
Craft: Raidernick US Probes Pioneer 5
Potential Mod Interaction: Persistent Rotation 1.8.4

**Comment by Damien212** [comment]
[INFO.20171202-222832.1368.txt](https://github.com/mockingbirdnest/Principia/files/1524374/INFO.20171202-222832.1368.txt)

**Comment by eggrobin** [comment]
We know what is happening here: Principia does axial tilt by tilting the universe around the main body, and it does not properly tilt the vessels while doing so.

We want to fix that by handling rotation ourselves eventually (thereby also doing what PersistentRotation does), but this will take time. This is unfortunate for your Pioneers.

**Comment by Damien212** [comment]
Ah, that makes sense. I'll bear it in mind for future missions. Thanks.

**Comment by pleroy** [comment]
For the record, the following pull requests were needed to reach the point where this issue could be properly fixed:

#1860, #1861, #1862, #1863, #1884 (reverted), #2200, #2201, #2202, #2203, #2204, #2205, #2206, #2207, #2208, #2209, #2210, #2211, #2212, #2213, #2214, #2215, #2216, #2217, #2218, #2220, #2221, #2223, #2224, #2225, #2232, #2233, #2235, #2236, #2237, #2238, #2241, #2243, #2246, #2250, #2251, #2327, #2330, #2333, #2349, #2350, #2351, #2353, #2354, #2355, #2359, #2362, #2364, #2366, #2367, #2368, #2371, #2377, #2379, #2382, #2384, #2386, #2387, #2388, #2392, #2394, #2396, #2397, #2411, #2414, #2416, #2418, #2420, #2421, #2423, #2426, #2428, #2435, #2438, #2451, #2452, #2459, #2463, #2464, #2465, #2467, #2471, #2473, #2474, #2475, #2477, #2481.

#2375 is also related but it's still under review.

**Comment by Growflavor** [comment]
> For the record, the following pull requests were needed

Wow!  & Thank you :-)

**Comment by pleroy** [comment]
And some more: #2483, #2499, #2500.
