### ISSUE TITLE
Principia window got saved off-screen, no way to recover

### ISSUE THREAD

**Issue by kiracofe8** [mockingbirdnest/Principia#1677]
Not sure how, but the main Principia window got saved off the screen in one of my games.  i.e., the relevant part of the .sfs file looked like the below.  That puts the window off the screen.  So when I load the game, I can't see the window.  Switching between space center, tracking station, map view, vessel view, etc. does not bring the window back, nor does quitting KSP and restarting and reloading the game.  Only way to get the window back is to manually edit the .sfs file in a text editor and change main_window_x and main_window_y and reload the game.  

Suggest maybe a check when the game is first loaded that the main window is visible.  

SCENARIO
{
	name = PrincipiaPluginAdapter
	scene = 5, 7, 8
	show_main_window_ = True
	main_window_x_ = 1407
	main_window_y_ = 911

Using KSP 1.2.2 with Cristoffel on Debian Linux.

**Comment by pleroy** [comment]
#1611 was supposed to fix this "once and for all".  Apparently it didn't.

**Comment by eggrobin** [comment]
It was supposed to fix it for the flight planner window, and as far as I know it did (once and for all!).
This is the main window; as I commented on #1611, it would make sense to have that logic common to all windows...
