### ISSUE TITLE
Navball manoeuvre marker jumps at time of ignition

### ISSUE THREAD

**Issue by pleroy** [mockingbirdnest/Principia#1728]
See https://youtu.be/P2ADq1CVm0o for details.

**Comment by fat-lobyte** [comment]
Hi, just wanted to follow up with more information.

Quicksave: 
[quicksave-node-jump.zip](https://github.com/mockingbirdnest/Principia/files/1755897/quicksave-node-jump.zip)

Steps to reproduce:

1. Unpack and load the quicksave
2. Open Flight planner
3. Delete the current (stale) maneuver node on the NavBall
4. Re-Create the maneuver node by clicking on "Show on NavBall" in the Principia Flight Planner
5. Align ship to maneuver node
6. Wait until the countdown has counted to zero
7. Observe the Maneuver node jumping

Additional Information:

  * Principia Version: 2018011702-Clifford-0-g6039cbb001e31796edef56c11e407a75dcfeda10
  * KSP Version: 1.2.2.1622 (WindowsPlayer x64)
  * Operating System: Windows 10, 64 Bit

Please contact me if you need any more info or if you need help with testing.

**Comment by pleroy** [comment]
We can't seem to be able to reproduce the problem demonstrated by your video in the stock game.  Have you observed it with stock?  If not, the problem might come from an interaction with other mods, and these things are notoriously hard to debug.

What mods do you use?  In other words, what mods do we need to load the save?

**Comment by EstrelaGaliza** [comment]
Same problem here.

Maneuver node jumps when t=0

Is easy to check creating a new maneuver node and moving the ignition time between past and future, but it also happens when you set the node and naturally execute it.

Im running a clean KSP 1.2.2 install with Realistic Progression Ckan install (just recommended mods).

Should I share my savegame with you?

Apologies, my english is not very good.

**Comment by EstrelaGaliza** [comment]
I have just recreate the issue in stock game without mods (Principia+ Squad folder).

Nodes jumps when time = 0. The only way to correctly burn nodes is using ''inertially fixed'', closing principia window and burning like an standard KSP node.
[quicksave #1.zip](https://github.com/mockingbirdnest/Principia/files/1847598/quicksave.1.zip)

-Create a node to circularice at Mun Apogee.
-''Show on Navball''
-Wait until time = 0
-You'll see the node changing position

**Comment by pleroy** [comment]
Thanks a lot for taking the time to reproduce the problem on the stock game.  I'll take a look over the week-end and I'll update the bug.

**Comment by pleroy** [comment]
Thank you both for being persistent in bringing this issue to our attention.  This bug will be fixed in the next release, Cramer, to be released around April 16th.  The problem stemmed from a confusion between the vessel orbit and the manœuvre node patch orbit.  This is almost always incorrect as the vessel orbit may change, but it was only really visible e.g., when changes of celestial sphere of influence were involved.

**Comment by EstrelaGaliza** [comment]
Glad to hear that.

I had experienced this kind of problems with mars transfer maneuvers.

By the way, I had decided to start new savegame without beginning until the issue was fixed. I'm using RSS... Would it be a problem if I installed principia in my current savegame? Would it affect the historical position of the planets?

Thanks a lot!

**Comment by pleroy** [comment]
You can give it a try, but you may or may not like the result.  We will restart integration of the solar system since the origin (it will take a little while the first time you start the game with Principia) and we'll move the celestials to the positions that we have computed.  As an example, the Moon is likely to move quite a bit, so if you were flying towards the Moon you may find yourself going towards the-moon-is-not-here-anymore.
