### ISSUE TITLE
Path shenanigans and uncompiled .proto files break fresh Windows build

### ISSUE THREAD

**Issue by aw1621107** [mockingbirdnest/Principia#1755]
I ran into some issues when setting up a Principia dev environment. First, I got the following error message when running `rebuild_all_solutions.ps1`:

    Building JS embedded well-known types
    '"C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\Debug\js_embed.exe"' is not recognized as an internal or external command, operable program or batch file.
    C:\Program Files(x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 9009. [C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\libprotoc.vcxproj]

`js_embed.exe` is located at `C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\x64\Debug\js_embed.exe` on my machine, while `libprotoc.vcxproj` refers to `js_embed.exe` at `"$(SolutionDir)$(Configuration)\js_embed.exe"`.

Sticking `\x64\` between `$(SolutionDir)` and `$(Configuration)` seems to solve this issue, but 
the build still fails, with the following error messages:

    4>ClCompile:
        lite_unittest.cc
    4>C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\google/protobuf/map_lite_unittest.pb.h(36): fatal error C1083: Cannot open include file: 'google/protobuf/unittest_no_arena_lite.pb.h': No such file or directory [C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\lite-test.vcxproj]
        map_lite_test_util.cc
    4>C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\google/protobuf/map_lite_unittest.pb.h(36): fatal error C1083: Cannot open include file: 'google/protobuf/unittest_no_arena_lite.pb.h': No such file or directory [C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\lite-test.vcxproj]
        test_util_lite.cc
        map_lite_unittest.pb.cc
    4>C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\google/protobuf/map_lite_unittest.pb.h(36): fatal error C1083: Cannot open include file: 'google/protobuf/unittest_no_arena_lite.pb.h': No such file or directory [C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\lite-test.vcxproj]
        unittest_import_lite.pb.cc
        unittest_import_public_lite.pb.cc
        unittest_lite.pb.cc
        unittest_no_arena_lite.pb.cc
    4>c1xx: fatal error C1083: Cannot open source file: 'google\protobuf\unittest_no_arena_lite.pb.cc': No such file or directory [C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\lite-test.vcxproj]

`unittest_no_arena_lite.pb.{cc,h}` indeed does not exist. `unittest_no_arena_lite.pb.proto` does, though, and according to `lite-test.vcxproj`, `unittest_no_arena_lite.pb.proto` only gets compiled for Win32 builds.

I copied the CustomBuild commands from `map_lite_unittest.proto`, after which a similar set of messages appeared for another protobuf file:

    12>C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\google/protobuf/unittest_mset.pb.h(32): fatal error C1083: Cannot open include file: 'google/protobuf/unittest_mset_wire_format.pb.h': No such file or directory [C:\Users\awang\code\Principia-repos\Google\protobuf\vsprojects\test.vcxproj]
    <Another 4 messages very similar to the above>

The cause and fix were the same as those for `unittest_no_arena_lite.proto`. After this fix, the build finished fine.

OS: Windows 10 Pro Insider Preview 17093.rs_prerelease.180202-1400
VS 2015 Update 3, freshly installed

I have the most recent versions of all dependencies + Principia:

  - Principia: 2a17af46c6e5281e4f65bcdd7222510100995308
  - Optional: https://github.com/mockingbirdnest/Optional/commit/9d15e6e73f4263f3b506132e8467faf7ff284935
  - benchmark: https://github.com/mockingbirdnest/benchmark/commit/2802832f9310be63c533a5a25a1092ad74c0f844
  - chromium: https://chromium.googlesource.com/chromium/src/+/40.0.2193.1 with patch added in https://github.com/mockingbirdnest/Principia/commit/4a85594a4d7de4cfd1924a0fb386b26e6c99dfed
  - glog: https://github.com/mockingbirdnest/glog/commit/e40b0fb22276e02ccee95e05431f036ddaee5dc0
  - googlemock: https://github.com/mockingbirdnest/googlemock/commit/c0cfbe7cd506c2e7e39ae901aa5045db57f27c9a
  - googletest: https://github.com/mockingbirdnest/googletest/commit/acb26f2e6913142863084f27d15886471e24bf4c
  - protobuf: https://github.com/mockingbirdnest/protobuf/commit/dc25c99b097a623b469636bb622fe426b4239d70

**Comment by pleroy** [comment]
Fixed by [37ec94a490d5fa42a7b1ec678ad3eeb0eab81d9a](https://github.com/mockingbirdnest/protobuf/commit/37ec94a490d5fa42a7b1ec678ad3eeb0eab81d9a) in the `mockingbirdnest/protobuf` branch.
