### ISSUE TITLE
Principa uses up 8GB of RAM in under 30 min

### ISSUE THREAD

**Issue by Zacxen** [mockingbirdnest/Principia#1797]
In the map view, when Principa's flight planner is being used, RAM usage constantly increases until maxed out. KSP did not crash, but had to be closed due to the fact that the ram usage was making Ubuntu unusable.

Running on Ubuntu 16.10 with a fresh install of KSP 1.3.1
The only mod being used is Principa Coxeter for 1.3.1

Log files:
[KSP.txt](https://github.com/mockingbirdnest/Principia/files/1891628/KSP.txt)
[stderr.txt](https://github.com/mockingbirdnest/Principia/files/1891629/stderr.txt)

**Comment by pleroy** [comment]
Could you give us a save?

**Comment by Zacxen** [comment]
Here you go, it is a brand new game with a ship that has a flight plan in orbit. If I go to map view or the tracking station and view it's path memory usage increases rapidly.

**Comment by pleroy** [comment]
Many thanks for reporting this bug, and sorry that it took us a while to resolve it.
