### ISSUE TITLE
Principia makes fps down to 5% without principia

### ISSUE THREAD

**Issue by EthanWang706** [mockingbirdnest/Principia#1800]
Without using more than 15% CPU 10GB RAM and much graphic card. 
Because I am using Mac, so it's using OpenGL

**Comment by pleroy** [comment]
We would need at a minimum a save, logs, reproduction steps, and a description of what you were doing and how/when it got slow.

**Comment by EthanWang706** [comment]
I am just on the ground, and principia's calculation doesn't even start, but if I remove principia, the game back to 60fps. The save is a brand new file with no astroids and spacecrafts

**Comment by pleroy** [comment]
Look, we have many users on Mac and nobody has ever reported this.  I don't doubt that you are seeing a problem, but if you don't give us a save and logs (*both* the `KSP.log` file and our own INFO logs found in `glog/Principia`) there is not much that we can do to investigate.

**Comment by EthanWang706** [comment]
Because Principia still not supports v1.4.3, so I download the previous 1.4.2 version, and this bug was gone
