### ISSUE TITLE
KSP freezes, principia probable cause

### ISSUE THREAD

**Issue by kostor** [mockingbirdnest/Principia#1839]
No box appears, game freezes. Only way to get it back up - restart.
I'll be adding files of logs.

What happens: I try to add delta V to tangent slider when doing maneuver planning.
What mods I have: Kopernikus, RSS and generally the mandatory for RO.
KSP ver.: 1.3.1 (most mods are stable on this ver.)

gist with FATAL and INFO and output_log:
https://gist.github.com/kostor/81ec42a15a9bf6ec9ef4c365703d83b0

thanks!

**Comment by pleroy** [comment]
Failure:
```
F0520 17:11:46.264861  7064 ephemeris_body.hpp:489] Check failed: integrator_parameters.first_time_step > 0 * Second (-5.00679016113281250e-06 s vs. +0.00000000000000000e+00 s) Flow back to the future: -1.54620104540178633e+09 s <= -1.54620104540178132e+09 s
```
Decoded stack trace:

[`ksp_plugin/flight_plan.cpp:372`](https://github.com/mockingbirdnest/Principia/blob/039ef8545425acfbb4a6bcbc4838f7d085f59240/ksp_plugin/flight_plan.cpp#L372)
[`ksp_plugin/flight_plan.cpp:286`](https://github.com/mockingbirdnest/Principia/blob/039ef8545425acfbb4a6bcbc4838f7d085f59240/ksp_plugin/flight_plan.cpp#L286)
[`ksp_plugin/flight_plan.cpp:152`](https://github.com/mockingbirdnest/Principia/blob/039ef8545425acfbb4a6bcbc4838f7d085f59240/ksp_plugin/flight_plan.cpp#L152)
[`ksp_plugin/interface_flight_plan.cpp:458`](https://github.com/mockingbirdnest/Principia/blob/039ef8545425acfbb4a6bcbc4838f7d085f59240/ksp_plugin/interface_flight_plan.cpp#L458)

**Comment by pleroy** [comment]
FTR the relative error in the times is about 2^-48, so it's more than a few ULPs.

**Comment by pleroy** [comment]
I am 95% certain that this is the same bug as #1864, only the failure mode in #1864 was much easier to diagnose.  Basically the integrator used for the flight plan (which is the same as used for the prediction) would sometimes overshoot a bit, and this would result in misordered burns and coasts in the flight plan, causing the integration to try to go backwards in time.
