### ISSUE TITLE
Getting in a orbit that fly pass 4 outer planets in a row in RSS will crash the game when time warp

### ISSUE THREAD

**Issue by EthanWang706** [mockingbirdnest/Principia#1864]
For some reason, that happened every time trying to time warp, to even 2x
Hardware: 
CPU: i7-6700HQ
RAM: 16g DDR4
Graphic: GTX 1070
because this is on my friends' computer, and he's not online yet, so I will sent principia.dll when he sent it to me.
By changing into a orbit that is far enough from Neptune can warp to 100x without crashing the game, but we are still passing Saturn, and we have to get in a orbit like this.

**Comment by EthanWang706** [comment]
[WARNING.20180627-125954.17364.txt](https://github.com/mockingbirdnest/Principia/files/2143538/WARNING.20180627-125954.17364.txt)

**Comment by EthanWang706** [comment]
[INFO.20180627-125559.17364.txt](https://github.com/mockingbirdnest/Principia/files/2143545/INFO.20180627-125559.17364.txt)
and this one

**Comment by EthanWang706** [comment]
The game freeze itself when warping, for minutes, so I just quit the game. So there is no crash logs

**Comment by pleroy** [comment]
Note for ourselves: partially decoded stack trace:








[`integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp:178`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp#L178)

[`ksp_plugin/vessel.cpp:252`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/ksp_plugin/vessel.cpp#L252)
[`ksp_plugin/interface.cpp:987`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/ksp_plugin/interface.cpp#L987)


It appears that we broke stack traces with the DLL split 5 months ago.  This doesn't help debugging this problem.

**Comment by pleroy** [comment]
Note for ourselves: full trace obtained by guessing the base address of the Physics DLL until I got something sensible:


[`physics/ephemeris_body.hpp:973`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/physics/ephemeris_body.hpp#L973)
[`physics/ephemeris_body.hpp:1065`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/physics/ephemeris_body.hpp#L1065)
[`physics/ephemeris_body.hpp:1095`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/physics/ephemeris_body.hpp#L1095)
[`physics/ephemeris_body.hpp:467`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/physics/ephemeris_body.hpp#L467)

[`integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp:178`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp#L178)
[`physics/ephemeris_body.hpp:516`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/physics/ephemeris_body.hpp#L516)
[`ksp_plugin/vessel.cpp:252`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/ksp_plugin/vessel.cpp#L252)
[`ksp_plugin/interface.cpp:987`](https://github.com/mockingbirdnest/Principia/blob/31a61b387a33a9ec354dbacad16a514ad9eec49e/ksp_plugin/interface.cpp#L987)

and the failure message:
```
F0627 12:59:54.624032 11408 continuous_trajectory_body.hpp:161] Check failed: t_max() >= time (+3.75912000000000000e+08 s vs. +3.75912000000000119e+08 s) 
```
This could be related to #1839, which is a bug where I could never figure out what was happening.

**Comment by pleroy** [comment]
@EthanWang706: I think that I have figured out what's happening, so I don't need more data from you.  The problem appears to be a subtle numerical error in the integrator used to compute the prediction, see #1867.

The fix will be in version Δημόκριτος, to be released around July 13th.

Unfortunately I don't have a good work-around for you in the meantime, but I suggest that you try to tweak the Tolerance parameter of the prediction in the Prediction Settings in the main Principia UI.  With some luck, reducing the tolerance might cause the problem to go away.  If you try this and it helps, please let us know by commenting on this issue.

**Comment by EthanWang706** [comment]
Ok, thank you.

**Comment by EthanWang706** [comment]
many thanks
