### ISSUE TITLE
Plotting Frame's interaction with stock SAS is inconsistent

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#1868]
There is the already known problem of the markers on navball not matching with the actual direction when in the Target frame of reference. But apart from that, another inconsistency occurs when loading from a quick save (Hold F9).

What happens is that on a game load (normal load, you just started the game and are launching a ship, no quick loads so far) if you use the SAS in a special mode (prograde, normal etc. anything other than basic stability assist), the ship always aligns with the SOI body's markers, ignores the plotting frame (apart from change between inertial and surface fixed frames. Those do affect SAS correctly). So if I'm plotting in Mun - Kerbin barycenter frame, and want to burn in KMB prograde, I have to do so manually. Because the ship will keep pointing in Kerbin / Mun prograde direction, whichever SOI I happen to be in.

Now with your ship in space, do a quicksave (F5) and quickload (F9). Now the SAS will be faithful to the plotting frame, aligning with the markers shown on navball. And not just for that one ship, for every ship you take control of in that KSP session. Quit KSP, come back, and it will be ignoring plotting frame again.

I didn't find these issues documented anywhere.
So, review of steps to reproduce:
1. Launch KSP and start a new game / resume previous game.
2. Launch a new vessel / take control of previously launched vessel.
    Observed behaviour: SAS ignores current plotting frame beyond inertial / surface fixed of current SOI.
3. While in control of a vessel, do a quicksave and quickload (F5, hold F9)
    Observed behaviour: SAS is faithful to the current plotting frame.

That said, I'm not sure which behaviour would be preferable. On one hand, I want to be able to properly execute nodes that are in a non stock frame. But on the other hand, I also want the ability to execute nodes in one frame while looking at the results in another frame (burn in KCI, looking at Mun periapsis in MCI). This isn't a big problem in sandbox mode where the manoeuvre mode of SAS is unlocked, but can be frustrating in career mode.

**Comment by eggrobin** [comment]
> I had never managed to figure out how to deterministically reproduce this bug

Unfortunately, I am unable to reproduce the issue by following the given reproduction steps with Εὔδοξος, either in 1.3.1 or 1.5.1: on normal game load (either starting a new game or loading one), launching a new vessel or taking control of an existing one, the SAS follows the plotting frame (quicksaving and quickloading have no further effect).

Nevertheless, the bug still exists: we just had [a report to that effect on the forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip131-14x-151-principia%E2%80%94version-%CE%B5%E1%BD%94%CE%B4%CE%BF%CE%BE%CE%BF%CF%82-released-2018-01-06%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/&page=48&tab=comments#comment-3520988).

**Comment by scimas** [comment]
I haven't played KSP much recently, so I maybe remembering some things incorrectly.
>Do you mean fact that the markers display the Frenet frame of the trajectories in the target LVLH frame as we discussed on the forum thread last year?

No, the forum thread was just me getting confused. From what I recall, in the LVLH frame, the velocity with respect to the target wouldn't match with the (+/-)tangent markers on the navball. Even when using kOS and telling it to point in the direction of `my:Velocity - target:Velocity` would result in the vessel pointing in a direction slightly different than the tangent markers on the navball. Although I would really need to test this again to confirm.

>Unfortunately, I am unable to reproduce the issue by following the given reproduction steps with Εὔδοξος, either in 1.3.1 or 1.5.1

I was able to reproduce it reliably when I opened the issue. Can you let me know the Principia version at the time of the issue? I still have principia releases from Christoffel, I can try to recreate it in that version and then the current one. Let's see if that works.

**Comment by eggrobin** [comment]
> in the LVLH frame, the velocity with respect to the target wouldn't match with the (+/-)tangent markers on the navball. Even when using kOS and telling it to point in the direction of my:Velocity - target:Velocity would result in the vessel pointing in a direction slightly different than the tangent markers on the navball.

Ah, I think you see what you mean.
This is intended, but fairly subtle: the LVLH frame is a rotating frame, so that your velocity in that frame is not just the difference of the KCI velocities.

As an example, consider a situation where the target is on a circular orbit around Kerbin, and you are on an orbit at the same altitude, in the same plane, and in the same direction, but 180° out of phase from the target (i.e., you remain directly opposite the target on the orbit).
In that case, the kOS `my:Velocity - target:Velocity` will be twice your orbital velocity, as the ships are moving in opposite directions with respect to Kerbin.
However, in the LVLH frame, which rotates with the target, neither ship is moving: the markers on the navball will indicate whatever tiny deviation there is from the ideal "same orbit" setup, and the navball speed display will indicate a very small speed.

> I was able to reproduce it reliably when I opened the issue. Can you let me know the Principia version at the time of the issue? I still have principia releases from Christoffel, I can try to recreate it in that version and then the current one. Let's see if that works.
Edit: It was probably Dedekind. I will try with that one first.

Yes, I think it was Dedekind.

**Comment by eggrobin** [comment]
OK, by following your instructions, I have reproduced it, but only via the "launch a new vessel" path; taking control of a previously-launched vessel (such as the vessels in the save you linked above) results in a working SAS for me.
Going to the space centre and then back to the vessel via the tracking station fixes the behaviour of the SAS.
Further, I do not need to quit KSP to reproduce the behaviour again, only to launch another vessel.

**Comment by eggrobin** [comment]
Weirder still: launching to orbit reliably reproduces the bug, but launching to a suborbital trajectory does not.

**Comment by eggrobin** [comment]
> Weirder still: launching to orbit reliably reproduces the bug, but launching to a suborbital trajectory does not.

Nevermind; it seems a critical factor in reproducing this bug is whether SAS is turned on before launching: if SAS is turned on prior to launch, the SAS will keep its stock behaviour and thus ignore the plotting frame; if it is turned on after launch, it will follow the plotting frame.
