### ISSUE TITLE
Support with a mod that could do maneuver nodes automatically

### ISSUE THREAD

**Issue by EthanWang706** [mockingbirdnest/Principia#1871]
Another request, now in RO, it's seriously such a hard thing to adjust orbit in a high accuracy with hand, and now, I didn't find a mod that could do maneuver nodes automatically, which is hard when you want to fly by many planets, a little 0.01m/s would just make your spacecraft off target for millions of km.

**Comment by pleroy** [comment]
@lamont-granquist is working on closed-loop guidance compatible with the Principia manœuvres, see #1659.

**Comment by EthanWang706** [comment]
Yeah, but when you're trying to save delta-v, you have to choose between saving delta-v or do a not-so-accurate burn, it's kind of hard sometimes, especially when you're trying to go for Voyager 2's orbit,  somehow, after leaving Earth, adjusting orbit to flyby Jupiter, I only have about 200m/s of delta-v, which I have to thing a lot about how to adjust orbit in limited amount of delta-v, and I can control burning properly. Anyway, if Principia could do maneuvers itself, then my work is to just work on those maneuver nodes and don't need to worry about  doing them

**Comment by lamont-granquist** [comment]
It isn't a solvable problem to that accuracy.  Period. 

I am working on code for MechJeb that will execute burns so that it can probably execute an interplanetary burn and hit the target periapsis at the destination planet within a few 10s of km or so.  You're still going to pack some dV for mid-course burns, and burns near the flyby periapsis to fine-tune the next transfer orbit.  That alone is a hard enough problem.

**Comment by EthanWang706** [comment]
Yes, after playing too much stock KSP, sometimes I just want to save as much dv as possible, but that doesn't work here, so maybe I need to change my mind. Yeah, if MechJeb could so maneuvers, then for me, it's easier than me trying to not mess up so bad.

**Comment by pleroy** [comment]
I am going to close this issue as I think that the discussion has clarified the expectations.

**Comment by lamont-granquist** [comment]
https://github.com/MuMech/MechJeb2/issues/1062
