### ISSUE TITLE
Is there a way to auto execute maneuvers?

### ISSUE THREAD

**Issue by njbrown09** [mockingbirdnest/Principia#1894]
As the title said, is there a way i can either auto execute a node OR make the navball deltav work properly?

**Comment by pleroy** [comment]
See the discussion in #1871.  @lamont-granquist is working on beefing up MechJeb to do that.

**Comment by njbrown09** [comment]
Thanks.

**Comment by lamont-granquist** [comment]
https://github.com/MuMech/MechJeb2/issues/1062
