### ISSUE TITLE
Principia Not working in deepin(linux)15.6

### ISSUE THREAD

**Issue by GysdfHome** [mockingbirdnest/Principia#1899]
principia.so will not be found

**Comment by pleroy** [comment]
Sorry, we only know how to support Ubuntu.  For any other Linux distros (it's the first that that I hear about deepin) you're pretty much on your own.  You should check that `principia.so` lives in the right directory (`GameData/Principia/Linux64`) and figure out how KSP (or the system loader) decides in what directories it looks for shared libraries.

If you find some configuration change that should be merged upstream, feel free to send us a pull request.
