### ISSUE TITLE
Not Normal Warp Speed In RSS

### ISSUE THREAD

**Issue by EthanWang706** [mockingbirdnest/Principia#1908]
In RSS, using Principia and RO and 16K texture, only 2 craft in orbit, after warping for 10 minutes, only 4 month has passed, with 1 million times speed.
I want to know if this is a bug, or this is a normal warp speed

**Comment by pleroy** [comment]
4 months in 10 minutes is about 20,000x, this seems slow.  Our experience is that it's easy to get to 100,000x and that 1,000,000x is rather janky.  So things should be about 10x faster than what you report.

I quickly checked using stock KSP and Desargues that we didn't break the performance: it is roughly what I expect it to be.

It's hard to say what's happening in your case: could be interactions between mods, could be that other things are happening on your machine, that it's just not powerful enough, that it's swapping, etc.

**Comment by pleroy** [comment]
Can you give us the detailed characteristics of your machine?

**Comment by EthanWang706** [comment]
iMac Pro (2017)
CPU: Intel Xeon W-2150B
Graphic: Vega 64 16GB VRAM
Memory: 64GB DDR4 2666MHZ ECC

**Comment by pleroy** [comment]
I suspect that "less than 15%" means that you are actually CPU-bound.  Your CPU has 10 cores, but unfortunately Principia cannot use multiple cores on Mac because the C++ library support is incomplete (see the change log for [Cesàro](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#ces%C3%A0ro) where multicore support was added for Linux and Windows).

At some point in the future we will stop supporting old versions of MacOS and we'll be able to fully use your 10 cores.

**Comment by EthanWang706** [comment]
I think that's still not the issue, because from what I see, all 10 cores are pretty much using the same amount, which is confusing, I am pretty sure that my app shows how much each core uses properly, but it doesn't look like that it is only fully using 1 core.

**Comment by pleroy** [comment]
So?  This is how multicores work.  At the beginning of each frame a bundle of threads gets created, which do pure computation (100% CPU) for 10-15 ms.  Once the frame is ready to be displayed the threads are destroyed.  Over the course of a second or two the kernel is going to schedule the threads over different cores (for good reasons, e.g., balancing power usage) so it will look like all the cores are using 10% of the CPU.

**Comment by EthanWang706** [comment]
Oh, that's the point, someone told me that in Windows, things are going much better, like only use 5 minutes to warp from 1951 to 2006

**Comment by pleroy** [comment]
The upcoming release, Descartes, will abandon support for El Capitan and will be able to use the updated C++ library provided by Sierra.  We expect significant performance improvements in your case.  Let us know.

**Comment by rsparkyc** [comment]
I was seeing similar issues with timewarp, and just upgraded to Descartes, however I did not see a noticeable improvement.  I also have 2 vessels in LEO, and timewarp gets very choppy at 100,000x, and the game practically freezes at 1,000,000x.  I'm on a MacBook Pro 

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
```
```
Radeon Pro 560:

  Chipset Model:	Radeon Pro 560
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Dynamic, Max):	4096 MB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00c0
  ROM Revision:	113-C980AJ-927
  VBIOS Version:	113-C9801AU-A02
  EFI Driver Version:	01.00.927
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3
```

**Comment by EthanWang706** [comment]
@rsparkyc I switched my RO install to Windows earlier, and it is way better. Actually, your situation is way better than my, before I move it to Windows, I can get about 12fps at 10,000x, and only 1-2 at 100,000, if I try to use 1,000,000x, it's like 10-15 frame per minute, and the game time per minute  got less, also it's really hard to stop time warping. 
Using Bootcamp is a really good solution for now on this problem, I can increase time warp to 100,000x with higher than 60fps, even at 1,000,000x,  I can still get 15fps.

**Comment by pleroy** [comment]
I am going to close this issue.  Let's continue the discussion in #1955.  It seems that we are running into limitations of the mutex support in macOS.
