### ISSUE TITLE
Crash when creating or loading a save

### ISSUE THREAD

**Issue by njbrown09** [mockingbirdnest/Principia#1916]
Ksp 1.4.5 modded.
[KSP.log](https://github.com/mockingbirdnest/Principia/files/2326305/KSP.log)

**Comment by pleroy** [comment]
Nothing that we can do with `KSP.log`.  Please see https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt.

**Comment by njbrown09** [comment]
thats the problem. The game just closes but it doesnt actually produce a crash folder.

**Comment by njbrown09** [comment]
Here is the FATAL in glog

Log file created at: 2018/08/28 09:38:36
Running on machine: DESKTOP-MRO50O8
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FFC81ACD842  	principia__VesselVelocity [0x00007FFC81ACD841+231233]
    @   00007FFC81ACC74E  	principia__VesselVelocity [0x00007FFC81ACC74D+226893]
    @   00007FFC81ABA6C6  	principia__VesselVelocity [0x00007FFC81ABA6C5+153029]
    @   00007FFC81AC5A4D  	principia__VesselVelocity [0x00007FFC81AC5A4C+198988]
    @   00007FFC81A73C29  	principia__EndInitialization [0x00007FFC81A73C28+312]
    @   00000000223DDA0C  	(No symbol) [0x00000000223DDA0B]
F0828 09:38:36.128521 10140 rotating_body_body.hpp:41] Check failed: angular_frequency_ != 0.0 * SIUnit<AngularFrequency>() (+0.00000000000000000e+00 s^-1 rad vs. +0.00000000000000000e+00 s^-1 rad) Rotating body cannot have zero angular velocity

**Comment by pleroy** [comment]
We'll need the entire `INFO` file in `glog`.  We cannot decode the stack without it.

**Comment by njbrown09** [comment]
[INFO.20180828-095812.txt](https://github.com/mockingbirdnest/Principia/files/2328357/INFO.20180828-095812.txt)

**Comment by njbrown09** [comment]
Okay. It appears that sigma binary is incompatible (Makes sense) You may want to note that in the FAQ.

**Comment by pleroy** [comment]
Good point, added a blurb to the FAQs.
