### ISSUE TITLE
Crashes when I try to load a game

### ISSUE THREAD

**Issue by Catmaniscatlord** [mockingbirdnest/Principia#1965]
[errors.zip](https://github.com/mockingbirdnest/Principia/files/2489575/errors.zip)
title say it all
Mods include:
Kerberal engineer
trajectories
kerbal alarm clock
transferwindow planner

**Comment by eggrobin** [comment]
From the FATAL file:
> F1017 16:53:04.120956  8668 interface.cpp:765] Unexpected KSP version 1.5.0; this build targets 1.4.5, 1.4.4, 1.4.3, 1.4.2, and 1.4.1.

**Comment by Catmaniscatlord** [comment]
How do I go back to 1.4.5

**Comment by pdn4kd** [comment]
Depends on how you got KSP in the first place. With the store version, it's a simple matter of of keeping old zips (or redownloading them). With GOG, they may also directly offer old versions for download. With Steam it should be possible to select old versions somewhere in the right-click menu, but I'm less familiar with it. (Something about beta enrollment?) 

If you are using Steam, I strongly recommend copying your game out to a different directory in the future if you plan to use mods.
