### ISSUE TITLE
Looking for the latest compatible download for KSP 1.2.2 with Realism Overhaul

### ISSUE THREAD

**Issue by pcloof** [mockingbirdnest/Principia#1989]
I am trying to install KSP according to a video of Scott Manley with mods Realism Overhaul, Real Solar System, RSS Visual Enhancements, Scatterer and Principia. In the video Scott mentions version Cauchy to download. From the documentation it seems that there are multiple versions compatible with 1.2.2 . Can you give a download link for the latest compatible version? Or is there a page with all the older download links available? I know there is a page with the source code for all older versions, but I need the package to add to KSP's GameData folder.

I found a download link to Cardano in another issue, but I prefer to have the latest compatible version.

**Comment by pleroy** [comment]
The last version that supports 1.2.2 is Cramer.  The download link is http://goo.gl/XgRdRP.  Note that we don't investigate problems or fix bugs for old versions.

In general, it is possible to find the download links for older versions by looking at the [history of the README.md file](https://github.com/mockingbirdnest/Principia/commits/master/README.md).

**Comment by pcloof** [comment]
Thank you sir.
