### ISSUE TITLE
Cannot run Real Solar System with latest code

### ISSUE THREAD

**Issue by madman2003** [mockingbirdnest/Principia#2014]
I will try to see myself if I can understand what the problem here is, until then this is the assertion:

```
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @     0x7ff3e559a38b  principia::physics::internal_geopotential::Geopotential<>::GeneralSphericalHarmonicsAcceleration()
    @     0x7ff3e55d3c91  principia::physics::internal_ephemeris::Ephemeris<>::ComputeGravitationalAccelerationByMassiveBodyOnMasslessBodies<>()
    @     0x7ff3e55d38e0  principia::physics::internal_ephemeris::Ephemeris<>::ComputeMasslessBodiesGravitationalAccelerations()
    @     0x7ff3e55d368d  principia::physics::internal_ephemeris::Ephemeris<>::ComputeMasslessBodiesTotalAccelerations()
    @     0x7ff3e55d4405  _ZNSt3__128__invoke_void_return_wrapperIN9principia4base6StatusEE6__callIJRZNS1_7physics18internal_ephemeris9EphemerisINS1_8geometry14internal_frame5FrameINS1_13serialization15Frame_PluginTagELSD_7ELb1EEEE20FlowWithAdaptiveStepENS2_8not_nullIPNS6_28internal_discrete_trajectory18DiscreteTrajectoryISE_EEEENS_8functionIFNS9_18internal_grassmann11MultivectorINS1_10quantities19internal_quantities8QuantityINSP_19internal_dimensions10DimensionsILl1ELl0ELln2ELl0ELl0ELl0ELl0ELl0EEEEESE_Li1EEERKNS9_14internal_point5PointINSR_INST_ILl0ELl0ELl1ELl0ELl0ELl0ELl0ELl0EEEEEEEEEES13_RKNSF_22AdaptiveStepParametersElbEUlS13_RKNS_6vectorINSY_INSO_INSR_INST_ILl1ELl0ELl0ELl0ELl0ELl0ELl0ELl0EEEEESE_Li1EEEEENS_9allocatorIS1D_EEEERNS19_ISW_NS1E_ISW_EEEEE_S13_S1I_S1L_EEES3_DpOT_
    @     0x7ff3e55d43a2  _ZNSt3__110__function6__funcIZN9principia7physics18internal_ephemeris9EphemerisINS2_8geometry14internal_frame5FrameINS2_13serialization15Frame_PluginTagELSA_7ELb1EEEE20FlowWithAdaptiveStepENS2_4base8not_nullIPNS3_28internal_discrete_trajectory18DiscreteTrajectoryISB_EEEENS_8functionIFNS6_18internal_grassmann11MultivectorINS2_10quantities19internal_quantities8QuantityINSN_19internal_dimensions10DimensionsILl1ELl0ELln2ELl0ELl0ELl0ELl0ELl0EEEEESB_Li1EEERKNS6_14internal_point5PointINSP_INSR_ILl0ELl0ELl1ELl0ELl0ELl0ELl0ELl0EEEEEEEEEES11_RKNSC_22AdaptiveStepParametersElbEUlS11_RKNS_6vectorINSW_INSM_INSP_INSR_ILl1ELl0ELl0ELl0ELl0ELl0ELl0ELl0EEEEESB_Li1EEEEENS_9allocatorIS1B_EEEERNS17_ISU_NS1C_ISU_EEEEE_NS1C_IS1K_EEFNSD_6StatusES11_S1G_S1J_EEclES11_S1G_S1J_
    @     0x7ff3e5489e3f  principia::integrators::internal_embedded_explicit_runge_kutta_nystrÃ¶m_integrator::EmbeddedExplicitRungeKuttaNystrÃ¶mIntegrator<>::Instance::Solve()
    @     0x7ff3e55960ec  principia::physics::internal_ephemeris::Ephemeris<>::FlowWithAdaptiveStep()
    @     0x7ff3e5659bc7  principia::ksp_plugin::internal_pile_up::PileUp::AdvanceTime()
    @     0x7ff3e56584ff  principia::ksp_plugin::internal_pile_up::PileUp::DeformAndAdvanceTime()
    @     0x7ff3e556cadf  std::__1::__function::__func<>::operator()()
    @     0x7ff3e557a82e  principia::base::internal_thread_pool::ExecuteAndSetValue<>()
    @     0x7ff3e557a4a8  principia::base::ThreadPool<>::DequeueCallAndExecute()
    @     0x7ff3e557a77d  _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEENS_6__bindIMN9principia4base10ThreadPoolINS9_6StatusEEEFvvEJPSC_EEEEEEEEPvSI_
    @     0x7ff51a054a9d  start_thread
    @     0x7ff519c4ab23  __GI___clone
F1206 22:13:49.082738 11158 geopotential_body.hpp:624] Unexpected degree -1 Vesta
```

**Comment by pleroy** [comment]
Decoded stack:



[`physics/ephemeris_body.hpp:1139`](https://github.com/mockingbirdnest/Principia/blob/f772b71b057b64f978bbabdc95ebea2095f27018/physics/ephemeris_body.hpp#L1139)
[`physics/ephemeris_body.hpp:1208`](https://github.com/mockingbirdnest/Principia/blob/f772b71b057b64f978bbabdc95ebea2095f27018/physics/ephemeris_body.hpp#L1208)
[`physics/ephemeris_body.hpp:1238`](https://github.com/mockingbirdnest/Principia/blob/f772b71b057b64f978bbabdc95ebea2095f27018/physics/ephemeris_body.hpp#L1238)

[`integrators/embedded_explicit_runge_kutta_nystr�m_integrator_body.hpp:185`](https://github.com/mockingbirdnest/Principia/blob/f772b71b057b64f978bbabdc95ebea2095f27018/integrators/embedded_explicit_runge_kutta_nystr�m_integrator_body.hpp#L185)
[`physics/ephemeris_body.hpp:523`](https://github.com/mockingbirdnest/Principia/blob/f772b71b057b64f978bbabdc95ebea2095f27018/physics/ephemeris_body.hpp#L523)
[`ksp_plugin/pile_up.cpp:343`](https://github.com/mockingbirdnest/Principia/blob/f772b71b057b64f978bbabdc95ebea2095f27018/ksp_plugin/pile_up.cpp#L343)
[`ksp_plugin/pile_up.cpp:131`](https://github.com/mockingbirdnest/Principia/blob/f772b71b057b64f978bbabdc95ebea2095f27018/ksp_plugin/pile_up.cpp#L131)

[`base/thread_pool_body.hpp:15`](https://github.com/mockingbirdnest/Principia/blob/f772b71b057b64f978bbabdc95ebea2095f27018/base/thread_pool_body.hpp#L15)
[`base/thread_pool_body.hpp:80`](https://github.com/mockingbirdnest/Principia/blob/f772b71b057b64f978bbabdc95ebea2095f27018/base/thread_pool_body.hpp#L80)

**Comment by pleroy** [comment]
It's because of the PotatoRoids...

**Comment by madman2003** [comment]
I'll have to admit being largely clueless here. I got stuck at the point that you have a harmonic function of some kind for geopotential. And you're trying to determine how many harmonic terms to include. And this one doesn't seem to even have any terms at all. What is so special about the PotatoRoids?
