### ISSUE TITLE
crash when adding maneuver

### ISSUE THREAD

**Issue by Maarico** [mockingbirdnest/Principia#2021]
When I add a new maneuver in the flight planner KSP crashes instantly.
Thanks in advance.

[Principia.zip](https://github.com/mockingbirdnest/Principia/files/2659623/Principia.zip)

**Comment by eggrobin** [comment]
`F1208 11:37:19.325199  2976 manœuvre_body.hpp:164] Check failed: is_inertially_fixed_`

Check introduced in #1998.

**Comment by pleroy** [comment]
Erdős has been re-released.  Please download it again.
