### ISSUE TITLE
Fatal error when click in Erdos the Flight Plan of a Descartes save: "2432 manœuvre_body.hpp:164] Check failed: is_inertially_fixed_"

### ISSUE THREAD

**Issue by Growflavor** [mockingbirdnest/Principia#2025]
Upgrading Principia from Descartes to Erdos (continuing work on the EDU mission for the Mun tutorial): I am getting the following fatal error when I click "Flight Plan" to view the flight plan created in Descartes...is this to be expected?

Here is the fatal error reported in the logs (info, error & fatal):

`Log file created at: 2018/12/12 12:20:41
Running on machine: ALOE6700
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FFA0CC62C6C  	principia__ExternalGetNearestPlannedCoastDegreesOfFreedom [0x00007FFA0CC62C6B+23963]
    @   00007FFA0CC6515E  	principia__FlightPlanGetManoeuvre [0x00007FFA0CC6515D+397]
    @   00000000627D6F9F  	(No symbol) [0x00000000627D6F9E]
F1212 12:20:41.737807  2432 manœuvre_body.hpp:164] Check failed: is_inertially_fixed_ 
`
The above error & crash occurs in the same way when  I attempt to open the Flight plan in this Descartes save in both KSP 1.3.1 & 1.4.5 updated to Erdos.

Here is a link to the screenshot HD 1080p video of the process leading to the fatal crash event (google is still processing it so it may take some time for Google to display the 1080p version):

https://photos.app.goo.gl/NjrfZ3HpUXXo2Liw6

Here is a screenshot from when I built the flight plan in this save using Principia Descartes:

https://i.imgur.com/aBibzwS.png

I look forward to your insights.  Thanks!

**Comment by pleroy** [comment]
From your screenshot, it seems that you downloaded Erdős before December 8, 18:30 UTC, in which case you got a buggy version (see #2020) which was failing on any attempt to create a flight plan.  If you re-download and re-install Principia, you should be good (we updated the binary).

If the problem persists after re-downloading, please let us know.

**Comment by Growflavor** [comment]
Thank you!

Indeed I saw only the 1st hot fix post..must have used "flight plan" only in my search in git rather than also the KSP forum page...also a reminder that I need to check 'closed' issues #2021  rather than just scanning the open ones! ...will chalk that off as due to recovering from being quite sick the past week.

I can see the flight plan again :-) Used a different browser to download again today...shows as the following in game which is different from the 3rd KSP forum post:

2018120707-Erdős-0-g3e2334a95bcfc6869b5464ecda5ae48b5412dba0

https://i.imgur.com/bRTAnVQ.png

RE: KSP forum post: " Another serious issue was found with the Erdős release (#2021, adding a manœuvre to a flight plan would cause a crash, effectively rendering flight planning unusable), so we have hotfixed it again; if you downloaded Erdős prior to this post, please download it anew (the version string in the Principia UI should say **3e2334a95bcfc6869b5464ecda5ae48b5412dba0**, not 773e6fbad7f9fb59790de49fde48650d9451a278 or f772b71b057b64f978bbabdc95ebea2095f27018﻿)."

Thanks again!

**Comment by pleroy** [comment]
I think it's the same version string (you've got to skip the leading "g" that's put there by git).
