### ISSUE TITLE
Take the engine thrust limiter into account in manœuvres

### ISSUE THREAD

**Issue by Kinexity** [mockingbirdnest/Principia#2128]
Would this be possible to implement inclusion of engine's thrust offset in maneuver planning? For ex.  it's hard to set capture burn correctly from interplanetary trajectory with ion engine when you can't supply enough energy.

**Comment by pleroy** [comment]
You'll need to provide more details as I have no idea what you are asking.  Specifically, what do you mean by "thrust offset"?  How does that relate to ion engines?

**Comment by Kinexity** [comment]
I meant "thrust limiter" (i'm not native english speaker so mistakes happen). In flight planning, when you create a maneuver it's duration is calculated as if you were using 100% thrust of engines, which is the opposite to what stock maneuvers do (they take into account previously set thrust limit). What I would like to propose as a feature is to make Principia maneuver planning do the same (so if someone for ex. would set thrust limiter to 50 their maneuver's duriation and trajectory would have been calculated with that taken into account).

**Comment by pleroy** [comment]
I see, thanks for the clarification.

**Comment by pleroy** [comment]
Reopening as we had to revert the change while building Fáry: the API we use didn't exist prior to 1.5.1.

Also, we should do the same for RCS.

**Comment by pleroy** [comment]
This won't be fixed in Fatou (June) because Fatou will be the last version supporting 1.3.1.  This bug will likely be fixed in Fermat (July) once we stop supporting versions prior to 1.5.1.
