### ISSUE TITLE
Chromium requirement to build?

### ISSUE THREAD

**Issue by cseelhoff** [mockingbirdnest/Principia#2139]
In Principia-master\Google\glog\vsprojects\libglog\libglog.vcxproj there seems to be a reference to "..\..\..\chromium\base\memory\singleton.cc" which is causing my build to fail on Windows. Do I need to clone the chromium git repo to get this to work? It seems like the last version that chromium had with this file was tags/64.0.3282.204

**Comment by eggrobin** [comment]
> Do I need to clone the chromium git repo to get this to work?

Yes (at least partially). See the instructions fro building Principia on Windows: https://github.com/mockingbirdnest/Principia/blob/master/documentation/Setup.md.
