### ISSUE TITLE
Extending the external API to allow for interaction with flight planning

### ISSUE THREAD

**Issue by RCrockford** [mockingbirdnest/Principia#2144]
I would like to be able to read (and potentially modify) flight planning manoeuvre nodes from another mod (specifically kOS). This allows for instance the ability to plan a manoeuvre and then have it automatically executed by a flight computer.

I am proposing extending the external API to give access to functions such as (not an exhaustive list):
principia__FlightPlanExists
principia__FlightPlanGetManoeuvre
principia__FlightPlanGetGuidance
principia__FlightPlanGetInitialTime

**Comment by RCrockford** [comment]
Having thought this through more, the actual set of functions would be (this is an exhaustive list):

- FlightPlanNumberOfManoeuvres - the number of of manoeuvres in the vessel flight plan, or zero if none / no flight plan.
- FlightPlanGetManoeuvreInitialTime - initial time for indexed manoeuvre on vessel.
- FlightPlanGetManoeuvreDuration - duration for indexed manoeuvre on vessel.
- FlightPlanGetManoeuvreGuidance - guidance vector for indexed manoeuvre on vessel (in game space). Magnitude of vector equal to required delta-V.

Specifying an invalid vessel or manoeuvre index would throw an exception.

These are all read only, as allowing write access to the flight planning is a rather more complicated task.

One obvious issue is that manoeuvres are indexed, and may change if the user alters the flight plan. I don't currently have a good solution for notifying any external mods of this occurring.

**Comment by pleroy** [comment]
(Sorry for the late answer, been busy.)

All these APIs seem to make sense, and look stable enough that we could implement them no matter what we do with the flight plan in the future.

I might take a stab at implementing them for the next version (del Ferro).

**Comment by eggrobin** [comment]
They make sense, but it is not clear whether they are needed after all; quoth @RCrockford on discord:
> I kinda dropped the kOS integration for principia as you can do basically everything using the stock manoeuvre node integration.

Closing this for now.
