### ISSUE TITLE
The icon for KSC sometimes move when changing the orientiation of vessel

### ISSUE THREAD

**Issue by MiracleMagician** [mockingbirdnest/Principia#2155]
https://youtu.be/FFZsG0_NOyQ

**Comment by MiracleMagician** [comment]
I'm playing on 1.6.1 with version Fáry, didn't notice this slight glitch in previous versions

**Comment by MiracleMagician** [comment]
Oof, time wrap does this too
https://youtu.be/TPbTORK_o3s

**Comment by eggrobin** [comment]
Where does this KSC icon come from?
It is not present in stock KSP 1.6.1; it looks like the flag icon, but even by planting a flag at KSC, I am unable to reproduce the issue you report; the flag stays where it should be when spinning the spacecraft or timewarping.

**Comment by MiracleMagician** [comment]
Wait what? The flag icon indicating position of KSC should be stock... I tried removing all my mods and Making history but it's still there
![Oof](https://user-images.githubusercontent.com/50024118/57568016-085d2200-7414-11e9-855e-4ba493105408.png)

**Comment by eggrobin** [comment]
> Where does this KSC icon come from?
It is not present in stock KSP 1.6.1

Nevermind, it is, I was confused (it's been too long since I actually played that game, I didn't know about it).

Still can't reproduce the issue though.

**Comment by MiracleMagician** [comment]
I tried several times, but unable to think out the steps to reproduce it. But i'm rather sure to get the situation in the first video happen, camera view should be focused on vessel, and it happens most when vessel have some distance from kerbin

**Comment by pleroy** [comment]
@MiracleMagician Unrelated question: I notice that your UI is in simplified Chinese.  We recently put our zip files on 腾讯微云 in the hope of making things easier for users in mainland China (see the [README](https://github.com/mockingbirdnest/Principia/blob/master/README.md)).  Is this useful at all?

**Comment by MiracleMagician** [comment]
Ehh, since google drive is banned in China I'm pretty sure that would help. Actually I still downloaded Fáry from google drive since I basically have VPN on 24/7...

**Comment by MiracleMagician** [comment]
I did a test downloading from 微云 with VPN off. It downloads at a steady 900kb/s without needing to login / download a client, so pretty fine!

**Comment by MiracleMagician** [comment]
Okay I have to close this issue, silly me... Just because I noticed this glitch after I installed principia doesn't mean it is caused by it. I'll try to figure out what mod does this, and sorry for wasting you two precious time.
