### ISSUE TITLE
Sometimes the AP/PE point doesn't have ap/pe written on it.

### ISSUE THREAD

**Issue by MiracleMagician** [mockingbirdnest/Principia#2156]
https://i.imgur.com/16j8Rhw.png
Yeah, again, a small visual glitch I didn't notice in previous versions. Am I getting a little annoying by keep reporting minor issues?

**Comment by eggrobin** [comment]
I have encountered this kind of issue before (and it did happen in previous versions), I thought I had managed to get rid of all of its occurences; apparently I missed some.

Can you provide reproduction steps? “sometimes” is not very specific, and unless I can deterministically reproduce the issue, it is going to be hard to figure out what is going on.

**Comment by eggrobin** [comment]
I appear to have reproduced this by changing between reference frames a lot; I may have an idea as to what is going on, I will add some traces and investigate.

**Comment by pleroy** [comment]
By the way, please keep reporting these issues: they are very useful to us and we appreciate that you take the time to make Principia better.
