### ISSUE TITLE
Performance hit when flight plan window is opened

### ISSUE THREAD

**Issue by MiracleMagician** [mockingbirdnest/Principia#2157]
FPS keeps at 60 when flight plan window is closed, even with sigificantly long plan is plotted.
But when flight plan window is opened and with a long plan present, the game can be a bit laggy, running lower than 40fps, and drop lower than 30 when moving the map around.
CPU usage is around 45% and GPU is below 10% when lagging, so it is likely not caused by hardware limitation.

**Comment by MiracleMagician** [comment]
My description was a bit wrong. Only when there's a manoeuvre, a long flight plan and flight plan window is opened there will be FPS drop

**Comment by pleroy** [comment]
I was able to reproduce the problem.

**Comment by pleroy** [comment]
Profiling a journal:
```
Read                         23%
FlightPlanReplaceLast        17%
UpdatePrediction             12%
PlanetariumPlotPrediction    6%
PlanetariumPlotFlightSegment 4%
```

**Comment by eggrobin** [comment]
For future reference: this issue was introduced in Fano, not Fáry (that is, during the restructuring of the UI code, rather than the introduction of text input).
