### ISSUE TITLE
Portable macros

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#216]
We need portable macros for thing like `__cdecl` vs. `__attribute__((cdecl))` vs. nothing, `__dllexport` vs. `__attribute__((visibility("default")))`, `__forceinline` vs. `__attribute__((always_inline))`.
`base/macros.h` and `base/compiler_specific.h` from chromium don't quite cover what we need, but we can build upon them (we will already depend on them with `stack_trace`).
`build/build_config.h` also contains some useful macros for OS-specific or compiler-specific things (we need some for clang though).

**Comment by pleroy** [comment]
Let's add macros iff we need them.
