### ISSUE TITLE
Game froze the moment craft launched

### ISSUE THREAD

**Issue by yafeshan** [mockingbirdnest/Principia#2173]
https://gist.github.com/yafeshan/68ae0c4263bc42ca3e31fc1b94968291

I included Info file just before freeze, persistent save file and Fatal file created for freeze.

Game is frozen the moment i started engine and loose clamps. It crashed after a minutes or so. There is no problem as long as craft stays on launchpad.

**Comment by pleroy** [comment]
For our information, decoded stack:
 https://github.com/mockingbirdnest/Principia/blob/933d2219c634c46158e41fe90002ad2509fcdfe7/ksp_plugin/interface.cpp#L993-L997  https://github.com/mockingbirdnest/Principia/blob/933d2219c634c46158e41fe90002ad2509fcdfe7/ksp_plugin/plugin.cpp#L603-L620 



https://github.com/mockingbirdnest/Principia/blob/933d2219c634c46158e41fe90002ad2509fcdfe7/ksp_plugin/pile_up.cpp#L97-L104

**Comment by pleroy** [comment]
From the INFO log:
```
I0519 02:17:05.609725 10040 part.cpp:137] Adding part KJRsensor1 (00000000) to the pile up at 00000000F9623110
```
A part with an id of 0 is extremely suspicious.  Seems to come from KJR next.  Use KJR continued until @ferram4 returns.
