### ISSUE TITLE
Flight plan error message wording

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#2222]
On a flight plan with no manœuvres, it is possible to get `flight plan final time overlaps the last manœuvre`. This is obviously incorrect.

https://github.com/mockingbirdnest/Principia/blob/782fdc624aa41c390be8e3364c80fe91e26f547a/ksp_plugin_adapter/flight_planner.cs#L482-L486

**Comment by pleroy** [comment]
Part of the problem is that when an error message is displayed, and the flight plan is destroyed and recreated, the error message persists.

**Comment by pleroy** [comment]
Also, we run into trouble when the flight plan is shorter than 60 seconds.
