### ISSUE TITLE
Prediction plotting in tracking station is slightly broken under certain conditions

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#2257]
If you take control of any craft orbiting a body other than Kerbin (Mun, Minmus, whatever) and then jump directly to the tracking station (without going to the KSC first), the vessel orbits (any vessel you select) in tracking station are plotted with respect to that body. What's weird is that the node markers (eg Ap) have a text saying "Kerbin Apoapsis" but I can't quite figure out where the values are coming from. They don't seem to be calculated either with respect to Kerbin or that body.
In addition the Principia main window shows plotting frame to be Kerbin Inertial.
If you click on the plotting frame settings (ie open that dialog box) the plotting frame immediately changes to Kerbin Inertial and all labels and values are also fixed.

**Comment by eggrobin** [comment]
This sounds like https://github.com/mockingbirdnest/Principia/issues/2196#issuecomment-500119032, which mystified me; investigating should be easier now that you have reproduction steps (this will probably not be addressed in Ferrari though).

**Comment by eggrobin** [comment]
#2196 is probably a separate issue after all.
