### ISSUE TITLE
Principia UI visibility at KSC

### ISSUE THREAD

**Issue by SirMortimer** [mockingbirdnest/Principia#2262]
If you have the Principia UI open and switch to any building except one of the editors (VAB/SPH), the UI stays open with no way to close it. Since it is of no use, I suggest hiding the window in
* R&D
* Mission Control
* Astronaut Complex
* Administration

**Comment by pleroy** [comment]
Good point.  Now the question is, how do we figure out what scene is displayed? 
 [DetermineVisibility](https://kerbalspaceprogram.com/api/class_k_s_p_1_1_u_i_1_1_screens_1_1_application_launcher.html#a2a8c57366faea3152bb803cd0a2ab556) might help us figure out if our button is shown, and if not, hide the main window.

**Comment by SirMortimer** [comment]
Maybe you can use `HighLogic.LoadedSceneIsFlight || HighLogic.LoadedSceneHasPlanetarium`
