### ISSUE TITLE
Control point up / forward won't affect the navball

### ISSUE THREAD

**Issue by SirMortimer** [mockingbirdnest/Principia#2267]
Since KSP 1.6ish(?) it is possible to change the nav ball orientation by adjusting the control direction. The stock KSP navball will change its orientation when that mode changes, which is of great utility when steering a rover to a waypoint, because you can actually see which direction you're going. Just like flying a plane.

See attachment

<img width="1138" alt="Bildschirmfoto 2019-08-07 um 23 02 40" src="https://user-images.githubusercontent.com/43166475/62658646-8bd1d500-b969-11e9-99be-7fea5e21174c.png">

**Comment by eggrobin** [comment]
I am unable to reproduce it with Ferrari.

**Comment by SirMortimer** [comment]
To reproduce, you need to build the ship in a specific way:

Take a normal probe core (it must be the root part), attach a decoupler, and to that decoupler attach a rove mate. In flight, decouple the probe core from the rove mate.

It's probably a bug in stock KSP and not related to principia.

Closing this issue.
