### ISSUE TITLE
Keep the whole history

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#228]
For the moment we compute the histories using `sampling_period == 0`, which results in large gaps in the trajectory at high timewarp (rendered as long straight line segments, see below).  We should use `sampling_period == 1` instead, and downsample ourselves as needed when rendering.
![screenshot8](https://cloud.githubusercontent.com/assets/2284290/4780431/6b346bfe-5c68-11e4-9093-9b9af84bf963.png)

**Comment by pleroy** [comment]
Blocked by #973.

**Comment by eggrobin** [comment]
@aw1621107  reports impact; the visual appearance has changed with the Чебышёв interpolated plotting, we now get weird loops instead of straight segments:
![](https://i.imgur.com/Uanelz6.jpg)
![](https://i.imgur.com/bqkqtNz.jpg)
