### ISSUE TITLE
Commit the histories to disk after a while.

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#229]
As time goes on, the histories of the celestials and vessels will be get longer. In order to prevent unnecessary memory usage (since we will not be rendering them most of the time) but still enable looking back in time, we should commit them to disk.
Protobuf would probably be a good choice.
(Note that this is separate from the persisting to disk which must be done to support saving. Saving will have to work with the strange, escapeless, newline-delimited KSP cfg format, whereas here we are free to cache things in protobuf binary format if we so desire.)

**Comment by pleroy** [comment]
Will be fixed as part of #934.
