### ISSUE TITLE
Provide checksum for release

### ISSUE THREAD

**Issue by kc9jud** [mockingbirdnest/Principia#2300]
Binary releases should have a SHA-256 checksum, both for ensuring download success/integrity as well as to provide a bit of confidence about the source. (I remember being sketched out the first time the download link took me to Google Drive.)

Ideally, the checksums should be in the repository itself (maybe in README.md) rather than in the wiki. It would also be great if the commit is GPG-signed by @eggrobin or @pleroy.

**Comment by eggrobin** [comment]
To quote the README,
> if you don't trust our binary, build the mod from the Ferrari release.

Building these binaries on multiple platforms every month is already an exceedingly tedious process; we are not interested in adding further steps steps to that process.

What you suggest would make perfect sense if this were a professional project; however, I would like to remind you that this is an entirely volunteer effort, from which we gain no benefit other than the entertainment value of astrophysics and numerical analysis.
