### ISSUE TITLE
Try setting the points in for the VectorLine directly from C++

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#231]
This may be possible using C# unsafe magic:
```c#
fixed (UnityEngine.Vector3* pts = rendered_trajectory_.points3) {
// pass pts using P/Invoke and let it do the iteration.
```
It would remove the clumsy iteration through P/Invoke and remove at least one copy of the whole rendered trajectory every frame.

**Comment by pleroy** [comment]
Will be OBE as part of #934.
