### ISSUE TITLE
Add support for course corrections

### ISSUE THREAD

**Issue by zroug** [mockingbirdnest/Principia#2315]
Maneuver nodes can never be executed 100% accurate. It would be very helpful to have an option to refresh the flight plan after a maneuver, so that it uses the new predicted flight path. You could then simply adapt the future nodes to the change and you would not have to recreate the complete flight plan. As a bonus it would be useful to be able to add maneuver nodes between existing nodes, so that you can add correction maneuvers.

**Comment by pleroy** [comment]
The capability to "Rebase" a flight plan, added in [Gallai](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#gallai), is intended to support exactly this use case.

**Comment by zroug** [comment]
This is great, thank you! :tada:
