### ISSUE TITLE
Crash on extending manoeuvre start time to end of flight plan

### ISSUE THREAD

**Issue by nepphhh** [mockingbirdnest/Principia#2331]
First crashed to desktop, no windows dialog. Same thing happened later that day, crash to desktop this time with a long hang before dying and with a Windows dialog.

Gist will come after I get out of lab. Tried to upload and github 404'd on me twice. Later.

**Comment by eggrobin** [comment]
@nepphhh I think you can attach a file to an issue directly, that might be easier than copying the logs into a gist.

**Comment by nepphhh** [comment]
[Principia.zip](https://github.com/mockingbirdnest/Principia/files/3622647/Principia.zip)

**Comment by eggrobin** [comment]
```
F0916 12:26:43.506275  9684 manœuvre_body.hpp:209] Check failed: it != coasting_trajectory_->End() 
```

This is somewhat reminiscent of #2188.

**Comment by nepphhh** [comment]
As far as I can remember, that issue is identical to mine.

**Comment by pleroy** [comment]
Decoded stack trace:

 https://github.com/mockingbirdnest/Principia/blob/d541b66c483a4d2bc435625938499c1a399aa922/ksp_plugin/interface_flight_plan.cpp#L246-L253  https://github.com/mockingbirdnest/Principia/blob/d541b66c483a4d2bc435625938499c1a399aa922/ksp_plugin/man%C5%93uvre_body.hpp#L174-L176  https://github.com/mockingbirdnest/Principia/blob/d541b66c483a4d2bc435625938499c1a399aa922/ksp_plugin/man%C5%93uvre_body.hpp#L205-L209
