### ISSUE TITLE
Increase pilots experience when flying to lagrange points

### ISSUE THREAD

**Issue by vladtcvs** [mockingbirdnest/Principia#2346]
I've made a big tour through L1-L5 points, it was not very trivial, but pilot got no experience.

**Comment by pleroy** [comment]
We do not integrate with the career mode and have no plans to do so.

On the positive side, what you describe is a simple geometric check (within some distance of the Lagrange points for some time) and doesn't need to be integrated with Principia at all.  So if you feel like writing a mod to do that, it might be cool :-)
