### ISSUE TITLE
Check failed and game instantly closes, didn't happen yesterday

### ISSUE THREAD

**Issue by TransparentElemental** [mockingbirdnest/Principia#2360]
[my save.zip](https://github.com/mockingbirdnest/Principia/files/3750912/my.save.zip)
It just closes when i reach the mark of 140km (vacuum) in RSS. No crash windows, no crash logs are generated, no nothing as if i pressed Alt+F4 and closed the game. No additional mods were installed before this began to happen. Here are the latest INFO and FATAL logs.
https://gist.github.com/TransparentElemental/82c1f22fd520c65fda91895847ccd415

**Comment by pleroy** [comment]
Decoded stack trace:

 https://github.com/mockingbirdnest/Principia/blob/4b8edaa129b72e5f9d2bcf664b6901833ee19e96/ksp_plugin/interface.cpp#L807-L819  https://github.com/mockingbirdnest/Principia/blob/4b8edaa129b72e5f9d2bcf664b6901833ee19e96/ksp_plugin/plugin.cpp#L425-L469  https://github.com/mockingbirdnest/Principia/blob/4b8edaa129b72e5f9d2bcf664b6901833ee19e96/ksp_plugin/part.cpp#L50-L51

**Comment by TransparentElemental** [comment]
Not principia's fault.

**Comment by eggrobin** [comment]
The culprit here seems to have been Kerbalism.
Quoting @gotmachine on Discord:
> New Kerbalism dev build 7237 available, contains the following fixes :
> - "invalid situation" when transitioning over the default biome (ex : shores on earth)
> - Fix a NaN error happening when running out of EC while having an experiment that doesn't require any EC (was causing KSP crashes if you were using Principia)
> - Fix sample masses being incorrectly registered
> Get Kerbalism-Core from here : https://github.com/Kerbalism/DevBuilds/releases/tag/DevBuild-7237
> Thanks to everyone that provided help on these issues.
