### ISSUE TITLE
Incompatibility with Extraplanetary Launchpads

### ISSUE THREAD

**Issue by Mogball** [mockingbirdnest/Principia#2419]
I'm not sure if this belongs on the EPL Github or here, but:

In EPL, special parts allow the construction of vessels in orbits or on other planets. When clicking "Finalize" to spawn the new vessel, Principia crashes:

```
Log file created at: 2019/12/28 16:43:45
Running on machine: 
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FFAF2BD633A  	google::LogMessageFatal::~LogMessageFatal [0x00007FFAF2BD6339+57]
    @   00007FFAAD55933C  	principia__VesselVelocity [0x00007FFAAD55933B+673067]
    @   00007FFAAD57183F  	principia__VesselVelocity [0x00007FFAAD57183E+772654]
    @   00007FFAAD498365  	principia__InsertUnloadedPart [0x00007FFAAD498364+564]
    @   00000000206AFFEC  	(No symbol) [0x00000000206AFFEB]
F1228 16:43:45.887115 15564 plugin.cpp:1499] Check failed: inserted part_id: 0
```

Related issue(s): https://github.com/taniwha/Extraplanetary-Launchpads/issues/152

**Comment by pleroy** [comment]
What we call `part_id` is called `part.flightID` by KSP.  We use it to uniquely identify the parts.  All the parts created by KSP (and most mods) have a unique id, which can be generated by `ShipConstruction.GetUniqueFlightID(HighLogic.CurrentGame.flightState)`.  It seems that this mod leaves the id 0, which makes it impossible for us to store parts in our data structures.

The bottom line is: Extraplanetary Launchpads has a bug and there is not much that we can do on our side.

**Comment by Mogball** [comment]
Thanks, this is insightful! I'll update the EPL issue.
