### ISSUE TITLE
Limitations on Concepts page needs to be updated 

### ISSUE THREAD

**Issue by rsparkyc** [mockingbirdnest/Principia#2462]
Currently it says that Principia does not handle the trajectories of a celestial, however I believe it now does: https://github.com/mockingbirdnest/Principia/wiki/Concepts#limitations

**Comment by pleroy** [comment]
Went through the [Concept](https://github.com/mockingbirdnest/Principia/wiki/Concepts) and [FAQ](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions) pages, removed outdated stuff, added some new information.
