### ISSUE TITLE
Going through the ground on the Moon

### ISSUE THREAD

**Issue by damianreds** [mockingbirdnest/Principia#2472]
Vessel goes through the surface of the Moon, crashes roughly 5km further down below and game crashes as well.
Stock altitude indicator at surface level reads 5km, probably difference between Altitude and Altitude(True) however Vessel does not have avionics hence can't get that reading from MechJeb. 

KSP 1.7.3, RSS 16.4, Kopernicus 1.7.3-2, Vannadin's RSS Textures 2.0.0 (not sure if relevant)

Log Files:

ERROR.20200215-201908.13156.log
https://gist.github.com/damianreds/b0a4e18760461ead840b96619b046374

FATAL.20200215-203351.13156.log
https://gist.github.com/damianreds/ada581c4612e18851de860bbf1ba49f4

INFO.20200215-200240.13156.log
https://gist.github.com/damianreds/ea2072a4d72a34904d7d71ffb28f205b

**Comment by pleroy** [comment]
I suspect that the vessel is being destroyed and that as part of this KSP ends up with a vessel having no parts at all, and we trip on this.

But the real question is: why do we go through the ground?  Would you by any chance be able to give us a save created when you're below the surface (but not crashed yet)?  That would help a lot in understanding the sequence of events.

**Comment by damianreds** [comment]
thanks for your follow-up! as reported in the forum thread, reverting the aforementioned custom RSS texture pack to a previous, known-to-work-with 1.7.3 version did the trick. would you still be interested in that save file in the moment the vessel goes through the surface but has not yet crashed? if so I can produce it this week.

**Comment by pleroy** [comment]
I don't think that a save would be useful at this point.  Principia is clearly not the culprit, so it's not worth your time or my time debugging the textures (which we had to do once already, see #2447).  I am going to close this issue.
