### ISSUE TITLE
Ability to display lagrange points, or more importantly, use it as a reference-frame.

### ISSUE THREAD

**Issue by feha** [mockingbirdnest/Principia#2476]
One of the things I like the most about principia is the ability to jump between reference-frames at will. The n-body physics is a major part why I use the mod, but still only secondary to this feature (in fact, at times the lag makes me kinda want to return to SOI's but keep the plotting :p). 
As such, I feel it would make some amount of sense to have the ability to use the lagrange-points emerging from the n-body physics the mod adds, as an option with the plotting-frames.

Of course, it is not entirely straight-forward, as for example there would  #be no rotation like a body has. Neither would there be a mass large enough to be visible naturally in map-screen. Meaning you can't just treat it as a body. Instead I imagine it would be more similar to using a Target as the reference (potentially even possible to re-use that exact system by creating a fake "vessel" that is pretend-targeted - to avoid removing real target - and referenced by the same functionality?).

This suggestion is similar to #1843 , except not just highlighting the point on the map, but more importantly plotting things relative to it.

**Comment by pleroy** [comment]
Closing as the rotating-pulsating frame introduced in [ابن الهيثم](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#%D8%A7%D8%A8%D9%86-%D8%A7%D9%84%D9%87%D9%8A%D8%AB%D9%85) addresses this issue properly.
