### ISSUE TITLE
No metions of Persistent Rotation

### ISSUE THREAD

**Issue by DarthPointer** [mockingbirdnest/Principia#2510]
As for now Principia handles impulse momentum conservation. P.R. mod handles* it too. Do Principia and P.R. interfere and work fine if both are installed? It would be great to have a big red warning in the wkik if they should not be used together.

*I'm not 100% sure it does right.

**Comment by eggrobin** [comment]
Please read the [change log](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#frobenius) which answers your question.

> If you have been using PersistentRotation, we recommend that you uninstall it as the two mods would fight each other and PersistentRotation is not physically correct anyway.

**Comment by DarthPointer** [comment]
It is not jsut a question. A few days have passed since the release and there is only one mention of it in the changelog. Please make a more noticable warning about this mod.
