### ISSUE TITLE
Feature suggestion: Automatic maneuver for vessels in an unstable orbit

### ISSUE THREAD

**Issue by t-liu93** [mockingbirdnest/Principia#2540]
I have a feature suggestion: 

In n-body environment, vessels in orbit such as the halo orbit around Earth-Moon L2 Lagrange point is an unstable orbit. In order to keep the vessel in the correct orbit, a regular maneuver has to be applied regularly (+/- 45 days). 

This kind of regular maneuver is a little bit difficult/inconvenient for the players to apply, as during time warp, 45 days are easily passed. 

I am wondering if it's possible to add a feature to let the players add a group of automatic maneuver points, so Principia calculates the required delta-v for the maneuver, and performs the maneuver to correct the orbit, then update the fuel and delta-v on the vessel.

This would be really helpful for long term missions.

**Comment by pleroy** [comment]
Closed-loop control is out of scope for Principia.  It *could* be handled by a separate mod, possibly using APIs.  (@lamont-granquist has expressed interest in some areas of closed-loop control.)
