### ISSUE TITLE
The Principia DLL failed to load.

### ISSUE THREAD

**Issue by lolotux69** [mockingbirdnest/Principia#2557]
Hi

I'm under Linux!
$ uname -a
Linux debian 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Here my KSP.log
[KSP.log](https://github.com/mockingbirdnest/Principia/files/4589259/KSP.log)

And my folders : 
$ tree Principia/
Principia/
├── assets
│   ├── navball_barycentric.png
│   ├── navball_body_direction.png
│   ├── navball_compass.png
│   ├── navball_inertial.png
│   ├── navball_surface.png
│   ├── navball_target.png
│   └── toolbar_button.png
├── ksp_plugin_adapter.dll
├── ksp_plugin_adapter.dll.config
├── ksp_plugin_adapter.pdb
├── Linux64
│   ├── principia.dll
│   └── principia.so
├── MacOS64
│   ├── principia.dll
│   └── principia.so
├── real_solar_system
│   ├── gravity_model.cfg
│   ├── initial_state_jd_2433282_500000000.cfg
│   └── sol_numerics_blueprint.cfg
└── x64
    ├── libglog.dll
    ├── libprotobuf.dll
    ├── principia.dll
    ├── principia.pdb
    ├── serialization.dll
    └── serialization.pdb

5 directories, 23 files

:/

**Comment by pleroy** [comment]
> I'm under Linux!

You're under Debian.  We build for Ubuntu.  There is no telling if a binary built for one system will work for the other.

>├── Linux64
│   ├── principia.dll
│   └── principia.so
├── MacOS64
│   ├── principia.dll
│   └── principia.so

These `principia.dll` files under `Linux64` and `MacOS64` are strange.  They are probably not the source of the problem, but they didn't come directly from the install.

Anyway, do you have a recent version of `libc++abi` installed?  The error message talks about 6.0.2, but I think you need version 8 these days.

**Comment by hdszcg-ksp** [comment]
i have the exact same problem!! the macosx64 and linux64 also  shows for me

**Comment by lolotux69** [comment]
sudo apt list --installed | grep -i libc++

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libc++abi-7-dev/stable,now 1:7.0.1-8 amd64  [installé]
libc++abi-dev/stable,now 1:7.0-47 amd64  [installé]
libc++abi1-7/stable,now 1:7.0.1-8 amd64  [installé]
libc++abi1/stable,now 1:7.0-47 amd64  [installé]

And mod downloaded from : https://drive.google.com/file/d/1tNPUDpk1UJyBm5Wdj6JGgwg6gfPWctRh/view

???

**Comment by lolotux69** [comment]
So I will try with libc++abi 8

**Comment by lolotux69** [comment]
sudo apt list --installed | grep -i libc++

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libc++abi1-8/buster-backports,now 1:8.0.1-3~bpo10+1 amd64  [installé]

Now I will install again Principia and I will tell you !

Tks

**Comment by lolotux69** [comment]
Hmmmmm

`Failed to load assembly /home/lolo/.local/share/Steam/steamapps/common/Kerbal Space Program-1.8.1-principia/GameData/Principia/x64/principia.dll:
System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.`

:/

**Comment by pleroy** [comment]
This is well-known and [documented](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#the-case-of-badimageformatexception).

**Comment by pleroy** [comment]
Also, I would expect that you would need *both* `libc++` and `libc++abi`.  You seem to only have the latter.

**Comment by lolotux69** [comment]
> > I'm under Linux!
> 
> You're under Debian. We build for Ubuntu. There is no telling if a binary built for one system will work for the other.
> 
> > ├── Linux64
> > │   ├── principia.dll
> > │   └── principia.so
> > ├── MacOS64
> > │   ├── principia.dll
> > │   └── principia.so
> 
> These `principia.dll` files under `Linux64` and `MacOS64` are strange. They are probably not the source of the problem, but they didn't come directly from the install.
> 
> Anyway, do you have a recent version of `libc++` and `libc++abi` installed? The error message talks about 6.0.2, but I think you need version 8 these days.

Ok but what version of Ubuntu?

Cause my Debian buster seams to be as Ubuntu : 
`19.10  eoan       buster  / sid 
19.04  disco      buster  / sid
18.10  cosmic     buster  / sid`

**Comment by pleroy** [comment]
We build on 18.04, bionic beaver.  Any version of Ubuntu more recent than that should work fine.  But anyway it's really only the libraries that matter.

**Comment by pleroy** [comment]
No life signs, closing.
