### ISSUE TITLE
Please add build instructions for linux

### ISSUE THREAD

**Issue by vladtcvs** [mockingbirdnest/Principia#2580]
Just run make, or principia_make.sh fails. Please add instructions about building on linux, like there are for building on windows.

**Comment by pleroy** [comment]
FWIW the way that we build releases for macOS and Linux is based on Azure pipelines.  The scripts like `principia_make.sh` have been contributed by @ts826848 in #2523 (thanks!) but we are not using them actively (and are not really documented).

This is not to say that we should not have better documentation, but realistically the documentation is likely to suffer from bit rot as the Azure pipelines evolve.
