### ISSUE TITLE
Change reference body or kicked out moons

### ISSUE THREAD

**Issue by vladtcvs** [mockingbirdnest/Principia#2581]
Principia fixes Jool system and makes it stable. But there are mods, that add some new planets and moons. And they are not fixed and i don't think all authors will worry about it. And if some moon is kicked out of the original planet, i think it should rotate on orbit around the Sun, and be removed from moon list.

**Comment by pleroy** [comment]
I don't see us spending any time improving the user experience with unstable solar systems.  Specifically:
1. It's not only moons being kicked out, it's quite often moons colliding, which we will never be able to handle properly.
1. It's not so easy to figure out if a moon is "kicked out" or just on a very elongated orbit.
1. The moon may end up around the star, or it may be captured by another planet, or it may leave the system.

Overall, way too much complexity.

**Comment by vladtcvs** [comment]
Actually, if planets collides, the correct way is to delete original planets and build new planet with random surface and mass equal to sum of original masses. Or multiple such planets.

But I think it should be separate mod.
