### ISSUE TITLE
Incompatibility with Extraplanetary Launchpads

### ISSUE THREAD

**Issue by LegoF4** [mockingbirdnest/Principia#2582]
See link here for my main issue writeup: [EL Issue](https://github.com/taniwha/Extraplanetary-Launchpads/issues/157)
[Gist](https://gist.github.com/LegoF4/875894be1fe5de6b71f9f320dabda826)

**Comment by pleroy** [comment]
Tracked in the Extraplanetary Launchpads issue.  Closing.
