### ISSUE TITLE
Vessels teleport/switch places upon EVA

### ISSUE THREAD

**Issue by gert7** [mockingbirdnest/Principia#2590]
[Image](https://i.redd.it/q8cjpozv7k051.jpg)

1.9.1 Fuchs. This happened to my Apollo 11-style flight. When I noticed I hadn't moved my crew over to the lander I decided to EVA. The two undocked vessel sides switched places when I hit the EVA. I tried this again in an earlier quicksave and the same thing happened with a much greater distance between the vessels.

**Comment by pleroy** [comment]
Are you using any mods besides Principia?  Can you give us your save and the logs at the time where the glitch happened?

**Comment by gert7** [comment]
[Eva.zip](https://github.com/mockingbirdnest/Principia/files/4673099/Eva.zip)

Quicksave here can reproduce the bug after undocking the middle and switching to EVA. To me it seems to only move vessels along their trajectories, namely the vessel being EVA-d from moves forward some amount. The distance seems to vary, velocities and rotations are completely unaffected.

**Comment by gert7** [comment]
And no, Principia is the only mod I have ever installed in this installation of KSP.

**Comment by pleroy** [comment]
I have reproduced the problem and I have a journal.  This is going to be challenging to debug.

**Comment by pleroy** [comment]
When the Kerbal goes in EVA, it is unready (and therefore unmanageable by Principia) for a short period (probably 1 frame).  If, during that period, it collides with the vessel, this makes the vessel unmanageable and Principia forgets about it.  Shortly thereafter the Kerbal becomes ready, and the vessel is re-created by Principia, *using the position provided by KSP*.  That position may differ significantly from the "real" one and the vessel appears to jump.

The solution is to ignore collisions with an unready Kerbal.  Unreadiness is a transient state anyway, so at the next frame the Kerbal will be ready and will nicely pile-up with the vessel.

There have been reports in the past of the history being lost when doing EVA.  That's probably the same cause (deletion and re-creation of a vessel).  I checked that the history is preserved in this instance.
