### ISSUE TITLE
I'm getting "Principia DLL failed to load" on fuchs for 1.9.1

### ISSUE THREAD

**Issue by larryfast** [mockingbirdnest/Principia#2594]
Superficially this looks similar to #2063.   BTW I'm running this on Windoze with KSP 1.8.1

Where can I find the Fubini or older releases to see if this is a new problem?

**Comment by pleroy** [comment]
The history of the [README](https://github.com/mockingbirdnest/Principia/commits/master/README.md) contains links to the previous versions.

This being said it's undoubtedly a problem with your setup and not with our binaries, because if it didn't work on Windows we would have heard about it (Fuchs has been downloaded 400+ times).

Look at #2548 for steps to collect and send us information about what's going on on your system when you try to load Principia.

**Comment by larryfast** [comment]
Thanks for the instructions.  Agree that this is probably my problem not yours.  If you would prefer I take this elsewhere please suggest the best forum to get some feedback.  In the meantime here's a link to my PML file from starting up KSP with principia.

[https://drive.google.com/file/d/1JZgiwsHPC3w4heersZV69TAIKYaA0pCW](url)

A few more details: 

After all my messing about I decided to do a clean reinstall of KSP before capturing the PML logs.  FYI, the real path to principia.dll in my KSP installation is
M:\WORK\Games\Steam\steamapps\common\Kerbal Space Program\GameData\Principia\x64\principia.dll

I don't claim to know what it all means but I did see recurring references to "...\libGameData\..."  as well as principia.DLL instead of .dll.

**Comment by pleroy** [comment]
Sorry to ask the obvious: have you installed the Microsoft Visual C++ 2015-2019 Redistributable (x64)?  I would expect the error message to ask you to do that.  From the system traces, it loads the Principia DLLs fine, but fails to find `VCRUNTIME140_1.dll`, which is part of the runtime and should live in `C:\Windows\System32`.  This seems to be an **x64**-only file, so make sure you download the right version of the Redistributable.

If you *didn't* get an error message asking to install the Redistributable, then that's a bug and I'd like to hear about it.

**Comment by larryfast** [comment]
Thanks for clarifying. Installed the C++ redist and Principia loads now. You can close this ticket.

Root cause of my problem:  The first mention of C++ Redist that I found was the 2063 bug discussion from 2019.  I didn't find any mention of this requirement in any installation/startup docs, so my initial assumption was -bug-

**Comment by pleroy** [comment]
Good to hear that this fixes your problem.  For what it's worth, this requirement is documented in the [FAQs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-users).
