### ISSUE TITLE
Parachuting Kerbals behave unphysically in Fuchs

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#2607]
Noted while testing #2604; independently reported by @darthpointer.

@darthpointer further reports that the Kerbals are fine in Frobenius, so this likely has something to do with the rigidity assumptions of Fuchs, rather than improper force or torque application.

If all else fails we could make them unmanageable (parachuting leads to unmanageability by grounding in the short term anyway).

**Comment by DarthPointer** [comment]
I found it affecting not only the kerbal, but the vessel too if I get blown away from the ladder. Deploying the chute after being blown away also causes insane accelerations (2k gees recorded).

**Comment by eggrobin** [comment]
It looks like we are seeing spurious collisions between the kerbal and various parts of the aircraft, which means we treat the kerbal+aircraft system as a (nearly rigid) pile up even as they drift apart, which leads to obvious brokenness.

Let’s see whether we can characterize the spurious collisions…

**Comment by eggrobin** [comment]
Ignoring the spurious collisions fixes ejection, but the EVA parachute itself still has issues: the Kerbal orients itself in a parachute-down attitude, which looks silly and is generally not survivable.
