### ISSUE TITLE
Make a Place to Change the Planet’s Information

### ISSUE THREAD

**Issue by Peter-JY** [mockingbirdnest/Principia#2612]
There and many system packages now on KSP Forum, such as [Outer Planets Mod](https://forum.kerbalspaceprogram.com/index.php?/topic/184789-*), [The World Beyond](https://forum.kerbalspaceprogram.com/index.php?/topic/175432-*), and so on. Although there may be some issues or bugs with n-body and extended body gravitation, some people also want to play with a n-body gravitation and test the stable condition. Principia don’t have the place to change the planets or systems in the original Principia. So is there be any chance to add the function or the .txt to let us change the planets and systems?
I know that we can change that in RSS in Initial_State_Jd_2433282_500000000.cfg of Real_Solar_System folder, why not give us a place to change in original KSP?

**Comment by pleroy** [comment]
This exists and [it's documented](https://github.com/mockingbirdnest/Principia/wiki/Principia-configuration-files).

**Comment by Peter-JY** [comment]
I have read the document, but I didn’t find the file to change it.

**Comment by pleroy** [comment]
Well, there is no file to change, you'll have to create a new `.cfg` file for your favorite solar system.  The `.cfg` file that we deliver for RealSolarSystem is a good model for that, but mostly you'll have to do the hard work.

**Comment by pleroy** [comment]
Nothing to do on our side, closing.
