### ISSUE TITLE
Minimum system configuration to use principia mod?

### ISSUE THREAD

**Issue by 13-potatos-why** [mockingbirdnest/Principia#2618]
I have i5 7thgen
8gb ddr4 ram
Gpu with 2gb gddr5 vram
Can i run ksp with principia mod?

**Comment by pleroy** [comment]
Probably, as long as you don't have too many mods.  But you'll have to try.

The [forum](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip151-161-17x-181-principia%E2%80%94version-galileo-released-2020-06-21%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/page/63/&tab=comments#comment-3811175) is a better place to ask this kind of information.  I mean, this is neither a bug report nor a feature request.
