### ISSUE TITLE
KSP 1.10.0

### ISSUE THREAD

**Issue by branc116** [mockingbirdnest/Principia#2636]
New Version of KSP is out!

git log:
```
commit 6dc7d900c5eef378c1a28d8160db602e0d9925a4
Author: Pascal Leroy <pascal.h.leroy@gmail.com>
Date:   Mon Jul 6 22:56:29 2020 +0200

    Merge pull request #2632 from pleroy/InnerProduct
    
    A stray commit.
```

You have something like this:
```
#if KSP_VERSION_1_9_1
    if (!(Versioning.version_major == 1 &&
        (Versioning.version_minor == 8 && Versioning.Revision == 1) ||
        (Versioning.version_minor == 9 && Versioning.Revision == 1))) {
      string expected_version = "1.8.1 and 1.9.1";
```
in ksp_plugin_adapter.cs
I just added ```         (Versioning.version_minor == 10 && Versioning.Revision == 0) || ``` and it looks like it works for 1.10.0 version. Principia GUI is showing, orbits are being calculated, stderr.log is empty, it just seem to be a bit slower than usual (I've build debug version... it's most likely that.)

Is there a test I can run to check if the new version has some breaking changes?

**Comment by pleroy** [comment]
The comets are the scary bit in this release.  What happens when a comet appears?  When a comet breaks down?  When a vessel gets close to a comet?  Depending on how the KSP team chose to implement them, comets could Just Work™ or they could break major invariants of Principia and require weeks of work.

So if you're interested in helping us look for breakages in 1.10.0, please play with comets and report the outcome.

**Comment by pleroy** [comment]
Oh, and I wouldn't build a debug version if I were you, warp is going to be excruciatingly slow.

**Comment by eggrobin** [comment]
> New Version of KSP is out!

Note that, even when this goes smoothly, it often takes us a couple of Principia releases to check that everything is fine with the new KSP version (see the [change logs](https://github.com/mockingbirdnest/Principia/wiki/Change-Log)). Further, as @pleroy pointed out, this one may be messier than usual.

> Depending on how the KSP team chose to implement them, comets could Just Work™

I strongly suspect that, at the very least, we will have to do some special handling to ensure that linear momentum is conserved when comets break down: so far, pile ups only break up into parts that they already contained.

**Comment by pleroy** [comment]
Good news everyone!  The fingerprints have not changed.

**Comment by WC12366** [comment]
I think there won't be any problems with comets, because in KSP 1.10, comets are also vessels like asteriods.

**Comment by wgaylord** [comment]
Has there been any progress?

**Comment by pleroy** [comment]
https://github.com/mockingbirdnest/Principia/wiki/Change-Log#gateaux.
