### ISSUE TITLE
Crash during flight planning

### ISSUE THREAD

**Issue by lpgagnon** [mockingbirdnest/Principia#2640]
Using build test-2626, on Windows.

While fiddling with a LEO rendez-vous flight plan, got a crash to desktop. Happened twice in a row in same situation. In both cases I was in the middle of typing a new number in an input box - flight plan duration in one case, burn time start in the other.

FATAL.log: 
`F0712 00:59:31.438285 14304 discrete_trajectory_body.hpp:644] Check failed: t_min() <= time (-1.28353034162678909e+09 s vs. -nan(ind) s)`

[ERROR.log and INFO.log](https://gist.github.com/lpgagnon/b94eef594ec1aa90ac4765d057c5707e)

**Comment by pleroy** [comment]
Can I get the INFO log?  I need it to decode the stack.

**Comment by lpgagnon** [comment]
sorry about that, I evidently read the instructions diagonally. INFO.log added to same gist

**Comment by lpgagnon** [comment]
Seen again; this time in Galileo, and with no flight plan involved. Just one vessel slowly approaching another in LEO, tuning trajectory with RCS. Additional INFO.log added to same gist.

I'm presuming it's the same issue based on the identical "check failed" message

**Comment by pleroy** [comment]
Decoded stack trace.  This is going to be *really* hard without a journal:

 https://github.com/mockingbirdnest/Principia/blob/6dc7d900c5eef378c1a28d8160db602e0d9925a4/ksp_plugin/interface_renderer.cpp#L72-L79  https://github.com/mockingbirdnest/Principia/blob/6dc7d900c5eef378c1a28d8160db602e0d9925a4/ksp_plugin/plugin.cpp#L972-L977  https://github.com/mockingbirdnest/Principia/blob/6dc7d900c5eef378c1a28d8160db602e0d9925a4/physics/apsides_body.hpp#L34-L106  https://github.com/mockingbirdnest/Principia/blob/6dc7d900c5eef378c1a28d8160db602e0d9925a4/physics/discrete_trajectory_body.hpp#L325-L326  https://github.com/mockingbirdnest/Principia/blob/6dc7d900c5eef378c1a28d8160db602e0d9925a4/physics/discrete_trajectory_body.hpp#L643-L644

**Comment by lpgagnon** [comment]
You're (I'm?) in luck, got a semi-reproducible case. 3 crashes in a row, the last 2 with as close to the same steps as I could recall, the last with a journal. [link](https://drive.google.com/file/d/1CHcAWrfGgJPUiO9Oir_NLZWq5es1VFNy/view?usp=sharing)

Steps: (I may have got some of these in the wrong order)
- turn on journaling in tracking station, jump to vessel in LEO (station in LEO was already set as its target)
- decouple spent stage (was hoping to hit the other crash, no luck)
- create flight plan. add maneuver, add 60m/s prograde
- change plan duration from default to 1d
- change navball to target mode
- focus on target
- select the 001 in plan duration input box, TRY to change it to 2
- crash

**Comment by lpgagnon** [comment]
Got 2 or 3 more crashes _trying_ to do things differently; in every case, the crash trigger was trying to do keyboard input in a numerical field (at least plan duration and prograde dv; might also have happened with time-until-burn). I seem to be having better luck sticking to the sliders.

There's more to it than that, given my 2nd report of getting "the same" crash without a flight plan; but that's now the odd one out.

**Comment by lpgagnon** [comment]
Haven't seen this happen again since upgrading from Galileo to Gallai

**Comment by lpgagnon** [comment]
now seen in gateaux. trigger was again 'type in flight plan duration box'

**Comment by pleroy** [comment]
Confirming the stack for the INFO log posted on July 17 (apologies for the delay).
 https://github.com/mockingbirdnest/Principia/blob/5fa2cecbd475e10034d64b4c4c795bc0003858ec/ksp_plugin/interface_renderer.cpp#L72-L79  https://github.com/mockingbirdnest/Principia/blob/5fa2cecbd475e10034d64b4c4c795bc0003858ec/ksp_plugin/plugin.cpp#L972-L977  https://github.com/mockingbirdnest/Principia/blob/5fa2cecbd475e10034d64b4c4c795bc0003858ec/physics/apsides_body.hpp#L34-L106  https://github.com/mockingbirdnest/Principia/blob/5fa2cecbd475e10034d64b4c4c795bc0003858ec/physics/discrete_trajectory_body.hpp#L325-L326  https://github.com/mockingbirdnest/Principia/blob/5fa2cecbd475e10034d64b4c4c795bc0003858ec/physics/discrete_trajectory_body.hpp#L643-L644

**Comment by pleroy** [comment]
Groan, running into #2778 when trying to replay the journal.

**Comment by pleroy** [comment]
Replaying this journal was a bit of a pain because, due to #2778, the journal was incorrectly constructed so I had to hack around the corruptions.

Anyway, what is happening is that we are trying to compute the closest approaches between one vessel and itself (name `0133 station crew 2`, guid `db9cd970-10f6-4d4e-945a-90da6c172235`).  It seems that this vessel became its own target.

I am going to fix the numerical libraries, but we should also understand how that situation can happen, because I wouldn't be surprised if it caused crashes elsewhere.

**Comment by lpgagnon** [comment]
re: became its own target: now idea how _that_ might happen, but speculating:
 
> select the 001 in plan duration input box, TRY to change it to 2

There's a good chance "select the 001" was done via double-clicking. I'm unclear on principia's click-through behavior, but double-click is one way to set/unset targets...
