### ISSUE TITLE
Why more celestials won't cause performance problem

### ISSUE THREAD

**Issue by WC12366** [mockingbirdnest/Principia#2645]
Principia calculates the orbit of celestials and vessels together, but why some asteroids can cause the performance problem and the celestials not. I installed RealExpansion (a mod which adds lots of celestials in real life) and its principia cfg file, it's very smooth even at 6000000x time warp (no asteroids)

**Comment by pleroy** [comment]
Asteroids are vessels, vessels are integrated every 10 s, celestials every 10 min (for RSS) or 35 min (for stock).  That makes vessels 60 to 200 times more expensive.  This being said I am somewhat surprised that RealExpansion, which has a gazillion celestials, does not degrade performance more.  Did you create a new save after installing it?  (The configuration of the solar system is part of the save.)

Incidentally, github issues are for, well, tracking issues.  For random interesting questions, please use the [forum](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip151-161-17x-181-191-principia%E2%80%94version-galileo-released-2020-06-21%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/page/64/).

**Comment by WC12366** [comment]
ok, thank you very much for answering my questions

**Comment by CindyRIng** [comment]
excuse me,where can i get principia cfg for RealExpansion?

**Comment by WC12366** [comment]
> excuse me,where can i get principia cfg for RealExpansion?
Here you are.
[RealExpansion.zip](https://github.com/mockingbirdnest/Principia/files/4971800/RealExpansion.zip)

**Comment by CindyRIng** [comment]
ok thank you very much
