### ISSUE TITLE
How do I download old binaries? 

### ISSUE THREAD

**Issue by joey-lg** [mockingbirdnest/Principia#2657]

**Comment by pleroy** [comment]
Please stop using github issues to ask random questions.  Issues are reserved for bugs or feature requests.  There is a KSP [forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip181-191-principia%E2%80%94version-gallai-released-2020-07-20%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/page/64/) for asking questions, where this question has already been asked and answered.

Using older binaries means "no support", by the way.
