### ISSUE TITLE
Weird Issue with Craft Collision Detection

### ISSUE THREAD

**Issue by MarsMan1000** [mockingbirdnest/Principia#2659]
I have a strange issue, running version 1.9.1 under both Fubini and Gallai.

For some reason, craft collision detection seems "offset" from the actual position of the ship.  When returning to Kerbin, this can clearly be seen as an "impact" that occurs with the water about 10m ahead of the craft appearing to make physical contact with the ocean.  

A similar event happened when landing a probe on the Mun; even though the base of the landing struts were well below the descent engine and were deployed, the engine appeared to "crash" into the surface and exploded ahead of actual contact.  (Obviously this would be a disasterous outcome for a manned mission).

Another oddity I've noticed, which possibly is related, occurs when performing orbital rescue missions.  After a successful orbital intercept, I line up the rescue vessel 10m away from the target, align velocity at 0.0, then switch to the target.  When the stranded Kerbal goes EVA, however, the rescue vessel suddenly "repositions" itself 30m or more away, which is rather jarring.

Not sure if this is a Prinicipia issue, though I suspect it may be since I've not seen any reports of similar issues on the KSP boards (maybe I missed them).

If someone could please advise, I'd appreciate it. 

Thanks!

**Comment by pleroy** [comment]
On the surface this looks a bit like #2590, but that issue was fixed in Galileo.

We would need a save and [logs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs) to investigate.
