### ISSUE TITLE
Crash during ascent after dropping boosters

### ISSUE THREAD

**Issue by lpgagnon** [mockingbirdnest/Principia#2716]
Seen twice; not reproducible at-will, so no journal. Both in Gallai.

From FATAL.log: 
`F0909 21:55:24.457835  9920 not_null_body.hpp:33] Check failed: other != nullptr`

From INFO.log, crash happens both times after a bunch of "removing vessel"/"destroying part" messages

In both cases the scenario was the same: launching a rocket consisting of 2 stages plus a pair of solid boosters, the boosters were dropped a few seconds ago. Some parts have been blowing up, presumably from aerodynamic stress. It's possible enough time elapsed for the dropped parts to fall out of physics range.

Each solid booster (ROE-Algol1) has a pair of separation motors attached (ROSmallSpinMotor).
One difference in the second instance: one of the Algols blew up (testlite) shortly before running out of fuel. Its spinmotors would have become debris a few seconds before staging the remaining Algol.

[INFO.log for first instance](https://gist.github.com/lpgagnon/90e568db36b7b8c0f0f962c63f296532#file-info-20200908-092828-11732-log)
[INFO.log for second instance](https://gist.github.com/lpgagnon/90e568db36b7b8c0f0f962c63f296532#file-info-20200909-211353-11444-log)

**Comment by lpgagnon** [comment]
Journal! new scenario, but same failed check and similar conditions. Crash occurs during crewed reentry, while the decoupled service module is slowly dropping back and bits of it are exploding. Bits are somewhere around 4km distant.

Happened 3 times in a row, got a journal for 3rd instance.
https://drive.google.com/file/d/10ITznV2oS4RnIjG4aic6qJcmMMCQgFnP/view?usp=sharing

**Comment by lpgagnon** [comment]
supporting evidence that it has something to do with the decoupled part: reloaded, deleted it via tracking station, went back to capsule, no crash

**Comment by pleroy** [comment]
Decode stack trace:
 https://github.com/mockingbirdnest/Principia/blob/caa676d5d9d951abe92a5ce06f3c5a5df31d6965/base/thread_pool_body.hpp#L57-L80  https://github.com/mockingbirdnest/Principia/blob/caa676d5d9d951abe92a5ce06f3c5a5df31d6965/base/thread_pool_body.hpp#L14-L15  https://github.com/mockingbirdnest/Principia/blob/caa676d5d9d951abe92a5ce06f3c5a5df31d6965/ksp_plugin/plugin.cpp#L785-L785  https://github.com/mockingbirdnest/Principia/blob/caa676d5d9d951abe92a5ce06f3c5a5df31d6965/ksp_plugin/pile_up.cpp#L125-L129  https://github.com/mockingbirdnest/Principia/blob/caa676d5d9d951abe92a5ce06f3c5a5df31d6965/ksp_plugin/pile_up.cpp#L395-L477  https://github.com/mockingbirdnest/Principia/blob/caa676d5d9d951abe92a5ce06f3c5a5df31d6965/base/not_null_body.hpp#L33-L33

**Comment by pleroy** [comment]
The bug appears to be in `Diagonalize`.  (Surely the last bug in this code.)
