### ISSUE TITLE
Step-by-Step note edit

### ISSUE THREAD

**Issue by Kerbinator-CN** [mockingbirdnest/Principia#2718]
Simply an interface edit but extremely user-friendly
Refers to MechJeb's note editor's "+"&"-"button and input of delta-amount in its node editor.
for example:  
Prograde ----|---- [20.01235m/s] [+] [-] [0.00100m/s]

**Comment by pleroy** [comment]
There are improvements to be made in the UI, but I don't think this is one of them.  Closing.
