### ISSUE TITLE
KSP complete crash when ship explodes reentering the atmosphere

### ISSUE THREAD

**Issue by szundi** [mockingbirdnest/Principia#2749]
Ship started to blow into pieces. Whole KSP crashed.

`not_null_body.hpp:33] Check failed: other != nullptr `

Logs attached.

[stderr.log](https://github.com/mockingbirdnest/Principia/files/5333116/stderr.log)
[KSP.log](https://github.com/mockingbirdnest/Principia/files/5333117/KSP.log)

**Comment by eggrobin** [comment]
> Logs attached.

Not the right ones though, see [the FAQ (we need the INFO log)](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs).

Assuming the stack traces look alike, this may be a duplicate of #2716, for which we have a journal (we have yet to investigate it though).

**Comment by szundi** [comment]
sorry, those logs are gone now,  I close this then.
