### ISSUE TITLE
[Question] Recommanded tool to simulate n-body to test modified system

### ISSUE THREAD

**Issue by Tutul-** [mockingbirdnest/Principia#2788]
I wish to work on some system mods that may benefit to work on Principia.
Is there a recommanded tool that can help me simulate these system and see any instability (moon ejected, collisions, etc...) faster than running the simulation in ksp max warp on the map ?

I'm ok with python script that need some tweaking to read json definitions

**Comment by pleroy** [comment]
This is a question that gets asked from time to time, and the short answer is that it's just hard and requires trial and error.  See [this post](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip181-191-1101-principia%E2%80%94version-%D0%B3%D0%B5%D0%BB%D1%8C%D1%84%D0%B0%D0%BD%D0%B4-released-2020-11-15%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/&do=findComment&comment=3573125) and [this post](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip181-191-1101-principia%E2%80%94version-%D0%B3%D0%B5%D0%BB%D1%8C%D1%84%D0%B0%D0%BD%D0%B4-released-2020-11-15%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/&do=findComment&comment=3573776) for possible ways to get started.  The bottom line is that you'll be able to experiment much more efficiently if you don't use KSP but simulate your solar system using external tools, and the Principia code base can help you to some extent.  But at any rate that will require quite a bit of programming.

**Comment by Tutul-** [comment]
Well it may be interesting to try to work on something with the principia physic library then.
I'll check the feasibility of something like that with my current level.

I was impress by the complete analysis of the Jool system. Was is done using KSP or an internal tool using principia ? 
My main aim is to detect possible collision and ejection to find the more urgent patch require for those system.
At first, a complete stability analysis like yours is probably out of my scope as it require better understanding of orbital mechanics to understand what are the implications.

**Comment by pleroy** [comment]
The [analysis of the KSP system](https://github.com/mockingbirdnest/Principia/wiki/On-the-dynamical-stability-of-Principia's-modified-Jool-system) was done using a mix of C++ (our physics libraries) and _Mathematica_.  No KSP involvement there.

**Comment by Tutul-** [comment]
I knew about  the "no KSP involved in this".
So you just provided the physics library with the KSP solar system configuration and Mathematica provided all the calculations tools ?

**Comment by eggrobin** [comment]
The code that was used to generate the data is https://github.com/mockingbirdnest/Principia/blob/master/mathematica/retrobop_dynamical_stability.cpp.
*Mathematica* was then primarily used for data visualization.

The C++ is very much *ad hoc*: if we wanted to answer a new question, we would write something to compute new data, and then stare at it using *Mathematica* to try to figure out what is going on.

**Comment by Tutul-** [comment]
Thanks, I'll dig into that.
If I manage to develop a "good enough" program that can simulate system to detect crash or escape with higher speed than KSP, and if it can be used to patch the system to work on KSP with Principia, I'll contact you again :-)
