### ISSUE TITLE
Principia significantly affects the handling of a significant portion of the aircraft

### ISSUE THREAD

**Issue by RobotV1** [mockingbirdnest/Principia#2808]
After install Principia, a large percentage of aircraft (**even rocket-powerde aircraft**) will be affected. They tend to become more difficult to control than the originals, and will often exhibit behavior that is different from the results of the FAR pneumatic analysis. Here's an example. Test flight video and craft files in example.zip
![Pneumatic Analysis0](https://user-images.githubusercontent.com/20885536/101062538-b7e87f00-35cc-11eb-9f47-3ae9d5fbe45e.png)
![TestFlight0](https://user-images.githubusercontent.com/20885536/101062244-5d4f2300-35cc-11eb-8050-e7b2acbe2f88.png)
[example.zip](https://github.com/mockingbirdnest/Principia/files/5637735/example.zip)

**Comment by eggrobin** [comment]
I am able to reproduce this (though it took me about an hour and a half to get an install that would load the crafts; as discussed on QQ something closer to stock would have been nicer).

This feels related to #2519, KSP-RO/ProceduralFairings#13, or similar issues brought to light by our handling of rotations.
There are several possibilities:
- the behaviour with Principia may be correct (there is no egregious violation of the conservation of energy even when flying this with Principia, and the aerodynamic* analysis is not all there is to stability, the rigid body dynamics matter too; we know that those are wrong in stock);
- there may be a bug in one of the part mods which causes a force or torque to be applied at the wrong point or to be ignored entirely in Principia;
- this might be hitting the rare unexplained spin-up behaviour from https://github.com/mockingbirdnest/Principia/issues/2519#issuecomment-636318756, but I don’t think that is it; the aircraft is not spinning up, and it remains about as rigid as planes are.

—
\* @RobotV1, note that here 气动分析 translates to *aerodynamic* analysis; pneumatics is about pumps, valves, cylinders & pistons, etc.
