### ISSUE TITLE
Request for Lighter version of principia.

### ISSUE THREAD

**Issue by 13-potatos-why** [mockingbirdnest/Principia#2810]
Please make a lighter version of principia for low end pc.

**Comment by Tutul-** [comment]
What do you mean by a "lighter version" ? It's a full n-body physics engine

**Comment by pleroy** [comment]
This is the most useless problem report ever, as it contains no actionable information.

First, note that it's unlikely that significant improvements are possible in the _n_-body integration: our integrators are state-of-the-art, the most expensive computations are hand-written using intrinsics (asssembly, if you want) and tuned using the Intel simulation toolset to achieve best use of the processor's functional units.  We are limiting ourselves to the SSE3 instruction set: we could certainly get better performance by using a more modern instruction set like AVX-512, but that would run counter to the requirement of supporting relatively modest PC hardware.

This is not to say that performance cannot be improved in other parts of the mod: #2776 is an example of a contribution that reduces heap use, and our work on #2400 is trying to make scene changes less annoying.  Note how the user who contributed #2776 did their homework, analysing where time was spent and how they could improve the situation.  They didn't just whine about Principia being too slow.

So if you want us to pay attention to performance issues, you need to provide detailed information about your configuration and your problem: on my PC which has characteristics so-and-so, doing X takes 1 minute (or causes a crash, etc.).  And give us saves, [journals](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#journaling), [logs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs), etc. to help us understand what's happening.

A few tips to increase the speed of the mod:
1. Use the stock game, not RSS: Principia with RSS has a very elaborate model of the Solar System that is going to burn CPU.
1. Limit the number of mods that you have installed.  Even mods that don't use a lot of CPU are likely to consume memory and cause your PC to swap.
1. Delete the [potatoroids](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#timewarping) and the comets.  They are represented as vessels by KSP and are exceedingly costly to handle.
1. Remove unused vessels, debris and the like.  They remain part of the _n_-body computation forever, long after their useful life span.
