### ISSUE TITLE
Everything randomly dissapears when flying

### ISSUE THREAD

**Issue by CaptainKeeble** [mockingbirdnest/Principia#2831]
I would just be flying trying to maneuver a craft and when I would switch from map view to normal view all of a sudden everything vanished. I wouldn't be able to see anything, this includes my craft, planets, the sun, etc. I would try to go back to the space station and everything would still be black, some toolbar buttons are empty. 

This never happened when I didnt have Principia installed. Now all of a sudden it happens very often. Sorry if this is not the right mod to cause this, I just assumed it would be it as I have never encountered this issue ever before installing this.

**Comment by CaptainKeeble** [comment]
Found out the issue isnt Principia,

**Comment by blackhack** [comment]
Sorry to ask, but I'm having the same issue, is my first time with principia and I never have this happening before, what did you figure was causing the issue?
