### ISSUE TITLE
Crash while nearby vessel explodes

### ISSUE THREAD

**Issue by al2me6** [mockingbirdnest/Principia#2853]
Encountered a crash while reentering and the nearby service module was exploding.

Error message:

```
    @   00007FFCA8316360  	google::LogMessageFatal::~LogMessageFatal [0x00007FFCA831635F+47]
    @   00007FFC62CEBCA7  	principia__VesselVelocity [0x00007FFC62CEBCA6+194918]
    @   00007FFC62CEADC3  	principia__VesselVelocity [0x00007FFC62CEADC2+191106]
    @   00007FFC62DFF33D  	principia__VesselVelocity [0x00007FFC62DFF33C+1323004]
    @   00007FFC62D09BA4  	principia__VesselVelocity [0x00007FFC62D09BA3+317539]
    @   00007FFC62DAEE9D  	principia__VesselVelocity [0x00007FFC62DAEE9C+994140]
    @   00007FFC62D2582F  	principia__VesselVelocity [0x00007FFC62D2582E+431342]
    @   00007FFCCA8714C2  	configthreadlocale [0x00007FFCCA8714C1+145]
    @   00007FFCCBA97034  	BaseThreadInitThunk [0x00007FFCCBA97033+19]
    @   00007FFCCD15D0D1  	RtlUserThreadStart [0x00007FFCCD15D0D0+32]
F0108 20:19:12.763484 14000 not_null_body.hpp:33] Check failed: other != nullptr 
```

[INFO.log](https://gist.github.com/al2me6/3495cd7d8cec13495c448724a07b62fa)

**Comment by al2me6** [comment]
Managed to reproduce via reloading; [journal](https://drive.google.com/file/d/1GF2p2Oaz07KbbI4XaBxWR39gK3YkduZE/view?usp=sharing).

**Comment by pleroy** [comment]
Decoded stack trace:

 https://github.com/mockingbirdnest/Principia/blob/cf4b30f0360e6e9953292dd33d9b29fc362b5b77/base/thread_pool_body.hpp#L57-L80  https://github.com/mockingbirdnest/Principia/blob/cf4b30f0360e6e9953292dd33d9b29fc362b5b77/base/thread_pool_body.hpp#L14-L15  https://github.com/mockingbirdnest/Principia/blob/cf4b30f0360e6e9953292dd33d9b29fc362b5b77/ksp_plugin/plugin.cpp#L785-L785  https://github.com/mockingbirdnest/Principia/blob/cf4b30f0360e6e9953292dd33d9b29fc362b5b77/ksp_plugin/pile_up.cpp#L125-L129  https://github.com/mockingbirdnest/Principia/blob/cf4b30f0360e6e9953292dd33d9b29fc362b5b77/ksp_plugin/pile_up.cpp#L395-L477  https://github.com/mockingbirdnest/Principia/blob/cf4b30f0360e6e9953292dd33d9b29fc362b5b77/base/not_null_body.hpp#L33-L33

**Comment by pleroy** [comment]
This seems very similar to #2716, and it apparently has the same cause, viz. `Diagonalize` producing NaNs which confuse the comparison at line 468 of `pile_up.cpp` above.

@eggrobin tells me that it might be time to open the [Golub & Van Loan](https://www.goodreads.com/book/show/18973892-matrix-computations?from_search=true&from_srp=true&qid=gc46o7CBet&rank=2) instead of trying to patch up the Wikipedia "algorithm".

**Comment by al2me6** [comment]
...and fix the Wikipedia page while you're at it?! 😆

**Comment by pleroy** [comment]
Thanks a lot for recording a journal, by the way, it was very useful to understand what was going on.
