### ISSUE TITLE
Hard CTD when deleting a flight plan after it has finished

### ISSUE THREAD

**Issue by daantimmer** [mockingbirdnest/Principia#2873]
1. I had a flight plan.
2. It was finished.
3. Clicked rebase (I wanted to add a new maneouver).
4. Reconcidered (bed time)
5. Clicked delete flightplan
6. Hard CTD

FATAL + INFO -> https://gist.github.com/daantimmer/89e5b800bc4def462c68b0cc8266ced4

**Comment by eggrobin** [comment]
This looks like a duplicate of #2862, which will be fixed in Gödel.

See https://github.com/mockingbirdnest/Principia/issues/2862#issuecomment-766145243 for the reproduction steps (and avoid closing a flight plan with the final trajectory analyser open in the meantime to avoid this crash).

**Comment by daantimmer** [comment]
👍 Will do.
