### ISSUE TITLE
How to download previous versions, such as Galileo

### ISSUE THREAD

**Issue by 1275112280** [mockingbirdnest/Principia#2875]
Announcement: the new moon of lunation number 253 has come; please download the latest Principia release, Galileo.

**Comment by pleroy** [comment]
You can find the download links for older versions by looking at the [history of the README.md file](https://github.com/mockingbirdnest/Principia/commits/master/README.md).

**Comment by pleroy** [comment]
I should have mentioned that, unless you have a compelling reason to stick to some ancient KSP version (Galileo was the last version to support 1.7.3) you should generally upgrade to the latest Principia version.  No support for anything other than the latest version.

**Comment by 1275112280** [comment]
OK，thanks



---Original---
