### ISSUE TITLE
Crash to desktop when switching vessels in Tracking Station

### ISSUE THREAD

**Issue by VincentThacker** [mockingbirdnest/Principia#2896]
I am using latest version Gödel on KSP 1.10.1. I was piloting an unmanned satellite "Satellite 1" towards the Earth-Moon L5 point. I set the flight plan duration to around 300 days in order to make sure the trajectory was stable. I was dragging the maneuver sliders around (this caused my FPS to drop drastically which is normal) to fine-tune my trajectory. Once I got a nice trajectory around L5 (I haven't executed the maneuver yet; it was planned for 10+ days later), I decided to check on another vessel. So I went to the Tracking Station to switch to another satellite "Moon Satellite 1" and it crashed to desktop.

There is no fatal log; only info.
[INFO.log](https://github.com/mockingbirdnest/Principia/files/6002748/INFO.20210217-202341.4280.log)
[KSP.log](https://github.com/mockingbirdnest/Principia/files/6010033/KSP.log)

**Comment by pleroy** [comment]
I can't make sense of the logs.  The last entry in the `INFO.log` file is:
```
I0217 21:13:22.671198  9844 part.cpp:67] Destroying part sasModule (0D3C8A0A)
I0217 21:13
```
But the `KSP.log` file happily continues for 20 seconds and doesn't seem to crash to desktop:
```
[LOG 21:13:22.656] [OD] <--- OnDemandStorage.DisableBodyCBMaps destroying Mercury
[LOG 21:13:22.656] [UIMasterController]: HideUI
[LOG 21:13:22.662] ScaleModList: listSize 82 maxListSize 1456
[LOG 21:13:30.521] [HighLogic]: =========================== Scene Change : From TRACKSTATION to FLIGHT (Async) =====================
[LOG 21:13:30.617] [OD] <--- OnDemandStorage.DisableBodyCBMaps destroying Dysnomia
[LOG 21:13:30.617] [OD] <--- OnDemandStorage.DisableBodyCBMaps destroying Eris
[LOG 21:13:30.617] [OD] <--- OnDemandStorage.DisableBodyCBMaps destroying Hydra
...
[LOG 21:13:40.561] Saving Achievements Tree...
[LOG 21:13:40.561] Saving Achievements Tree...
[LOG 21:13:40.643] [MessageSystem] Save Messages
[LOG 21:13:41.403] Game State Saved as persistent
```

**Comment by VincentThacker** [comment]
That is very strange. I am very sure that the above was what happened. At first I thought it was insufficient RAM but I have 32GB and the most I've ever seen KSP use is 20GB.
