### ISSUE TITLE
Crash doing flightplanning w Principia

### ISSUE THREAD

**Issue by joemos11** [mockingbirdnest/Principia#2903]
While working on a second maneuver for a flightplan to the L4 point, had a crash. KSP hung for about 4 seconds and then disappeared. I have had instability before with Principia. but wanted to upgrade to latest version first. My 1.8.1 install is about 2 months old, but Principia is the latest. Previous crashes have been doing map to flight screen transitions. I am in sandbox, and only have 3 probes in flight.
[INFO.20210306-173840.14896.log](https://github.com/mockingbirdnest/Principia/files/6096289/INFO.20210306-173840.14896.log)
[ERROR.20210306-173840.14896.log](https://github.com/mockingbirdnest/Principia/files/6096290/ERROR.20210306-173840.14896.log)
[WARNING.20210306-173840.14896.log](https://github.com/mockingbirdnest/Principia/files/6096291/WARNING.20210306-173840.14896.log)

**Comment by joemos11** [comment]
Second crash, this time I was switching from map mode to tracking station. Th pricipia windows came up, but there was no text in them, but I could see the outline of the buttons in the principia windows. No toolbar, and the earth or the other parts of the tracking station window did not come up. Game hung until terminated with the close button on the microsoft window. Error logs inclosed. 
[ERROR.20210307-154329.13864.log](https://github.com/mockingbirdnest/Principia/files/6098164/ERROR.20210307-154329.13864.log)
[WARNING.20210307-154329.13864.log](https://github.com/mockingbirdnest/Principia/files/6098165/WARNING.20210307-154329.13864.log)
[INFO.20210307-154329.13864.log](https://github.com/mockingbirdnest/Principia/files/6098166/INFO.20210307-154329.13864.log)

**Comment by pleroy** [comment]
So the logs don't indicate a crash of Principia *per se* (there is no stack at the end of the log files).  This is not to say that Principia is not the culprit, but it means that the log files alone don't tell us much.  If that happens to you again, it would be good if you could give us (in addition to the log files) the `KSP.log` file and the [crash folder](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#have-a-crash-folder-ie-a-folder-whose-name-is-the-date-in-your-ksp-install-directory).

An empty Principia window is typically a symptom of an exception in the display path.

**Comment by pleroy** [comment]
No life signs, closing.
