### ISSUE TITLE
[Info] FARc 0_16_0_1_Mader can lead to a Principia Fatal error in KSP 1.11.1

### ISSUE THREAD

**Issue by Growflavor** [mockingbirdnest/Principia#2922]
I am providing this mod interaction report since one can easily leave an older version of a mod in GameData & also in case the normal work on FARc for a KSP 1.11.1 version does not resolve this.  FARc has not yet been released for KSP1.11.1 but [several FARc users report using the 1.10.1 version with KSP 1.11.x](https://forum.kerbalspaceprogram.com/index.php?/topic/179445-18-110-ferram-aerospace-research-continued-v01601-mader-241120/&do=findComment&comment=3913019).  I have only been able to produce this FATAL with FARc added to GameData in KSP 1.11.1...when I remove it from GamaData launches proceed fine, as soon as I add FARc back & reload KSP I get the FATAL with the 1st stage debris. Also, Principia & this 0_16_0_1_Mader version of FARc appear to work fine together in KSP 1.10.1 as expected.

journal attached: [JOURNAL.zip](https://github.com/mockingbirdnest/Principia/files/6141928/JOURNAL.zip)
also available with principia logs at: https://drive.google.com/drive/folders/1qx9jgqkaWLg7lPo5g627eSItruQTzOVr?usp=sharing

Reproduction steps:

- KSP 1.11.1
- FARc 0_16_0_1_Mader (= for KSP 1.10.x)
- Principia
- Build in VAB a rocket with small solid rocket motor boosters as 1st stage attached via radial decoupler, example .craft:
[x2bCRAFT.zip](https://github.com/mockingbirdnest/Principia/files/6141950/x2bCRAFT.zip)
- Launch at KSC launch pad
- Turn slightly towards the water 
- Stage the small SRBs when their burn is complete
- Fatal occurs when SRB debris visually appears to impact the water facing side of KSC ground e.g. the field between the VAB & Launchpad.
- [FARcFATAL.gif](https://user-images.githubusercontent.com/1580559/111169388-31681400-85a3-11eb-88cd-1a7828b97c57.gif)

`part.cpp:67] Destroying part radialDecoupler (3319418D)
...
vessel.cpp:155] Check failed: !parts_.empty() `

pleroy was kind to respond on the forum since issues are not tracked there:

> "This does indeed seem somewhat similar to #1549, in the sense that I suspect that we end up with a vessel having no parts, although that probably happens in a completely different manner.
> 
> From looking at one particular log file, we have a vessel (Vessel x2b Debris) that has 3 parts (a noseCone, a solidBooster and a radialDecoupler).  The first two parts are removed from the vessel (so far so good) and then the third part is destroyed.  Since we see no message telling us that the vessel itself is destroyed, we are probably left with an empty vessel.
> 
> My gut feeling is that this could be KSP violating one of its own "invariants" or some other mod not properly managing parts and vessels.
> 
> If you know how to reproduce this, a journal would help greatly. "

**Comment by Growflavor** [comment]
More tracking notes...hmmm...just encountered this "Check failed: !parts_.empty() " with different radial decoupler...strangely this time in KSP 1.10.1 while in the upper Kerbin atmosphere shortly after separation:
[Principia_KSP1101_Logs_FATAL_20210510_195502_16856.zip](https://github.com/mockingbirdnest/Principia/files/6454344/Principia_KSP1101_Logs_FATAL_20210510_195502_16856.zip)

also, seems less frequent with the new FAR in KSP 1.11.2 with the simple X2B test craft but I am still able to get a crash: 
[Principia_KSP1112_Logs_FATAL_20210510_175954_8968.zip](https://github.com/mockingbirdnest/Principia/files/6454340/Principia_KSP1112_Logs_FATAL_20210510_175954_8968.zip)

I will keep observing & if I see something consistent will get another journal.

**Comment by pleroy** [comment]
For the record, I was able to replay the journal given in the first comment and to reproduce the crash.  No further analysis yet.
