### ISSUE TITLE
CTD during KCTSim after reverting to launch 'after load window'

### ISSUE THREAD

**Issue by daantimmer** [mockingbirdnest/Principia#2928]
KSP 1.10.1
Principia  Goldbach
RP-1 V1.8 (CKAN)

Situation: while flying pressing the revert to launch button. After the screen has finished loading and you are about to see the flight scene the CTD occurs.

principia logs:
https://gist.github.com/daantimmer/d81fc2a6a2d4aa39ab292a73bbb28340

**Comment by siimav** [comment]
Fixed in https://github.com/KSP-RO/RP-0/commit/b127626411982834535786a0c6e31e49421754ae
