### ISSUE TITLE
CTD during a LTI flight planning

### ISSUE THREAD

**Issue by shanglizhi** [mockingbirdnest/Principia#2956]
CTD without any dialog box. Happened during flight planning.

OS: Windows 10  (10.0.0) 64bit
CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12)
RAM: 32513
GPU: NVIDIA GeForce GTX 1650 Ti (3964MB)
SM: 50 (Direct3D 11.0 [level 11.1])
RT Formats: ARGB32, Depth, ARGBHalf, Shadowmap, RGB565, ARGB4444, ARGB1555, Default, ARGB2101010, DefaultHDR, ARGB64, ARGBFloat, RGFloat, RGHalf, RFloat, RHalf, R8, ARGBInt, RGInt, RInt, BGRA32, RGB111110Float, RG32, RGBAUShort, RG16, BGRA10101010_XR, BGR101010_XR, R16

The fatal and info files in the log folder are in the gist. 

https://gist.github.com/shanglizhi/1ee05a4d3a41a497a00bd93b130e2af3

**Comment by pleroy** [comment]
Are you using Kerbal Construction Time?  It has been known to cause time to go backwards, which is a no-no for Principia (see [this thread](https://discord.com/channels/319857228905447436/480397772248580098/824789468975857675) on Discord).

Generally, any mod that changes the way time moves could cause that kind of crash.

**Comment by shanglizhi** [comment]
> Are you using Kerbal Construction Time? It has been known to cause time to go backwards, which is a no-no for Principia (see [this thread](https://discord.com/channels/319857228905447436/480397772248580098/824789468975857675) on Discord).
> 
> Generally, any mod that changes the way time moves could cause that kind of crash.

Yes, I'm using KCT since it is mandatory for rp1 which is what I'm doing. Any suggestion on how to avoid this problem in rp1? Should I use KRASH instead of KCT sim for the test launch?

**Comment by pleroy** [comment]
KRASH is even more incompatible than KCT from what I gather, so I would recommend sticking with KCT. The author of KCT is aware of the issue and will come up with a fix at some point. In the meantime, he had [this recommendation](https://discord.com/channels/319857228905447436/480397772248580098/824806670781382728) to avoid running into the bug you found.

**Comment by eggrobin** [comment]
I believe the issue has been fixed by @siimav in Kerbal Construction Time recently, see https://github.com/KSP-RO/RP-0/commit/88fccb220fcabb21c6086d2b71457b207f6c0d01.

As @siimav wrote on Discord:
> My suggestion is to try the master branch of RP-1.
