### ISSUE TITLE
Crash during staging

### ISSUE THREAD

**Issue by Marsu69** [mockingbirdnest/Principia#2967]
Hello,

From times to times I have a crash during staging (with or without procedural fairing).

I really don't know how to reproduce as it seems totally random.
Here are the files from the last crash this day.

Thanks for your work on this mod. It's awesome.
[ERROR.20210502-092401.16368.log](https://github.com/mockingbirdnest/Principia/files/6410995/ERROR.20210502-092401.16368.log)
[FATAL.20210502-102306.16368.log](https://github.com/mockingbirdnest/Principia/files/6410996/FATAL.20210502-102306.16368.log)
[INFO.20210502-092401.16368.log](https://github.com/mockingbirdnest/Principia/files/6410997/INFO.20210502-092401.16368.log)
[WARNING.20210502-092401.16368.log](https://github.com/mockingbirdnest/Principia/files/6410999/WARNING.20210502-092401.16368.log)

**Comment by pleroy** [comment]
Note to self: this looks awfully similar to #2931 (which I haven't found time to investigate yet).
