### ISSUE TITLE
Incorrect zh-cn translation of 'apoapsis' and 'periapsis'

### ISSUE THREAD

**Issue by al2me6** [mockingbirdnest/Principia#3074]
The current Chinese localization

https://github.com/mockingbirdnest/Principia/blob/ecebea3d23a0a5eff09bbcc0f84cb0dc266e2836/ksp_plugin_adapter/localization/zh-cn.cfg#L225-L226

in fact translates the terms as 'apogee'/'perigee'. AFAIK the correct translations should be '近拱点' and '远拱点', respectively.

**Comment by eggrobin** [comment]
> AFAIK the correct translations should be '进拱点' 

Surely that should be 近拱点?

This should also be reflected in the following two strings from the orbit analyser. https://github.com/mockingbirdnest/Principia/blob/ecebea3d23a0a5eff09bbcc0f84cb0dc266e2836/ksp_plugin_adapter/localization/zh-cn.cfg#L104-L105

近拱点幅角 is attested.

**Comment by al2me6** [comment]
Ah, apologies. Typo'd.

**Comment by eggrobin** [comment]
平均近拱点高度 (mean periapsis altitude) does not appear in Google search results, whereas the current 平均近地点高度 (mean perigee altitude) does, but 近拱点高度 (periapsis altitude) is attested, so this seems like a reasonable extrapolation.

Further, a full-text CNKI search for 平均近拱点高度 with the Precise setting finds one result, namely [火星重力场模型发展回顾及对萤火一号的展望—On the Mars Gravity Field Models and Prospects of "Yinhuo-1" Mission, CNKI ID TWJZ201202007](https://global.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFD2012&filename=TWJZ201202007&v=MTQxNDlPUnVGeURoVTd2QU1UckJkTEc0SDlQTXJZOUZZNFI4ZVgxTHV4WVM3RGgxVDNxVHJXTTFGckNVUjd1Zlk=).
I was able to find [a PDF](http://center.shao.ac.cn/twxjz/abstract/2012/20120206.pdf), unfortunately it uses some stupid encoding so a text search does not work.
The phrase 平均近拱点高度 appears in the table at the top of page 223, which reads
| 主要阶段 | 时间范围 | 轨道特征 |
|---|---|---|
| 轨道刹车阶段 (AB1) | 19971107-199803028 | 在近拱点高度约为 120 km 处的轨道周期从 35.4 h 降到 11.5 h，平均近拱点高度约 120 km，远拱点高度从 45 000 km 降到 18000 km。 |

So it seems that 平均近拱点高度 is sensible as a technical term/phrase, albeit rare.
