### ISSUE TITLE
"Error extending trajectory for Laythe" for certain launch times

### ISSUE THREAD

**Issue by leftfusion** [mockingbirdnest/Principia#3205]
Hi all, I'm running Principia, FARc and a few other mods on KSP 1.12.2.3167 on a MacBook Pro M1.

I set up a rocket for launch at KSC. When I switch to map view, things seem normal. During launch, when I switch to map view again, a Principia dialog appears with:

> Error extending trajectory for Laythe. Error trying to fit a smooth polynomial to the trajectory. The approximation error jumped from +2.30409398201086163e-03 m to +8.35707936646116650e+03 m at time 2000-01-19T18:40:00,0000000000000000 (TT). The last position is {+2.82934834163834190e+10 m, +5.89477737293942795e+10 m, +3.18125881596906483e+08 m} and the last velocity is {-3.61413290050426031e+03 m s^-1, -1.47439688224631891e+03 m s^-1, +9.66053147377180750e+01 m s^-1}. An apocalypse occurred and two celestials probably collided because your solar system is unstable.

Reverting to launch pad and repeating the launch + switch to map view consistently reproduces this error for me.

Here are [the logs and the save](https://drive.google.com/drive/folders/1BIKxcwL1kmz7tINP6I-1FyQSsxn9EzHg?usp=sharing). The sequence of actions I described starts at around 10:50:00.

**Comment by leftfusion** [comment]
Curiously, if I time-warp a few hours into the future before launching, going to map view no longer causes this error.

**Comment by pleroy** [comment]
You are using a mod that makes your solar system different from the stock one, and unstable.  You may or may not be able to patch it using a Kopernicus configuration, [details here](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#kopernicus-users).

**Comment by leftfusion** [comment]
Ah, I just noticed installing Parallax (terrain shader mod) from CKAN auto-installed Kopernicus, so didn't realize the [retrobop config](https://gist.githubusercontent.com/eggrobin/31f6d0c246ecbe50423488f867fe7051/raw/55b814cd14b3c9fdd63119cee96dacb847e2e9ea/retrobop.cfg) needed to be applied.

If I apply it now, will these changes be reflected in my save, or only in new games started from now on? If not, is there a way I can retroactively apply these changes into an existing save?

**Comment by pleroy** [comment]
The configuration of the solar system is recorded in the save, so you'll have to start a new save after applying the patch.  There is no way that this can be fixed by editing the save.  If you choose to edit your save, don't come to us for help.

**Comment by leftfusion** [comment]
Your response is appreciated and your policy understood.
