### ISSUE TITLE
CTD when colliding with (or going roughly near) an asteroid with RSS

### ISSUE THREAD

**Issue by drhead** [mockingbirdnest/Principia#3219]
Bug was reported under RSS's repository before, and independently isolated to be a Principia incompatibility issue: https://github.com/KSP-RO/RealSolarSystem/issues/238

I am certain that I have intercepted asteroids before with Principia and without RSS without issues.

The only relevant lines in the principia logs that happen at the instant of the crash are as follows (I have checked KSP.log and Player.log over multiple crashes, as well as the crash folders, nothing related to the crash appeared in any of them, and no crash folder was ever created for these crashes):

```
I1128 16:26:28.744864 16180 ksp_plugin_adapter.cs:1310] Reporting collision with collider solid8 (0)
I1128 16:26:28.744864 16180 plugin.cpp:561] Collision between probeCoreOcto2.v2 (4A603C0E) and PotatoRoid (DB95666E)
    @   00007FF86524443F  	google::LogMessageFatal::~LogMessageFatal [0x00007FF86524443E+46]
    @   00007FF802DF556C  	principia__VesselVelocity [0x00007FF802DF556B+1238187]
    @   00007FF802C9BE94  	principia__ReportPartCollision [0x00007FF802C9BE93+387]
    @   000002DC1C766D36  	(No symbol) [0x000002DC1C766D35]
F1128 16:26:28.744864 16180 plugin.cpp:568] Check failed: v2.WillKeepPart(part2) PotatoRoid (DB95666E) will vanish
```
Another instance of the same crash:
```
I1128 15:50:20.019603  6460 ksp_plugin_adapter.cs:1310] Reporting collision with collider solid8 (0)
I1128 15:50:20.019603  6460 plugin.cpp:561] Collision between smallClaw (A9800317) and PotatoRoid (DB95666E)
    @   00007FF875F7443F  	google::LogMessageFatal::~LogMessageFatal [0x00007FF875F7443E+46]
    @   00007FF80348556C  	principia__VesselVelocity [0x00007FF80348556B+1238187]
    @   00007FF80332BE94  	principia__ReportPartCollision [0x00007FF80332BE93+387]
    @   00000230FADCD846  	(No symbol) [0x00000230FADCD845]
F1128 15:50:20.019603  6460 plugin.cpp:568] Check failed: v2.WillKeepPart(part2) PotatoRoid (DB95666E) will vanish
```

Based on the linked issue under RealSolarSystem, it appears that RSS's asteroids aren't exactly perfect on their own, and are subject to strange behavior upon collisions (the collision model doesn't appear to align with the visible mesh, last crash I crashed before touching the visible mesh, on the very first one I went a few meters inside the asteroid before crashing).  This bug is also most likely caused by RSS's rescaling of asteroids to be orders of magnitude larger with higher density.

I have also created a journaling file recorded during a crash and can upload it on request, though it is over 1GB in size.

**Comment by pleroy** [comment]
It would be nice if you could upload the journal somewhere (I recommend compressing it before the upload).  I suspect that RSS is violating an invariant of KSP, but I'd like to know for sure.

**Comment by drhead** [comment]
Here's the journal file:
https://drive.google.com/file/d/1R8b3Po8GJwNANYUw9vCyKUWN6Za8cXj4/view?usp=sharing

**Comment by pleroy** [comment]
Closing as we have not heard of this bug after #3349.
