### ISSUE TITLE
Cannot get the reference frame selector window

### ISSUE THREAD

**Issue by kbsj** [mockingbirdnest/Principia#3226]
Hello
When trying to set my reference l click on the reference frame selector (not sure about translation as i use french localisation: Selection du référentiel de dessin). 
Instead of getting the new selection window I used to have with previous version installed I get a small icon on the top left just below the time acceleration looking like a cross. 
I am not able to play with the reference due to that. 
Can you help?
I have attached a screenshot of the game with the icon displayed just left of Principia window. 
I will revert to previous version and see if the problem is resolved again. 
Thank you very much. 
I also take the occasion to thank even more for this impressive and outstanding mod!

![image](https://user-images.githubusercontent.com/12197273/144751485-7d641c27-5907-4c47-a117-ff0243a36d26.png)

**Comment by pleroy** [comment]
Nous vous remercions de votre rapport d'anomalie.  Le problème semble assez sérieux pour nécessiter que nous reconstruisions une nouvelle version de Hamilton.  Nous mettrons à jour le fichier [README](https://github.com/mockingbirdnest/Principia#readme) lorsque cette version sera disponible (dans quelques heures).

For users who don't read French and might run into this issue: it seems bad enough that we will rebuild the Hamilton release.  We'll update the [README](https://github.com/mockingbirdnest/Principia#readme) file once the new release is ready (in a few hours).

**Comment by kbsj** [comment]
Hello, 
Thank you very much for such a rapid fix.
It works for me. 
Closing the issue.
