### ISSUE TITLE
Crash when looking at trajectories without having looked at a window since the process was started

### ISSUE THREAD

**Issue by Mirviy** [mockingbirdnest/Principia#3239]
How I encountered this problem: 
Create a flight plan for a current loaded craft in space; (maneuver showed in navball)
Save the game;
Exit KSP and Restart;
Continue the game and immediately load the saved file;
Press M, game froze for seconds and crash.

If I delete the flight plan then press M, I can continue game.

**Comment by eggrobin** [comment]
Please post the appropriate logs: https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt.

**Comment by Mirviy** [comment]
Here are glogs:
https://gist.github.com/Mirviy/02491449a2d5bd20cb8f2717341d025d

**Comment by pleroy** [comment]
Note for ourselves: what happens is probably that the class `Style` get initialized to obtain the colors for the tangent/normal/binormal, and this initialization causes the static members to be created, and for some reason Unity has this silly restriction that you cannot create a `GUIStyle` outside of `OnGUI`.

Solution: create the `GUIStyle` really lazily, when they are needed (this will be in `OnGUI`).

Work-around for users: bring up the main Principia window before doing anything else after loading a save.

(This is from reading the code, not from any experiments.)
