### ISSUE TITLE
FAQ claims support for wrong KSP versions

### ISSUE THREAD

**Issue by jonesmz** [mockingbirdnest/Principia#3267]
https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions

> Note that Principia currently targets KSP 1.5.1, 1.6.1, 1.7.x, and 1.8.1.

README.md has

> Hamilton, the December version of Principia, is available with performance improvements and bug fixes.
> Download it here for 1.8.1, 1.9.1, 1.10.1, 1.11.0, 1.11.1, 1.11.2, and 1.12.2.

There may be other discrepancies that I'm not able to notice in the FAQ page, so I wanted to open an issue instead of attempting to edit the wiki directly.

**Comment by pleroy** [comment]
Changed to reference the README.  If we replicate the list of versions everywhere, we are sure to have inconsistencies.

This being said, you should feel free to edit/improve the wiki.  That's why it's a wiki.
