### ISSUE TITLE
Request: Auto jool mods for OPM

### ISSUE THREAD

**Issue by JovietUnion** [mockingbirdnest/Principia#3281]

**Comment by pleroy** [comment]
Any reason why [this patch](https://gist.githubusercontent.com/eggrobin/31f6d0c246ecbe50423488f867fe7051/raw/55b814cd14b3c9fdd63119cee96dacb847e2e9ea/retrobop.cfg) doesn't work?

**Comment by JovietUnion** [comment]
In the kopernicus system config, where do I put the text?

**Comment by eggrobin** [comment]
You put the .cfg file anywhere under GameData. It’s a ModuleManager patch (that’s what those `@` and `[]` are about), ModuleManager will use it and take care of modifying the `Kopernicus` entry in the configuration as described in the patch.

**Comment by JovietUnion** [comment]
Got it. Thanks!
