### ISSUE TITLE
Principia doesn't run after installation on MacOs

### ISSUE THREAD

**Issue by dchapman2146** [mockingbirdnest/Principia#3285]
[KSP.log](https://github.com/mockingbirdnest/Principia/files/7878847/KSP.log)

I installed Principia by downloading "principia hardy for 1.12.2.zip" to Downloads. Unzipped it in Downloads and then moved the Principia folder to /Applications/KSP_osx/GameData. When I start KSP I don't see any evidence that principia is working. Orbits are still the same as without Principia and the nav ball is the same as it was without Principia. I am running MacOs High Sierra. I have KSP 1.11.2 which I believe is compatible with Hardy.

The log file says that it was unable to open Applications/KSP_osx/GameData/Principia/MacOS64/principia. The MacO64 folder contains a file named principia.so

Thank you for any help that you can offer
dchapman2146@comcast.net

**Comment by rnlahaye** [comment]
I tried Hardy on 1.11.2 (albeit on Monterey), and got a similar error in the KSP.log, but nevertheless Principia loaded and was functional.

Did Principia save any of its own logs? (That is, are there any files in Applications/KSP_osx/glog/Principia?) If so, please post them.

**Comment by dchapman2146** [comment]
After starting KSP there were 3 new files in KSP_osx/glog/principia which I have attached. 
I also attached a screenshot of the training "To the Man part  1" which I interpret as showing that Principia hasn't been loaded correctly. I am doing this because I am afraid that I am making some silly mistake and that Principia has loaded correctly.

[ERROR.20220117-172148.41138.log](https://github.com/mockingbirdnest/Principia/files/7885450/ERROR.20220117-172148.41138.log)
[INFO.20220117-172148.41138.log](https://github.com/mockingbirdnest/Principia/files/7885453/INFO.20220117-172148.41138.log)
[WARNING.20220117-172148.41138.log](https://github.com/mockingbirdnest/Principia/files/7885454/WARNING.20220117-172148.41138.log)
<img width="644" alt="Screen Shot 2022-01-17 at 5 29 35 PM" src="https://user-images.githubusercontent.com/16739348/149855420-870597b8-69cf-4d8f-8799-341d189641f2.png">

**Comment by dchapman2146** [comment]
I'm sorry. I just started a sandbox instead of a training game and Principia is there.  I assumed that the training exercises would include Principia.

Sorry to have waisted your time.

**Comment by pleroy** [comment]
Closing as this is not an issue.  @rnlahaye thanks for your help with this one.
