### ISSUE TITLE
Beef up TransposedView

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#3302]
> (Note: we may want to have a more general and more powerful `TransposedView` in the future as the result of all `Transpose` (with conversions to the appropriate matrix types if actual transposition of the data is needed), but this is a rabbit hole for another day; for now this draft is good enough.)

_Originally posted by @eggrobin in https://github.com/mockingbirdnest/Principia/pull/3287#discussion_r789228715_

**Comment by pleroy** [comment]
Also unify the operators in `fixed_arrays` and `unbounded_arrays` to avoid having each implementation twice.
