### ISSUE TITLE
Not entirely an issue, but...does the Linux and MacOS folders in Principia contribute anything to my ksp_x64? And if it didn't, can I remove those files?

### ISSUE THREAD

**Issue by harrytherocketeer** [mockingbirdnest/Principia#3334]

**Comment by eggrobin** [comment]
> Not entirely an issue

Indeed having a sixteen megabyte folder lying around cannot conceivably be an issue.

Seeing are also the one who opened #3284 earlier without providing the necessary logs, I am going to ask you to stop wasting our time with useless issues.
