### ISSUE TITLE
Crash when changing to map or select vessel in tracking station

### ISSUE THREAD

**Issue by kretze** [mockingbirdnest/Principia#3341]
```
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0318 20:35:53.093883 10892 interface.cpp:702] Initialized Google logging for Principia
E0318 20:35:53.097215 10892 interface.cpp:703] Principia version 2022030218-Hausdorff-0-g82d602cb25d0130a4d019cf481092e85a18d0550 built on 2022-03-01T18:13:05Z by Microsoft Visual C++ version 192930037 for Windows x86-64
E0318 20:35:53.097215 10892 interface.cpp:716] Base address is 00007FFECE9D0000
    @   00007FFF3B85443F  	google::LogMessageFatal::~LogMessageFatal [0x00007FFF3B85443E+46]
    @   00007FFECEC11A31  	principia__VesselVelocity [0x00007FFECEC11A30+1453072]
    @   00007FFECEC0F700  	principia__VesselVelocity [0x00007FFECEC0F6FF+1444063]
    @   00007FFECEC15377  	principia__VesselVelocity [0x00007FFECEC15376+1467734]
    @   00007FFECEAA84B9  	principia__PlanetariumPlotPsychohistory [0x00007FFECEAA84B8+664]
    @   00000239B7FB6B83  	(No symbol) [0x00000239B7FB6B82]
F0318 20:37:20.985167 10892 discrete_trajectory_body.hpp:458] Check failed: (ConsistencyStatus()) == ::absl::OkStatus() (INTERNAL: Duplicated time mismatch 1961-06-04T22:56:16,0957183837890625 (TT) and J2000+0.00000000000000000e+00 s (TT) for segment #207 vs. OK) 
```

in active flight scene open the map -> crash
in tracking station activate the vessel -> crash

[stderr.log](https://github.com/mockingbirdnest/Principia/files/8307350/stderr.log)
[WARNING.20220318-203553.21656.log](https://github.com/mockingbirdnest/Principia/files/8307351/WARNING.20220318-203553.21656.log)
[INFO.20220318-203553.21656.log](https://github.com/mockingbirdnest/Principia/files/8307580/INFO.20220318-203553.21656.log)

**Comment by rsparkyc** [comment]
I'm getting the same error: 
```
Log file created at: 2022/03/29 16:26:11
Running on machine: DESKTOP-OI08K6H
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FFDC5B8443F  	google::LogMessageFatal::~LogMessageFatal [0x00007FFDC5B8443E+46]
    @   00007FFD3EB41A31  	principia__VesselVelocity [0x00007FFD3EB41A30+1453072]
    @   00007FFD3EB3F700  	principia__VesselVelocity [0x00007FFD3EB3F6FF+1444063]
    @   00007FFD3EB45377  	principia__VesselVelocity [0x00007FFD3EB45376+1467734]
    @   00007FFD3E9D84B9  	principia__PlanetariumPlotPsychohistory [0x00007FFD3E9D84B8+664]
    @   000001E4E94DC4B7  	(No symbol) [0x000001E4E94DC4B6]
F0329 16:26:11.539700  4648 discrete_trajectory_body.hpp:458] Check failed: (ConsistencyStatus()) == ::absl::OkStatus() (INTERNAL: Duplicated time mismatch 1966-11-26T06:43:46,3778676986694336 (TT) and J2000+0.00000000000000000e+00 s (TT) for segment #3 vs. OK) 
```

**Comment by pleroy** [comment]
I didn't really investigate the report by @kretze (I would need a journal, and even so the analysis is kind of difficult) but this looks very similar to #3332.  The good news is that this issue will be fixed in the next release, Heine, on April 1st.  The bad news is that the saves are botched (they are missing some data in the history) so there is no real way to fix the problem other than (1) not displaying too much history or (2) using the Hack Gravity hack to clear the history of the faulty vessel (if you manage to figure out which one it is).

**Comment by rsparkyc** [comment]
How does the hack gravity work? Do you just toggle the setting?

**Comment by eggrobin** [comment]
@rsparkyc: Fly affected vessel, check the hack gravity setting so Principia doesn’t see it anymore and forgets about it, and then unhack gravity so Principia sees it again (but has forgotten about its broken history).

**Comment by rsparkyc** [comment]
Sweet, that made my save playable again :) Hopefully we won't see that again with the new release!

**Comment by pleroy** [comment]
Since we have not seen this crash in more than a month, and #3332 was fixed in Heine, I am going to assume that these are two occurrences of the same problem and close this issue.
