### ISSUE TITLE
Consider making ContinuousTrajectory non-thread safe

### ISSUE THREAD

**Issue by pleroy** [mockingbirdnest/Principia#3345]
The performance analysis done as part of #3230 uncovered that the locking in `ContinuousTrajectory` is fairly expensive.  In particular, `ContinuousTrajectory::EvaluatePosition` uses about 12.4% of the CPU in that journal, of which 5.3% is taken by locking/unlocking the mutex.

Considering that this class is only ever used from `Ephemeris` it might be preferable to declare that it is *not* thread-safe and that `Ephemeris` is in charge of all the synchronization.

**Comment by rnlahaye** [comment]
I have also observed this in traces.
