### ISSUE TITLE
Principia does not run in debug KSP

### ISSUE THREAD

**Issue by al2me6** [mockingbirdnest/Principia#3436]
I suspect the issue was introduced in https://github.com/mockingbirdnest/Principia/pull/3303. ~~https://github.com/mockingbirdnest/Principia/pull/3201 is also suspect.~~

What I believe to the cause (apologies for screenshot-of-code):

![image](https://user-images.githubusercontent.com/35266431/188330702-0156798b-38c0-42ad-981f-75eda5dd6659.png)

cc @StonesmileGit

**Comment by StonesmileGit** [comment]
This NRE gets spammed while in a save:
```
[EXC 21:38:02.061] NullReferenceException: Object reference not set to an instance of an object
	principia.ksp_plugin_adapter.PrincipiaPluginAdapter.OnGUI () (at <29cbeb58583d4aa39b0d1d244f47f24e>:0)
```

**Comment by pleroy** [comment]
For the uninformed: what is "debug KSP" and where do I buy one?

**Comment by al2me6** [comment]
It is running KSP's unity in debug mode. _cf._ https://gist.github.com/gotmachine/d973adcb9ae413386291170fa346d043

**Comment by pleroy** [comment]
I think it needs lazy initialization of `psychohistory_mesh_`, `prediction_mesh_`, `target_psychohistory_mesh_`, and `target_prediction_mesh_`,

**Comment by DRVeyl** [comment]
Essentially yes.  You're instantiating Unity objects during the Plotter constructor [static declarations at the class level], which is not allowed.  The exception is swallowed or suppressed in non-debug mode.  More appropriate would be to put those initializations into a new `Plotter.Awake()` method, which gets automatically called right after the constructor.
