### ISSUE TITLE
Principia DLL failed to load 1.12.3

### ISSUE THREAD

**Issue by FallinGuy** [mockingbirdnest/Principia#3450]
i am getting this message on start screen. i tried to find principia.dll file and found it in the right place. then tried removing the file out and putting it in when i was out of the game but it didnt work

**Comment by LookItVal** [comment]
Im having this same problem. Fresh install if KSP, no mods except Principia. OSX Catalina.
when I open the game it loads correctly then I'm the main menu screen it says the DLL failed to load.
I could grab the exact text if needed but it sounds like the same problem you had, did you find a solution?
