### ISSUE TITLE
Verbosity levels

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#347]
We use `VLOG(1)` everywhere right now, and that quickly makes the logs unmanageable.
We should define criteria for verbosity levels. Since we're a library and we can't set flags, we also need to make verbosity tunable in-game.
###### Proposal

Where O is for the following variables going to positive infinity
f = frequency of `FixedUpdate`s
v = number of vessels
p = number of parts
c = number of celestials
t = length of histories

| severity or verbose level | frequency \* size | example |
| --: | :-- | :-- |
| `LOG(INFO)` | aperiodic | ships exploding / appearing |
| `VLOG(1)` | O(f) | calls to `AdvanceTime` |
| `VLOG(2)` | O((v+c)f) | calls to `InsertOrKeepVessel` |
| `VLOG(3)` | O((v+c+p)f) | arguments of `AddVesselToNextPhysicsBubble` |
| `VLOG(4)` | O((v+c+p+t)f) | return value of `RenderedVesselTrajectory` |

**Comment by pleroy** [comment]
We don't debug with `VLOG` anymore.
