### ISSUE TITLE
Changing the sign of a flight plan delta-v value

### ISSUE THREAD

**Issue by lpgagnon** [mockingbirdnest/Principia#3480]
QoL issue with the new fancy flight plan editor, similar to #3475 : it used to be possible to double-click-select one of the dv values and type either a positive or negative number, regardless of the sign of the previous value; now it's not possible to change the sign this way, because the sign in the input field is separate from the numbers, doesn't get highlighted with it, and the validator doesn't accept a second sign.

Making the validator accept +-NNN would help with the "change from positive to negative", but making "-+NNN" get treated as "+NNN" for the reverse case would be weird. Not seeing another way to handle it though

**Comment by eggrobin** [comment]
Additional discussion on Discord:
> <@lpgagnon> fwiw my main use case is starting a new flight plan by entering a negative number (I'm going to the moon, I know the capture is going to be -900). So maybe just not displaying a sign when the value is zero is all it takes 
> <@eggrobin> good point. making a double-click grab the sign should be easy enough, but then it makes changing a negative value to another one more annoying, which seems like cooling one spacebar to warm another

**Comment by lpgagnon** [comment]
The change does not appear sufficient to achieve the goal; still can't actually type in a negative number:

<img width="217" alt="Screenshot 2023-01-03 at 19 45 27" src="https://user-images.githubusercontent.com/5061230/210464731-ceac847f-63d1-4cc5-91ee-2ad61bc4b142.png">
