### ISSUE TITLE
Computation failed with error 4 when extending flight plan

### ISSUE THREAD

**Issue by Test-Account-KSP** [mockingbirdnest/Principia#3483]
Error message "Computation failed with error 4" appears when I extend a flight plan similar to the usual TLI maneuver to 10-20 days.
Steps to replicate: 
- enter the VAB, simulate any craft in 200km orbit, 
- create flight plan with max steps 4096, tolerance 10m, plan length 4 days
- add maneuver with t initial = 1h 1m, dV = 3150 prograde, inertially fixed, instant impulse
- extend flight plan from 4 days to 14 days or similar (entered 14 instead of 4 in the field, without moving the slider) 

![screenshot](https://user-images.githubusercontent.com/110846612/209436039-9ed4c327-fd80-4ac6-a70c-cf5ab668467e.png)

[persistent.zip](https://github.com/mockingbirdnest/Principia/files/10298550/persistent.zip)

[INFO.20221224-112749.6464.log](https://github.com/mockingbirdnest/Principia/files/10298551/INFO.20221224-112749.6464.log)

[WARNING.20221224-112749.6464.log](https://github.com/mockingbirdnest/Principia/files/10298552/WARNING.20221224-112749.6464.log)

[ERROR.20221224-112749.6464.log](https://github.com/mockingbirdnest/Principia/files/10298553/ERROR.20221224-112749.6464.log)

Another screenshot (different craft, same issue)

![screenshot19](https://user-images.githubusercontent.com/110846612/209436388-090fa457-1e2a-4570-8868-a96c5abd2b6d.png)

**Comment by pleroy** [comment]
We are running into this limit: https://github.com/mockingbirdnest/Principia/blob/c284c2a9a9c07df3b2a0c3238cee67b124b3b96a/ksp_plugin/flight_plan.hpp#L131
The right fix is probably to make the computation of the flight plan asynchronous, but that's a bit of work.
