### ISSUE TITLE
Consistent freeze on exiting tracking station

### ISSUE THREAD

**Issue by DerekC95** [mockingbirdnest/Principia#3520]
I've been having a consistent game breaking freeze when playing RP-1 with principia.

It does not happen on new saves until a decade or so into the save, usually around the time I start sending ships to the moon and/or the number of craft/debris left in orbit starts to increase (it's hard to say exactly what triggers it) but once it starts to occur I haven't been able to find a work around. If I enter the tracking station, click around on a vessel or 2 and then attempt to leave the tracking station the game will completely lock up until I force close it. This is very consistent, it will happen almost every single time I use the tracking station. It does not happen if I open and close the tracking station without selecting a vessel, no matter how long I spend there, only if I have selected a vessel at some point. Sometimes I can get away with clicking 1 or 2 vessels then closing the tracking station without it freezing but 3-4 vessels will almost always cause a freeze. The vessels I click on which cause the freeze do not seem to be consistent as far as I can tell.

On the surface it appears to be a very similar issue as was reported in https://github.com/mockingbirdnest/Principia/issues/3479

There is no crash log generated, I've uploaded my latest glog files and my persistent save here: https://gist.github.com/DerekC95/2e04fd1f2b5f8153c6c41d4ab237a04c
Notably I see that the last line of the INFO file is truncated, this is consistent every time the issue occurs, although not at a consistent event.

I think this is a principia error as this freeze has happened sooner or later on all 3 of the principia + RP-1 games I have attempted to play and has never occured on the many other non-principia RP-1 games I have played, many of which I have played much further than my principia saves (as the freeze makes the game pretty unplayable with RP-1s long load times). I have never been able to play more than a decade or 2 into a principia/RP-1 save because of this issue.

The first time I encountered this issue was almost a year ago if I remember correctly (I no longer have the save), all games were played in KSP 1.12.3 (as far as I can remember) but in different principia versions each time, starting with Heine (if I remember correctly) and the latest occurence was in the newest release Horner. Each time the KSP directory was copied from my clean unmodded steam directory and the save was started fresh.

I can provide additional files including my complete current modlist if needed

**Comment by pleroy** [comment]
There is nothing obviously wrong with the save.  Since you seem to have a reproducible scenario, what would help is to get a journal (instructions [here](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#journaling)).  Load the save, get into a state where it freezes, let it run for 30-60 seconds, and kill the game.  Send us the `JOURNAL.*` file found in the `glog\Principia` directory.  That could give us useful insights.

**Comment by DerekC95** [comment]
As a text gist:
https://gist.github.com/DerekC95/d9ae55b284f871c99c9ec87227b9fead

On google drive if that's better:
https://drive.google.com/file/d/1T19nH-br2jqD2ur9Bj6RtOHpe5XAgiTt/view?usp=share_link

I let the game lock up for a good 60 seconds before closing.

Thanks for your help

**Comment by pleroy** [comment]
Thanks for the journal.  I was able to reproduce the problem and I understand it.  Fixing it is going to require some care, though.

Note to self: we have 4 threads doing some interesting work.  One is trying to destroy a vessel, the other 3 are trying to reanimate vessels, including the one being destroyed:
|Thread Id|Function|Vessel GUID|Vessel Name|
|--|--|--|--|
|456|Vessel::ReanimateOneCheckpoint|"d190f9e1-a4fe-4919-9142-d691dce6a0cd"|"FSS"|
|12856|Vessel::ReanimateOneCheckpoint|"1c0139c8-8baa-4a05-a7eb-c62443357f28"|"FAS"|
|14664|Vessel::ReanimateOneCheckpoint|"5a0a11a6-e28f-49fa-a98b-3598047f453c"|"Luna I Probe"||
|18088|Vessel::~Vessel|"d190f9e1-a4fe-4919-9142-d691dce6a0cd"|"FSS"|

All the calls to `ReanimateOneCheckpoint` are stuck in `Ephemeris::WaitForReanimation`.  The call to `~Vessel` is trying to join with the `reanimator_` of the `Vessel`.

Now for the the curious incident of the dog in the night-time: there is no thread doing reanimation of the `Ephemeris`.  So the vessel reanimators make no progress, the joining cannot happen, and we have a deadlock.

The log messages related to reanimation can be found below.  Note how reanimation of the vessels properly causes reanimation of the ephemeris, but then the `Ephemeris` reanimator is immediately restarted with a desired `t_min` in the future:
```
I0218 12:50:37.668463 10068 ephemeris_body.hpp:774] Restoring to checkpoint at 1960-05-08T03:30:00,0000000000000000 (TT)
I0218 12:50:39.098989 12720 ephemeris_body.hpp:774] Restoring to checkpoint at 1960-05-08T03:30:00,0000000000000000 (TT)
I0218 12:50:40.668052 14664 vessel.cpp:935] Reanimating Luna I Probe (5a0a11a6-e28f-49fa-a98b-3598047f453c) until 1960-04-19T10:52:45,0084726810455322 (TT)
I0218 12:50:40.668052 14664 vessel.cpp:978] Restoring Luna I Probe (5a0a11a6-e28f-49fa-a98b-3598047f453c) to checkpoint at 1959-07-19T19:29:44,3274731636047363 (TT) until 1960-04-24T19:29:14,3274731636047363 (TT)
I0218 12:50:40.678058 17580 ephemeris_body.hpp:891] Reanimating segment from 1959-05-14T03:10:00,0000000000000000 (TT) to 1959-11-10T03:20:00,0000000000000000 (TT)
W0218 12:50:40.688324 18088 ephemeris_body.hpp:250] Restarting reanimator because desired t_min went from 1959-07-19T19:29:44,3274731636047363 (TT) to 1960-04-19T10:52:45,0284726619720459 (TT)
I0218 12:50:43.512585   456 vessel.cpp:935] Reanimating FSS (d190f9e1-a4fe-4919-9142-d691dce6a0cd) until 1960-04-19T10:52:47,9884698390960693 (TT)
I0218 12:50:43.512585   456 vessel.cpp:978] Restoring FSS (d190f9e1-a4fe-4919-9142-d691dce6a0cd) to checkpoint at 1956-08-13T11:25:02,4769225120544434 (TT) until 1960-04-23T16:02:42,4769225120544434 (TT)
I0218 12:50:43.532681 16388 ephemeris_body.hpp:891] Reanimating segment from 1959-05-14T03:10:00,0000000000000000 (TT) to 1959-11-10T03:20:00,0000000000000000 (TT)
W0218 12:50:43.532784 18088 ephemeris_body.hpp:250] Restarting reanimator because desired t_min went from 1956-08-13T11:25:02,4769225120544434 (TT) to 1960-04-19T10:52:48,0084698200225830 (TT)
I0218 12:50:46.173612 12856 vessel.cpp:935] Reanimating FAS (1c0139c8-8baa-4a05-a7eb-c62443357f28) until 1960-04-19T10:52:50,2884676456451416 (TT)
I0218 12:50:46.173612 12856 vessel.cpp:978] Restoring FAS (1c0139c8-8baa-4a05-a7eb-c62443357f28) to checkpoint at 1955-09-20T18:15:52,9406449794769287 (TT) until 1960-04-21T00:42:52,9406449794769287 (TT)
I0218 12:50:46.183619 11116 ephemeris_body.hpp:891] Reanimating segment from 1959-05-14T03:10:00,0000000000000000 (TT) to 1959-11-10T03:20:00,0000000000000000 (TT)
W0218 12:50:46.193800 18088 ephemeris_body.hpp:250] Restarting reanimator because desired t_min went from 1955-09-20T18:15:52,9406449794769287 (TT) to 1960-04-19T10:52:50,3084676265716553 (TT)
```
What is believed to happen is this: a vessel (say, `FSS`) wants to reanimate starting at 1956-08-13.  The  `Ephemeris` starts to reanimate its first segment (going backwards) from 1959-05-14 to 1959-11-10.  But then a call to `principia__PlanetariumPlotCelestialPastTrajectory` (maybe from the UI) updates the desired `t_min` to 1960-04-19, cause the reanimator of the `Ephemeris` to restart and the vessel to remain stuck waiting for the `t_min` of the `Ephemeris` to be at or before 1956-08-13.  This is mostly invisible (the reanimator of the vessel doesn't synchronize with anyone) until the vessel needs to be destroyed, at which point everything gets stuck.
