### ISSUE TITLE
CTD when loading from save (RP-0 PLC save) and adjusting maneuver for moon probe

### ISSUE THREAD

**Issue by rsparkyc** [mockingbirdnest/Principia#3549]
It doesn't happen every time, but this might be the 2nd time I've seen it when doing the same sort of mission. This is when I'm planning on my TLI burn for a probe destined to orbit the moon.

[INFO.20230307-091121.20528.log](https://github.com/mockingbirdnest/Principia/files/10910770/INFO.20230307-091121.20528.log)
[WARNING.20230307-091121.20528.log](https://github.com/mockingbirdnest/Principia/files/10910771/WARNING.20230307-091121.20528.log)
[ERROR.20230307-091121.20528.log](https://github.com/mockingbirdnest/Principia/files/10910772/ERROR.20230307-091121.20528.log)
[FATAL.20230307-095714.20528.log](https://github.com/mockingbirdnest/Principia/files/10910773/FATAL.20230307-095714.20528.log)

**Comment by rsparkyc** [comment]
Seems quite possible. Will check in about 14 days :)

**Comment by pleroy** [comment]
If you know how to reproduce it, a journal would be nice.  There have been many changes in this code lately, and there may be more bugs than just #3545.

**Comment by rsparkyc** [comment]
I tried to get it to fail again, but to no avail. I'll try to leave journaling on when I'm going to the moon to see if I can catch it.

**Comment by pleroy** [comment]
This hasn't been reported since March, the failure was seen in Householder and #3545 went into Hurwitz, so I am going to assume that it's all good now.  Please reopen if you see the bug again.
