### ISSUE TITLE
Delta V map

### ISSUE THREAD

**Issue by xsrvmy** [mockingbirdnest/Principia#3553]
I think it would be nice for there to be a delta v map for the stock system using principia. The main change would be the Joolean moons since they have different orbits. It would also be nice to have delta v values for somewhat stable Lagrange points, especially since L4 and L5 can be useful places to put relays

**Comment by afishcallederic** [comment]
Although transfer window planners are less accurate, using the Transfer Window Planner mod, or MechJeb's porkchop plot would give starting points that can be 'sanity checked' since planets like Duna/Dres don't move much relative to stock.

**Comment by pleroy** [comment]
We are not in the business of Δv maps.  There are other mods (TWP or MechJeb, as mentioned above) to help with planning.

Regarding the Lagrange points, the rotating-pulsating reference frame that was recently added gives a lot more detailed information than a Δv map would.
