### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by Shadlock0133** [mockingbirdnest/Principia#3554]
is there a reason Principia is distributed through Google Drive links, instead of Github releases? using them would also allow for easy access for people looking for older versions

**Comment by pleroy** [comment]
We use `bit.ly` links to Google Drive because it gives us analytics.

You can find previous releases by looking at the history of the [history of the README.md](https://github.com/mockingbirdnest/Principia/commits/master/README.md) file.
