### ISSUE TITLE
"Flight plan" for planets

### ISSUE THREAD

**Issue by xsrvmy** [mockingbirdnest/Principia#3564]
A very useful feature addition for planning interplanetary missions would be to plot a "flight plan" for Kerbin itself. This would be used to find transfer windows. Proposing this as an easier alternative to #1918.

**Comment by pleroy** [comment]
Believe me, you don't want us to compute the future of celestials.  It would burn a lot of CPU and RAM for very little benefit.  It would also clutter the UI significantly.  I want to point out that, in general, you want to use a frame where your target celestial is immobile to prepare your flight plan, and in that frame there is no future trajectory of the celestial to be drawn.

As mentioned in #1918, there are perfectly good mods (like TWP) for finding transfer windows.
