### ISSUE TITLE
Something is amiss in the reference frames whose axis of rotation varies

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#3615]
It was noted in #3609 that we had an abnormal discrepancy between the motion computed in the inertial frame and that computed using the geometric acceleration in the rotating-pulsating frame, but that this discrepancy was there in the MEO frame already.

This discrepancy is absent in the frame of the lunar surface. Interestingly @pleroy found that it is also absent when the Sun-Earth-Moon system is made planar; thus the issue is not just nonuniform rotation (the orbit of the moon is still eccentric in that case), but variation of the axis of rotation.

**Comment by pleroy** [comment]
The current theory is that [this computation](https://github.com/mockingbirdnest/Principia/blob/7b93a3b06cbd3787ff2697d9bd57d1c77ddd9968/physics/body_centred_body_direction_reference_frame_body.hpp#L213) is incorrect.  What we should be computing is the spin angular velocity of a rigid body (the frame) but we are using the formula for orbital angular velocity; Wikipedia even has a [note](https://en.wikipedia.org/wiki/Angular_velocity#Components_from_the_basis_vectors_of_a_body-fixed_frame) explaining that this is wrong.

**Comment by eggrobin** [comment]
Fixed by #3625.
