### ISSUE TITLE
Crash when in TKO reference frame and the target vessel is destroyed

### ISSUE THREAD

**Issue by brainwad** [mockingbirdnest/Principia#3636]
I was targeted onto the "Rock Grabber", in map view in the TKO reference frame and executing a planned manouever from the flight planner with the flight planner window open, when the game crashed. Logs appear to show that the vessel I  was targetting was destroyed, triggering the crash:

```
I0513 12:40:43.089469  8160 plugin.cpp:581] Removing vessel Rock Grabber (1f1f0dbd-7ed9-4ad4-9935-b51317aa17ab)
I0513 12:40:43.089469  8160 vessel.cpp:92] Destroying vessel Rock Grabber (1f1f0dbd-7ed9-4ad4-9935-b51317aa17ab)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part probeStackSmall (33DADDFD)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part nuclearEngine (48CC3DDD)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part batteryBank (CACC85B3)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part MK1Fuselage (9F532475)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part PotatoRoid (9FD2326B)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part GrapplingDevice (919AB656)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part RCSFuelTank (0AEB9246)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part advSasModule (63A5473F)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part MK1Fuselage (E9340D1C)
I0513 12:40:43.102401  8160 pile_up.cpp:94] Destroying pile up at 0000015D778892E0
    @   00007FF9E03644FF  	google::LogMessageFatal::~LogMessageFatal [0x00007FF9E03644FE+46]
    @   00007FF991CA69D9  	principia__VesselVelocity [0x00007FF991CA69D8+1245224]
    @   00007FF991B7273E  	principia__RenderedPredictionClosestApproaches [0x00007FF991B7273D+573]
    @   0000015C61A720EA  	(No symbol) [0x0000015C61A720E9]
F0513 12:40:43.139051  8160 plugin.cpp:1019] Check failed: renderer_->HasTargetVessel() 
```

**Comment by pleroy** [comment]
Please give all the [complete log files](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt).  A random excerpt is useless.

**Comment by brainwad** [comment]
[INFO.20230513-123636.8536.log](https://github.com/mockingbirdnest/Principia/files/11470116/INFO.20230513-123636.8536.log)
[FATAL.20230513-124043.8536.log](https://github.com/mockingbirdnest/Principia/files/11470117/FATAL.20230513-124043.8536.log)

**Comment by eggrobin** [comment]
Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/969757ec22f307ef722b171d4099e1549e19d27a/ksp_plugin/interface_renderer.cpp#L72-L79  https://github.com/mockingbirdnest/Principia/blob/969757ec22f307ef722b171d4099e1549e19d27a/ksp_plugin/plugin.cpp#L1018-L1019

**Comment by pleroy** [comment]
The logs tell us that the vessel `Rock Grabber` has been removed [here](https://github.com/mockingbirdnest/Principia/blob/969757ec22f307ef722b171d4099e1549e19d27a/ksp_plugin/plugin.cpp#L581).  As part of that removal `ClearTargetVesselIf` is called and the target vessel is removed from the renderer.  It is also removed from the `vessels_` set of the plugin, so future calls to `HasVessel` will return `false`.  Note that after the deletion, on the C# side, `plotting_frame_selector_.target_frame_selected` is still true.

`RenderedPredictionClosestApproaches` is called at [one place](https://github.com/mockingbirdnest/Principia/blob/969757ec22f307ef722b171d4099e1549e19d27a/ksp_plugin_adapter/ksp_plugin_adapter.cs#L2232), within `RenderPredictionMarkers`.  `RenderPredictionMarkers` in turn is called from [two](https://github.com/mockingbirdnest/Principia/blob/969757ec22f307ef722b171d4099e1549e19d27a/ksp_plugin_adapter/ksp_plugin_adapter.cs#L1745) [places](https://github.com/mockingbirdnest/Principia/blob/969757ec22f307ef722b171d4099e1549e19d27a/ksp_plugin_adapter/ksp_plugin_adapter.cs#L1752).  The second one is predicated on the vessel existing (through `HasVessel`) but the first one is not.  Presumably it's this first call that is causing trouble.

We should be more defensive when reading `plotting_frame_selector_.target_frame_selected` and we should also check if the target vessel still exists.
