### ISSUE TITLE
Crash when Decoupling After Loading A Save of Craft in Space (RP-0)

### ISSUE THREAD

**Issue by smunstu** [mockingbirdnest/Principia#3647]
I'm getting a crash when decoupling anything with a impulse percent of zero, but I think that this only occurs if the craft is loaded from a save file or something similar while in space.

If the same craft is launched and decoupled without any scene transitions or saving and loading, the crash does not occur.

**Comment by pleroy** [comment]
Please give us your [logs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt).

**Comment by smunstu** [comment]
Well, I've done a bit of trying and I seem to be having trouble reproducing this error now. I have some partial logs from an earlier date, but I hadn't learned how to activate the Principia Journal yet, so that would be missing from them.

Let me know if you'd like the partial data; otherwise I'll just keep an eye out for it to happen again (it's happened at least twice in my campaign already), and I can be more prepared to provide full logs next time. I'm pretty certain it will eventually happen again.

**Comment by smunstu** [comment]
I didn't have a FATAL log, but I just experienced the bug again with my latest save file. It crashes with a Unity popup box. Let me reproduce it this time with the Journal on, and I'll post everything.

**Comment by smunstu** [comment]
So. I've reproduced the error with the Journalling enabled, but the Journal file is 44 Mb, too large to upload here.

Here is everything else.

let me know what to do with the journal file.

[Error logs.zip](https://github.com/mockingbirdnest/Principia/files/11521181/Error.logs.zip)

**Comment by pleroy** [comment]
Can you put the journal on Google Drive, Dropbox, OneDrive, or a similar service, and post the link here?

**Comment by eggrobin** [comment]
Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/969757ec22f307ef722b171d4099e1549e19d27a/ksp_plugin/interface.cpp#L832-L835  https://github.com/mockingbirdnest/Principia/blob/969757ec22f307ef722b171d4099e1549e19d27a/journal/method_body.hpp#L55-L61 `journal/profiles.generated.cc:1934`

**Comment by pleroy** [comment]
For the record, the failing statement is:
```
void InsertOrKeepVessel::Fill(In const& in, not_null<Message*> const message) {
  auto* const m = message->mutable_in();
  m->set_plugin(SerializePointer(in.plugin));
  m->set_vessel_guid(in.vessel_guid);
  m->set_vessel_name(in.vessel_name);
  m->set_parent_index(in.parent_index);  // Line 1934.
  m->set_loaded(in.loaded);
}
```
The alert reader will notice that the failure occurs during serialization of the journal, so it's telling us nothing about the actual crash which happened before journaling got enabled.

At any rate, the journal replays without crashing on my machine, so it doesn't tell us much.

You should have crash dumps dated around May 17th-20th in directory `C:/Users/Minowara/AppData/Local/Temp/Squad/Kerbal Space Program/Crashes`.  Could you upload them to Google Drive?  They might contain useful information.

**Comment by pleroy** [comment]
No life signs, closing.
