### ISSUE TITLE
Crash when targetting a vessel

### ISSUE THREAD

**Issue by msabathier** [mockingbirdnest/Principia#3653]
Hi,
I just updated Principia to the latest version and then tried to finish my Mun mission by doing a rendez-vous between the lander and the orbiter but as soon as i click on the vessel to target it, i get a freeze (about 3-4 seconds) and then KSP just closes without any messages.
I tried both targetting the lander with the orbiter as the active vessel and targetting the orbiter with the lander as the active vessel but i get the freeze and crash each time.

I turned journaling on and reproduced the issue here are the logs :
[INFO.20230520-102545.9324.log](https://github.com/mockingbirdnest/Principia/files/11521917/INFO.20230520-102545.9324.log)
[WARNING.20230520-102545.9324.log](https://github.com/mockingbirdnest/Principia/files/11521918/WARNING.20230520-102545.9324.log)
[ERROR.20230520-102545.9324.log](https://github.com/mockingbirdnest/Principia/files/11521919/ERROR.20230520-102545.9324.log)
[FATAL.20230520-103014.9324.log](https://github.com/mockingbirdnest/Principia/files/11521920/FATAL.20230520-103014.9324.log)

and the journal : [JOURNAL.20230520-102851](https://drive.google.com/file/d/1RFmRDkVbBVSxKymtbAsIPfYD_8XGq530/view?usp=share_link)

I have a good amount of mods on this install, let me know if you need the list.

Also, since i am a bit of an idiot, i did not make a backup of the penultimate principia release binaries... Is there a place where i can find the binaries for Ὑπατία ? Or do i need to build it from the source ?

Thanks in advance for your time and response

**Comment by jd284** [comment]
I have the same crash (I think), when switching to the TgtEO frame on a ship that already has the target set. It's probably not the targeting itself, but the automatic switch to TgtEO.

**Comment by pleroy** [comment]
Look at the history of the [README.md](https://github.com/mockingbirdnest/Principia/blob/master/README.md) file, you'll find the links to the previous version.

**Comment by eggrobin** [comment]
Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/9f3105efa9ead54ad17567161fb59e5094829f7d/ksp_plugin/interface_planetarium.cpp#L171-L180  https://github.com/mockingbirdnest/Principia/blob/9f3105efa9ead54ad17567161fb59e5094829f7d/ksp_plugin/planetarium.cpp#L279-L286  https://github.com/mockingbirdnest/Principia/blob/9f3105efa9ead54ad17567161fb59e5094829f7d/ksp_plugin/planetarium.cpp#L298-L351  https://github.com/mockingbirdnest/Principia/blob/9f3105efa9ead54ad17567161fb59e5094829f7d/physics/rigid_reference_frame_body.hpp#L31-L32  https://github.com/mockingbirdnest/Principia/blob/9f3105efa9ead54ad17567161fb59e5094829f7d/physics/body_centred_body_direction_reference_frame_body.hpp#L103-L104  https://github.com/mockingbirdnest/Principia/blob/9f3105efa9ead54ad17567161fb59e5094829f7d/physics/discrete_trajectory_segment_body.hpp#L160-L166

**Comment by pleroy** [comment]
We'll publish an updated ابن الهيثم release in a few hours.

**Comment by pleroy** [comment]
@msabathier Thanks for the report, and for providing logs and a journal, it was very helpful.

**Comment by msabathier** [comment]
Well thank you @pleroy and @eggrobin for the speedy support !
