### ISSUE TITLE
Update wiki to reflect that Titania and Oberon are included in RSS

### ISSUE THREAD

**Issue by thunkii** [mockingbirdnest/Principia#3702]
c.f. here https://www.reddit.com/r/RealSolarSystem/comments/14dqusq/are_extra_moons_available_for_rss/ and from observation of my RP-1 install, it seems that the moons of Uranus, Vesta, and Ceres are already in base RSS. The wiki should be updated to reflect this.

**Comment by pleroy** [comment]
Thanks for noticing, I have fixed the wiki.

Note that, this being a wiki, we welcome edits by people who notice anomalies.  As you may have noticed, maintaining the documentation is not very high on our priority list.
