### ISSUE TITLE
Questions about kerbin sun-synchronous orbit.

### ISSUE THREAD

**Issue by Aebestach** [mockingbirdnest/Principia#3720]
Sorry to bother you. There is something confusing me right now. When I planned the sun-synchronous orbit in RSS, I imagined whether this orbit could be reproduced on kerbin.
After consultation and reference, I found that kerbin is not an oblate spherical and does not have a sun-synchronous orbit.

Yesterday, I also asked this question on Discord, and a friend told me the solution and @egg sent a link. The content of this link tells me that I can set the J2 parameter through the following methods.
```
principia_gravity_model {
  body {
    name                    = Kerbin
    j2                      = 0.002
  }
}
```
![image](https://github.com/mockingbirdnest/Principia/assets/64588584/d03da51a-d328-4ea2-a349-36f9a7d14b0c)![image](https://github.com/mockingbirdnest/Principia/assets/64588584/95a0f4e8-a492-40a0-aecc-9c658761492e)
I set this parameter in the game. In addition, through the calculation of the above formula, I set my eccentricity, inclination and semi-major axis, but the result given to me by Principia is not the sun synchronous orbit.

I would like to ask if setting the J2 parameter is useless or if I made a mistake when planning the node?

**Comment by pleroy** [comment]
`j2` is supposed to work.  Did you recreate your save?  Because if you did not, you are still using the previous state of your solar system.

Please use Discord for this kind of question.  There are many people there who are in a better position to help you.  Let's not use GitHub for useabilty questions.

**Comment by Aebestach** [comment]
thanks
