### ISSUE TITLE
Maneuver marker renders in flight scene

### ISSUE THREAD

**Issue by kkllffaa** [mockingbirdnest/Principia#3729]
After creating flight plan and maneuver in map scene and switching to flight scene marker is still visible.

**Comment by kkllffaa** [comment]
![screenshot11](https://github.com/mockingbirdnest/Principia/assets/68471730/5703479f-f533-4806-a302-3def26b985ae)
![screenshot10](https://github.com/mockingbirdnest/Principia/assets/68471730/2cbc0014-f4e6-4dc7-8969-c34263361567)
i think you need to be near maneuver for this to show up but didnt tested it

**Comment by al2me6** [comment]
Apologies; this is certainly to do with that PR. It is not immediately clear to me why and I didn't notice this while testing.

I am at work right now, but I will investigate tonight.

**Comment by al2me6** [comment]
PR sent; apologies again for the oversight.

Once you switch to map view, the marker gets stuck at some random position in the world. Hence it is only visible if you happen to look in the right direction, and if it's not obstructed by something.
