### ISSUE TITLE
Manoeuvre markers render outside of map view

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#3731]
![image](https://github.com/mockingbirdnest/Principia/assets/16473290/396de19a-c07b-45dd-bf94-029503f81435)
This is with version 岩澤. Happens with all manoeuvre markers in the flight plan. The markers update too - their projection changes to what it was the moment you left the map view - as you go in and out of the map view.

**Comment by pleroy** [comment]
Probably the same as #3729, which will be fixed in the next version, Jacobi.

**Comment by scimas** [comment]
Oh, definitely. My bad, didn't look through the closed issues considering how new the latest release is.
