### ISSUE TITLE
Add functions for argument reduction

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#3768]
Currently we have
- A reduction to ]-π/2, π/2[,
 
 https://github.com/mockingbirdnest/Principia/blob/90904e388ac57d2bd7c8920c69898b14128e6314/numerics/elliptic_integrals.cpp#L116-L120
- Many reductions to [0, 2π[, 
 
 https://github.com/mockingbirdnest/Principia/blob/90904e388ac57d2bd7c8920c69898b14128e6314/astronomy/orbital_elements_body.hpp#L461
  
 https://github.com/mockingbirdnest/Principia/blob/90904e388ac57d2bd7c8920c69898b14128e6314/astronomy/orbit_ground_track_body.hpp#L94
  some of them with preconditions, 
 
 https://github.com/mockingbirdnest/Principia/blob/90904e388ac57d2bd7c8920c69898b14128e6314/physics/kepler_orbit_body.hpp#L166-L169
   one slightly better one seemingly used only in tests,
   https://github.com/mockingbirdnest/Principia/blob/90904e388ac57d2bd7c8920c69898b14128e6314/numerics/double_precision_body.hpp#L309-L316

None of those are correctly rounded, and we keep writing more of that kind of thing (most recently in https://github.com/mockingbirdnest/Principia/pull/3761#discussion_r1318976086), there reducing to ]-π, π[.

We should centralize the angle reduction functions somewhere in numerics (and make them correctly rounded someday, see #1760).

**Comment by pleroy** [comment]
A better implementation would be part of #1760.
