### ISSUE TITLE
It is not possible to move objects in orbit using the console.

### ISSUE THREAD

**Issue by Helium-ion** [mockingbirdnest/Principia#3788]
In simple terms, Principia undoes all orbital changes that it deems unreasonable. When the console tries to set the object's orbit, it will fight Principia, who will win. Interestingly, the console can normally set the orbit of an object located on the ground. However, once the object leaves the ground, Principia will dominate it.
No one seems to have asked this question. If this is expected, how can I quickly move an object to a specific place for testing?

**Comment by Capkirk123** [comment]
Enabling "Hack Gravity" in the cheat menu will temporarily deactivate Principia, allowing vessels to be moved through the cheat menu

**Comment by Helium-ion** [comment]
Thanks for the method.
