### ISSUE TITLE
Consistent crash on decouple

### ISSUE THREAD

**Issue by firetux** [mockingbirdnest/Principia#3802]
Getting a crash everytime I try to decouple my Venus lander from its braking stage in Venus orbit. Unity crash handler appears then desktop.

Things I tried:

- Make sure nothing is clipping by having a gap between the decoupler and the heatshield did not help.
- Removing forces from the decoupler (impulse and %force 0) did not help.
- Decoupling in the PAW or staging makes no difference
- Ticking "hack gravity" does help to survive decoupling but if I then separate the craft and untick it, KSP crashes anyway.
- I tried decoupling the same decoupler in LEO and that did interestingly not lead to crash, however my TVI stage was still attached at that point (not sure it could make a difference)

Error.log seems to point to principa.dll 
logs here: https://gist.github.com/firetux/6eda469011cb273ef592a0192b450abe

**Comment by firetux** [comment]
After a fresh install and decoupling with hack gravity on plus trying a few times under different forms of physical time warp I managed to separate the craft without crash or explosions. The cause seems to be clipping parts, despite nothing of either subvessel visually overlapping.

**Comment by pleroy** [comment]
Possibly related to #4026.
