### ISSUE TITLE
Principia failed to load, but libc++ and libc++abi are installed (Linux)

### ISSUE THREAD

**Issue by Dupiter-AU** [mockingbirdnest/Principia#3808]
When attempting to launch the game natively (OpenGL on Arch Linux), the following error appears:

![Screenshot_20231125_160718](https://github.com/mockingbirdnest/Principia/assets/82429716/689011a2-7e0f-4649-b779-9a5ae22d99cd)

However, I have libc++ and libc++abi installed on my system:

![Screenshot_20231125_160808](https://github.com/mockingbirdnest/Principia/assets/82429716/cdb7962f-3a7d-479a-9e6e-2606e1fdf7d9)

My working directory is set correctly, so the only other thing I can see in terms of troubleshooting from the wiki page is this:
"Different distros seem to behave in different manners. If you run into trouble, feel free to contribute a pull request."
I'm willing to help in any way I can

My KSP.log:
[KSP.log](https://github.com/mockingbirdnest/Principia/files/13463160/KSP.log)

It seems that there are quite a few errors relating to principia, the most notable being the one near the bottom, which shows that principia.so is not found, despite it being at the location it is trying to look for it. Other errors near the top relate to multiple DLL files, but I don't understand what causes them.

System specs:

Operating System: Arch Linux 
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.2-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 6 × Intel® Core™ i5-9400F CPU @ 2.90GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2

I should also note that principia is the only mod installed in this scenario

**Comment by pleroy** [comment]
* The DLL errors in the log are [well-known and innocuous](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#the-case-of-badimageformatexception).
* On Ubuntu we require `libc++1`, not `libc++` which is a different thing.  No idea how things are packaged on Arch.
* There is something quite odd in your logs:
```
Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
ModuleManager v4.2.3.0
principia.ksp_plugin_adapter v1.0.0.0
Stock assembly: KSPSteamCtrlr v0.0.1.35

Folders and files in GameData:
Principia
Stock folder: Squad

ModuleManager.4.2.3.dll
principia 賈憲 for 1.12.5.zip
```
&emsp;&emsp;That last line with the `zip` file is surprising, that file should not go in the game install.  No idea whether that is the cause of the problem or not, though.
* To gather more information, I recommend using `strace` or a similar program to trace the system calls and figure out which files it's trying to access.

**Comment by Dupiter-AU** [comment]
The .zip file is just left over from the install, I just left it there in case I needed to reinstall principia, the actual folder still remains in GameData.

In attempting to run some diagnostics with `strace`, I seem to have found something. When the game is launched using Steam, be it from a manual non-steam game launch or normally through steam, the error occurs, however when launching the game directly from the executable, principia works fine. Perhaps steam is overriding some system libraries?

I managed to run strace from the steam game launch and output to a file, hopefully it should help pinpoint the problem:
[ksp.txt](https://github.com/mockingbirdnest/Principia/files/13464076/ksp.txt)
I'll be honest, I have no idea what I'm looking at with this ¯\_(ツ)_/¯

**Comment by pleroy** [comment]
That log file doesn't even mention Principia (or any path in `GameData` for that matter) so I suspect that it's tracing the game launcher and not the game being launched.  Anyway, we won't get anything useful out of it.

To the best of my understanding Steam doesn't support Arch Linux so maybe it's not surprising it doesn't work from Steam.  The sad truth is that if you choose to use an unsupported Linux distro, you're on your own.

**Comment by Dupiter-AU** [comment]
Well I did some messing around, copying over KSP installs, reinstalling, and testing between steam native runtime and the normal runtime, and it seems to just work now????
I have no idea what exactly I did to completely fix it, but I think the most likely candidate is the steam runtime switch. Hopefully that can help if anyone else is having the same problem. I'll close the issue now
