### ISSUE TITLE
Game crashes when loading up a save

### ISSUE THREAD

**Issue by Intlon** [mockingbirdnest/Principia#3813]
Tried to use principia (never worked before). When I load a save, it crashes while loading. Nothing else appears, no unity crash handler etc. My mod list (ksp add on checker doesnt detect principia in it, so its excluded from the list):
KSP: 1.8.1 (Win64) - Unity: 2019.2.2f1 - OS: Windows 10  (10.0.0) 64bit
ClickThroughBlocker - 0.1.10.15
Filter Extensions - 3.2.6
Harmony - 2.2.1
TexturesUnlimited - 1.5.9.24
Toolbar - 1.8.0.5
ToolbarControl - 0.1.9.4
KSP-Recall - 0.4.0.1
Advanced Jet Engine - 2.15
Animated Decouplers - 1.4.2.1
B9 Part Switch - 2.14
Community Resource Pack - 112.0.1
CommunityTechTree - 3.4.4
Connected Living Space - 2.0.2
Contract Configurator - 2.1.4
CraftImport - 0.9
CryoTanks - 1.6.5
CustomPrelaunchChecks - 1.8.1.1
Deadly Reentry - 7.9
DecouplerShroud - 0.7.2
DeployableEngines - 1.3.1
DistantObjectEnhancement - 2.2
DynamicBatteryStorage - 2.2.5
Environmental Visual Enhancements - 1.8.0.2
FarFutureTechnologies - 1.2
FASA - 7.2.6
Ferram Aerospace Research - 0.16.0.1
Firespitter - 7.17
FShangarExtender - 3.6.0.1
HideEmptyTechTreeNodes - 1.3
Interstellar Fuel Switch - 3.30
JanitorsCloset - 0.3.7.7
Kerbal Engineer Redux - 1.1.8.2
Kerbalism - 3.12
Kerbal Joint Reinforcement - 3.5.2
KerbalKonstructs - 1.8.4
Kerbal Reusability Expansion - 2.8.6
HyperEdit - 1.5.8
Kopernicus - 1.8.1.139
KSC Extended - 2.2
KSC Switcher - 2.1
KSP-AVC Plugin - 1.4.1.5
KSPCommunityFixes - 1.31.1
KSPWheel - 0.16.14.33
ModularFlightIntegrator - 1.2.7
Module Manager Watch Dog - 1.0.1.1
NearFutureProps - 0.6.2
NearFuturePropulsion - 1.3.5
NearFutureSpacecraft - 1.3.1
PatchManager - 0.0.17.2
Photon Sailor - 1.7.3
PlanetShine - 0.2.6.6
Procedural Fairings - 6.1
Procedural Parts - 2.5.8
RCS Build Aid - 0.10
RealChute - 1.4.8
RealFuels - 12.8.5
Real Heat - 5.1
RealismOverhaul - 12.8.1
RealSolarSystem - 18.1.3
ReentryParticleEffectRenewed - 1.9.1.1
RemoteTech - 1.9.5
RetractableLiftingSurface - 0.2.1.1
RSSVE - 1.5.0.1
SolverEngines - 3.14
SpaceDust - 0.4.4
SpaceTuxLibrary - 0.0.8.5
SystemHeat - 0.5.5
TextureReplacer - 4.5.3
TAC Life Support - 0.14
TexturesUnlimitedFX - 1.0.2.3
Tundra Exploration - 3.1.1
Tundra Space Center - 2.0.1
TweakScale - 2.4.7.4
TweakScale Companion (The ÜberPaket) - 2023.10.21.2
TweakScale Companion for AirCrafts - 0.2
TweakScale Companion for Airplane Plus - 0.1
TweakScale Companion for Frameworks - 0.4.0.3
TweakScale Companion for Firespitter - 1.3
TweakScale Companion for Kerbal Inventory & Attachment System (KIAS) - 1.1
TweakScale Companion Living Style - 0.0.3
TweakScale Companion Multipass - 0.1
TweakScale Companion for Neist Airliner Parts - 0.0.1
TweakScale Companion for Orbit Portal Technologies (OPT) - 0.0.1.1
TweakScale Companion for Post Kerbin Mining Corporation Add'Ons - 2.2.1.1
TweakScale Companion for ReStockPlus - 1.1
TweakScale Companion Rockets - 0.0.2
TweakScale Companion for SMCE - 0.0.2
KSP Interstellar Extended - 1.29.6
Waterfall - 0.9
ZeroMiniAVC - 1.1.0.2

Gist Link for Info and Fatal files: https://gist.github.com/Intlon/f18c5518974ec7dc2d6ea6a567a0974f

Crash Files are N/A

**Comment by Nimrodium** [comment]
I'm having the same EXACT issue with principia and kopernicus in general, doesnt matter which planet pack i add it crashes immediately while loading a save. seems like the only easy fix is to uninstall any planet pack, perhaps downloading an older version of principia would fix things but i have not tried that

**Comment by pleroy** [comment]
Please don't append to a closed issue, we don't look at those.

Also, [no logs, no support](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs).
