### ISSUE TITLE
KSP crashes to desktop when time warping on 10000x or 100000x on Principia

### ISSUE THREAD

**Issue by aalekh-sharan** [mockingbirdnest/Principia#3827]
This issue happens unpredictably and on average every 100 days in-game time in the stock solar system. Also on restarting it does not happen at the same in game time but can happen on any given time. Attaching the fatal crash error and the journal.
[FATAL.20231228-221904.15000.log](https://github.com/mockingbirdnest/Principia/files/13795886/FATAL.20231228-221904.15000.log)

https://drive.google.com/file/d/16qb67OvAJCpFuL6RLY3nMSrZktmoXAFi/view?usp=sharing - Journal file

**Comment by pleroy** [comment]
We'll need the INFO log, the FATAL log is not enough.

**Comment by pleroy** [comment]
No INFO log, no support, closing.
