### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by martindlabaja** [mockingbirdnest/Principia#3839]
Principia is awesome! The biggest room for improvement is UI. It takes up too much space. It could be made much more streamlined.

Thank you for your work, It is working great and I am in awe.

**Comment by pleroy** [comment]
> It could be made much more streamlined.

This is not an actionable statement.  There have been ideas about possible UI improvements in #2275, you might want to take a look at that issue.  But note that, while the UI is certainly not perfect (1) it is not so easy to make it work using the limited GUILayout Unity libraries; and (2) it must display lots of information and controls to let the player plan and analyze vessel trajectories.
