### ISSUE TITLE
Crashes when I take off from Minmus.

### ISSUE THREAD

**Issue by kosha227** [mockingbirdnest/Principia#3865]
[FATAL.20240203-180952.6760.log](https://github.com/mockingbirdnest/Principia/files/14151913/FATAL.20240203-180952.6760.log)
[INFO.20240203-180733.6760.log](https://github.com/mockingbirdnest/Principia/files/14151914/INFO.20240203-180733.6760.log)
Journal file is too big
Crases to desktop without error window or message

**Comment by pleroy** [comment]
Thanks for reporting.  This code has been completely rewritten, so that particular bug won't be in the next release, 掛谷, to be released on Feb. 9th.

**Comment by eggrobin** [comment]
```
F0203 18:09:52.978008  8000 apsides_body.hpp:216] Check failed: height_above_terrain_at_time(min_radius_time) <= Length{} (+2.89750460069626570e-07 m vs. +0.00000000000000000e+00 m) 
```
A sub-micrometre inconsistency in terrain height putting us on the wrong side of a bisection. This was previously reported by @R-T-B on Discord: https://discord.com/channels/319857228905447436/480397772248580098/1196089901846888579. As @pleroy wrote, this bug will become obsolete in a week.

**Comment by kosha227** [comment]
Thx! I'll be waiting.
