### ISSUE TITLE
Exception spam after undocking, leaving physics range

### ISSUE THREAD

**Issue by Krazy0** [mockingbirdnest/Principia#3873]
Principia Julia. I encountered constant exception spam (red text on screen and logged) after rendezvous sequence:

1. Piloting ship LJP 410, entered physics range of Moho Tug in Minmus orbit
2. docked and undocked these ships
3. piloting Moho Tug, set maneuver node (KAC set to automatically create alarm for it)
4. switched to pilot LJP 410 and flew away from Moho Tug.
5. When it exited physics range, null ref spam started (or possibly sooner if I didn't notice)
6. exited game through main menu

Experience shows this continuous log spam will cause a crash when the log gets to 100s of MB and game stutters/ lags until it does crash.

Attached KSP and player logs. No crash log - it didn't crash. I haven't tried Principia journaling (ever).

Issue starts in Player log, line 177238.
[Player.log](https://github.com/mockingbirdnest/Principia/files/14231407/Player.log)

[KSP.log](https://github.com/mockingbirdnest/Principia/files/14231401/KSP.log)

-Krazy1 on KSP forum

**Comment by pleroy** [comment]
The problem happens when switching vessel, and we have a leftover guidance node for the previous vessel that we try to remove from the manœuvre node of the current vessel.

Amusingly enough, this bug has been around since May 2019.
