### ISSUE TITLE
Can an in-game trajectory planner for the "Interplanetary transport network" be added in a future version?

### ISSUE THREAD

**Issue by KSPSTAR** [mockingbirdnest/Principia#3909]
I really want to realize the trajectory design and planning of low energy transfer spacecraft in the game

**Comment by Clayell** [comment]
> 30 seconds to type issue, 30+ months to implement feature

TDLR: If it requires a NASA computer, then it's probably not right for principia

**Comment by eggrobin** [comment]
The somewhat showy name « Interplanetary transport network » (seemingly coined by Shane D. Ross [in the May–June 2006 issue of the _American Scientist_](https://www.jstor.org/stable/27858771)) refers to the possibility of using sequences of low-energy transfers to construct particularly efficient trajectories.

This is a problem of global optimization, which is out of scope for Principia—and is a hard problem; the European Space Agency regularly organizes a competition on that subject, see https://sophia.estec.esa.int/gtoc_portal/.

This is similar to the situation in stock KSP; while you have tools to plan individual transfers, KSP does not help you with coming up with Voyager-style long sequences of high-speed gravity assists.

Note that you can already plan low-energy transfers using Principia; the gravitational potential, displayed when looking at trajectories in the reference frame of the Lagrange points of two bodies, can help guide the planning. See also https://github.com/mockingbirdnest/Principia/wiki/A-guide-to-going-to-the-Mun-with-Principia#low-energy-transfer-an-inner-resonance-transfer-1031-ms-2-days-16-h-41-min (note however that this guide is somewhat dated; the equipotential plotting in the Lagrange frame would probably help with planning such a transfer in more recent versions of Principia; see the animated GIF in the change log for version ابن الهيثم, https://github.com/mockingbirdnest/Principia/wiki/Change-Log#%D8%A7%D8%A8%D9%86-%D8%A7%D9%84%D9%87%D9%8A%D8%AB%D9%85).

**Comment by KSPSTAR** [comment]
thank you for your reply.
This question was raised at the time mainly because it took too long to use tools to calculate the ignition window period (the low-energy transfer window for flyby of 5 celestial bodies was calculated with hundreds of solutions and constant trial and error. It took almost a whole day)
