### ISSUE TITLE
Crash Report while flying in atmosphere

### ISSUE THREAD

**Issue by sesatapomang** [mockingbirdnest/Principia#3925]
While flying in Earth's atmosphere at Mach 2 and collecting science, I opened map view to look at how far I was from the space center.
After a few seconds in map mode, the game froze when I tried to exit map mode. A few seconds later, the game closed, and I got this file recorded in the glog/Principia folder.
[FATAL.20240328-210121.50388.log](https://github.com/mockingbirdnest/Principia/files/14798097/FATAL.20240328-210121.50388.log)

This is my first time reporting an issue, so apologies if this is crude. I tried to the best of my ability to follow the FAQ's suggestion for reporting crashes.

edit: There was no pop-up box, no unity dialog, nothing. The game just closed.

**Comment by eggrobin** [comment]
> This is my first time reporting an issue, so apologies if this is crude. I tried to the best of my ability to follow the FAQ's suggestion for reporting crashes.

Please note that we need the INFO file corresponding to that FATAL file; we cannot do anything with the FATAL file alone. See https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt.

**Comment by sesatapomang** [comment]
> > This is my first time reporting an issue, so apologies if this is crude. I tried to the best of my ability to follow the FAQ's suggestion for reporting crashes.
> 
> Please note that we need the INFO file corresponding to that FATAL file; we cannot do anything with the FATAL file alone. See https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt.

My apologies. Here is the info file.
[INFO.20240328-204342.50388.log](https://github.com/mockingbirdnest/Principia/files/14798241/INFO.20240328-204342.50388.log)

**Comment by eggrobin** [comment]
Thanks for the logs, we will take a look.

Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/ecc2f051050cf6e796cbe29e6d0a2d375efb8a31/base/push_pull_callback_body.hpp#L90-L90  https://github.com/mockingbirdnest/Principia/blob/ecc2f051050cf6e796cbe29e6d0a2d375efb8a31/ksp_plugin/interface_collision.cpp#L45-L45  https://github.com/mockingbirdnest/Principia/blob/ecc2f051050cf6e796cbe29e6d0a2d375efb8a31/ksp_plugin/plugin.cpp#L1029-L1045  https://github.com/mockingbirdnest/Principia/blob/ecc2f051050cf6e796cbe29e6d0a2d375efb8a31/physics/apsides_body.hpp#L164-L242

**Comment by pleroy** [comment]
After thoroughly analyzing the code, I believe that this can happen for trajectories that lead to ill-conditioned computation of the apsides.  I'll prepare a fix.
