### ISSUE TITLE
Crash when clicking on rebase

### ISSUE THREAD

**Issue by kwattt** [mockingbirdnest/Principia#4025]
[INFO.20240609-164451.17344.log](https://github.com/user-attachments/files/15754483/INFO.20240609-164451.17344.log)
[ERROR.20240609-164451.17344.log](https://github.com/user-attachments/files/15754482/ERROR.20240609-164451.17344.log)
[FATAL.20240609-170324.17344.log](https://github.com/user-attachments/files/15754484/FATAL.20240609-170324.17344.log)

This happened when planning a second maneouver on a moon flyby, I clicked rebase and crashed without any alert box on screen.

**Comment by pleroy** [comment]
Thanks for reporting.  Is this something that you know how to reproduce?  If so could you [give us a journal](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#journaling)?  I could paper over the bug, but I'd like to understand how we end up in this state.

**Comment by kwattt** [comment]
Hello, I managed to get a journal with the crash. I noticed a really high RAM spike before the crash, but never ran out of it.
This time I got the crash just by planning the first maneouver, again on the moon.

[INFO.20240610-195416.2432.log](https://github.com/user-attachments/files/15781139/INFO.20240610-195416.2432.log)
[ERROR.20240610-195416.2432.log](https://github.com/user-attachments/files/15781140/ERROR.20240610-195416.2432.log)
[FATAL.20240610-200338.2432.log](https://github.com/user-attachments/files/15781141/FATAL.20240610-200338.2432.log)

Here is the zipped journal, uncompressed has a size of about 1.1gb
https://drive.google.com/file/d/1RLH4E0QaIuvUPp_kcOmWL-SBEoJU-IA7/view?usp=sharing

**Comment by kwattt** [comment]
Same issue again, this time when I changed the reference to MCMF reference, i took a screenshot before the game closed if its worth, I also do have another journal, please let me know if you also need it and will upload it.
[ERROR.20240628-095242.22284.log](https://github.com/user-attachments/files/16033996/ERROR.20240628-095242.22284.log)
[FATAL.20240628-111934.22284.log](https://github.com/user-attachments/files/16033997/FATAL.20240628-111934.22284.log)
[INFO.20240628-095242.22284.log](https://github.com/user-attachments/files/16033998/INFO.20240628-095242.22284.log)
[WARNING.20240628-095242.22284.log](https://github.com/user-attachments/files/16034000/WARNING.20240628-095242.22284.log)

![KSP_x64_3IxBkzNHBe](https://github.com/mockingbirdnest/Principia/assets/45342968/bcb59f15-098c-42c2-a8cf-044ed942f964)

**Comment by pleroy** [comment]
The latest log is more interesting as it points towards a singularity in the integrator.  If you could upload the latest journal that would be great.

**Comment by kwattt** [comment]
Here it is
https://drive.google.com/file/d/13QyGFaQ7OoLu7hzPTnHlRMT7P6La-LJR/view?usp=sharing

**Comment by pleroy** [comment]
Decoded stack track:
 https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/base/push_pull_callback_body.hpp#L90-L90  https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/ksp_plugin/interface_collision.cpp#L45-L45  https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/ksp_plugin/plugin.cpp#L1029-L1054  https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/physics/apsides_body.hpp#L458-L458  https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/numerics/approximation_body.hpp#L247-L247  https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/numerics/approximation_body.hpp#L127-L132  https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/numerics/polynomial_in_%D1%87%D0%B5%D0%B1%D1%8B%D1%88%D1%91%D0%B2_basis_body.hpp#L305-L307

**Comment by pleroy** [comment]
Interesting bit of the journal:
```
E0629 20:02:26.921661 27536 player.cpp:106] index: 58888953
[principia.journal.serialization.CollisionNewFlightPlanExecutor.extension] { in { plugin: 1719027084128 
celestial_index: 9 sun_world_position { x: 47003878981.001343 y: -2723705084.7652864 z: -141254979389.99554 } 
vessel_guid: "bae30dc4-c136-48e2-af6d-d33eb01b18ab" max_points: 64 } }
[principia.journal.serialization.CollisionNewFlightPlanExecutor.extension] { return { result: 1746217032704 } }
E0629 20:02:26.921661 27536 player.cpp:106] index: 58888954
[principia.journal.serialization.CollisionGetLatitudeLongitude.extension] { in { executor: 1746217032704 } }
[principia.journal.serialization.CollisionGetLatitudeLongitude.extension] { out { latitude_in_degrees: 
-38.866553115290941 longitude_in_degrees: -72.801754301775276 } return { result: true } }
E0629 20:02:26.921661 27536 player.cpp:106] index: 58888955
[principia.journal.serialization.CollisionSetRadius.extension] { in { executor: 1746217032704 radius: nan } }
[principia.journal.serialization.CollisionSetRadius.extension] { }
```

**Comment by pleroy** [comment]
What's happening is that the computation of the altitude of the terrain of the Moon at a multiple pairs (latitude, longitude) returns `NaN`.  This should not happen (obviously) and we couldn't reproduce it.  It's also worth noting that no-one has reported anything similar.

Are you by any chance using a mod that changes the terrain of the Moon?

**Comment by linecrafter** [comment]
Hello, I encountered the same issue when plotting an impact course with MCMF
Here are the journals, logs and a video recording of what I was doing:
https://drive.google.com/drive/u/2/folders/1pwulWOwjQF9JMsmfNdAhsQkYRNXRdAFY

While researching I also found a similar closed issue: https://github.com/mockingbirdnest/Principia/issues/3872

> Are you by any chance using a mod that changes the terrain of the Moon?

Personally i have Parallax mod installed as part of RSS-Reborn pack. If anything else is necessary for a report, please let me know. 

Thank you.

**Comment by pleroy** [comment]
Interesting to hear that you are using RSS-Reborn, it could be part of the problem as it touches the PQS.

Could you please give us complete information about the installation options that you picked for RSS-Reborn, including texture resolution and other options?  We'll need that to try to reproduce the bug.

**Comment by linecrafter** [comment]
Hi, i'm using Luna 32k from here https://docs.google.com/document/d/1BfiIZ8_ZEh0lrx0nsIa27Lm7O2R4e2fKPli94XHga0Q
the rest are also from document and in the screenshot. 
![image](https://github.com/user-attachments/assets/843ee812-0b7b-4150-82fa-b3eef6d36502)

I also have parallax configs from github https://github.com/RSS-Reborn/RSS-Reborn/wiki/Installation

**Comment by pleroy** [comment]
I was finally able to install RSS-Reborn (had some trouble, the installer was not working perfectly) but I could not reproduce the problem.

I am adding a check early in the game to detect the case where the terrain system returns `NaN`.  If that happens, it would be easier to figure out which mod is causing trouble.

**Comment by pleroy** [comment]
See https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#rss-reborn.
