### ISSUE TITLE
Principia failed to load (Arch Linux)

### ISSUE THREAD

**Issue by PewPewCricket** [mockingbirdnest/Principia#4028]
When Loading the game from CKAN and directly loading the KSP executable this error appears on launch:

 "The Principia DLL failed to load. An unknown error occurred; detected OS Unix 6.9.5.1 64-bit; tried loading dll at 'GameData/Principia/Linux64/principia.so', 'GameData/Principia/MacOS64/principia.so'. Note that libc++abi1-17, libc++1-17, and libunwind-17 or later (Linux) or High Sierra or later (MacOS) are required. Warning: don't load a Principia save before you have fixed this error; it might get damaged."

The latest versions of the 3 listed libraries needed on Linux are installed on the system. I am running the game with RSS/RO/RP! and a few smaller addition mods. I manually installed Principia as I could not find it on CKAN, help would be appreciated, thank you!

![image](https://github.com/mockingbirdnest/Principia/assets/114350431/8fc49e6a-6157-49b8-bb4d-27a86bec42ca)

**Comment by pleroy** [comment]
Arch requires symlinking, please read the [FAQs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#linux-users).
