### ISSUE TITLE
Crash when switching vessels in Tracking Station

### ISSUE THREAD

**Issue by EwTE-H** [mockingbirdnest/Principia#4029]
1. open a vessel with manoeuvre nodes in tracking station
2. switch to another vessel, you will see that the nodes are still there
3. double-click a node
4. crash without any dialog boxes
[log.zip](https://github.com/user-attachments/files/16043286/log.zip)

**Comment by pleroy** [comment]
Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/ksp_plugin/interface_flight_plan.cpp#L321-L326  https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/ksp_plugin/interface_body.hpp#L748-L750

**Comment by pleroy** [comment]
Obviously, the nodes should go away in step 2.  Assigning to @al2me6 who touched it last.
