### ISSUE TITLE
Principia DLL Failed to load : Principia DLL not found

### ISSUE THREAD

**Issue by Arlinker** [mockingbirdnest/Principia#4033]
I download and extracted the Principia zip file into the gamedata folder of ksp with my other mods, and when the game launches I get this message :

The Principia DLL failed to load.
The principia DLL was not found at 'GameData\Principia\x64\principia.dll' in directory 'E:\Epic Games\KerbalSpaceProgram\English'.

Warning: don't load a Principia save before you have fixed this error; it might get damaged.

I checked and the dll was in the mentionned folder, and I have no idea what could cause this.

**Comment by pleroy** [comment]
Well, that check is pretty basic, so if it tells you that the DLL cannot be found, that's probably that it's not there.  Another possibility is that the file is read-only.

I note that the path `E:\Epic Games\KerbalSpaceProgram\English` doesn't have `Program Files` in it.  I don't know anything about your setup, but that's possibly odd.

If you give us your `KSP.log` we might be able to find something.

**Comment by pleroy** [comment]
And a screenshot of the actual error box, please.

**Comment by Arlinker** [comment]
I fixed it, you were right that the dll wasn't there because I extracted the Gamedata folder from the zip into the ksp install Gamedata folder but I tried putting the Principia folder into the ksp Gamedata folder which made it work, thanks for your help though.

**Comment by pleroy** [comment]
Yeah, you are not the first to make that particular mistake.  You might be the last, though, because I improved the error message in #4034 so it should now tell you that you put the DLL at the wrong place.
