### ISSUE TITLE
Crash while editing a maneuver node

### ISSUE THREAD

**Issue by Draluigi** [mockingbirdnest/Principia#4036]
Here are three files found in KSP RO\glog\Principia at the time of my latest crash : 
[INFO.20240711-000338.10252.log](https://github.com/user-attachments/files/16169569/INFO.20240711-000338.10252.log)
[ERROR.20240711-000338.10252.log](https://github.com/user-attachments/files/16169588/ERROR.20240711-000338.10252.log)
[WARNING.20240711-000338.10252.log](https://github.com/user-attachments/files/16169589/WARNING.20240711-000338.10252.log)

I was editing a maneuver node with a craft named "Eos 4". The game just quit, without any error message whatsoever. Second time it happens exactly the same way, with the same craft, editing the same maneuver. Third crash overall with that vessel and maneuver node (the very first one was a unity crash).

**Comment by pleroy** [comment]
As explained on Discord, there is no crash in these files.  If you have a `FATAL` file follow the instructions [here](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt).  If not, look for a crash folder as explained [here](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#have-a-crash-folder).  At any rate, give us the `KSP.log` file located in your KSP installation (that file is overwritten each time KSP starts, so you'll need to upload it immediately after a crash).

**Comment by pleroy** [comment]
No life signs for a month, closing.
