### ISSUE TITLE
Crash while staging decoupler above root

### ISSUE THREAD

**Issue by Jonpc042** [mockingbirdnest/Principia#4043]
Two of my vessels have upside-down decouplers above the root part, when I decouple them the game crashes and principia generates a crash report similar to the following:

[ERROR.20240722-110433.13832.log](https://github.com/user-attachments/files/16343514/ERROR.20240722-110433.13832.log)
[ERROR.20240722-112857.13260.log](https://github.com/user-attachments/files/16343515/ERROR.20240722-112857.13260.log)
[ERROR.20240722-130015.13112.log](https://github.com/user-attachments/files/16343516/ERROR.20240722-130015.13112.log)
[ERROR.20240722-223325.8308.log](https://github.com/user-attachments/files/16343517/ERROR.20240722-223325.8308.log)
[ERROR.20240722-224538.488.log](https://github.com/user-attachments/files/16343518/ERROR.20240722-224538.488.log)

I'm getting this crash consistently with these particular vessels, I have around 2 dozen of these crash reports if you need more.

**Comment by pleroy** [comment]
These log files don't indicate a crash.  Please follow the instructions [here](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs) for reporting a bug.

**Comment by pleroy** [comment]
Also, please upgrade to the latest version of Principia.  I shouldn't have to debug an issue that may already be fixed.

**Comment by pleroy** [comment]
No life signs, closing.
