### ISSUE TITLE
Suggestion for "Reverse Time Trajectory Simulation"and"virtual spacecraft"

### ISSUE THREAD

**Issue by KSPSTAR** [mockingbirdnest/Principia#4050]
Can the following two features be added to a future version of PRINCIPIA?
1. A virtual spacecraft can be set in any time and space for planning the trajectory in advance
2. Can the trajectory of virtual spacecraft (or the existing spacecraft) be simulated in reverse time, and can set maneuver node in the reverse time direction to plan some orbits that are extremely sensitive in n-body gravity? (e.g. low-energy transfer scheme for Earth-Moon NRHO orbits,In the traditional forward time trajectory simulation, it is extremely difficult to find its low-energy incident transfer orbit)

**Comment by pleroy** [comment]
The suggestions in this issue make no sense.

We are aware that planning trajectories prior to launch (or even spacecraft design) is a real and legitimate and we are considering a range of possibilities for facilitating that.
