### ISSUE TITLE
Crash on load due to the early terrain check of Klein

### ISSUE THREAD

**Issue by Prophett1313** [mockingbirdnest/Principia#4060]
After updating Principia to version Klein, upon loading a save from the main menu the game crashes/closes with no dialogue box whatsoever. 

Neither \LocalLow\Squad\Kerbal Space Program\Crashes nor \Local\Temp\Squad\Kerbal Space Program\Crashes contain a folder that's not a few days old. 
KSP.log and Player.log attached at those links:
https://cyberdrop.me/f/Ur4hBeJtfzq17
https://cyberdrop.me/f/Ow2IpCFWVH7mm
Everything from that timestamp in \glog is attached below

Upon reverting to Kleene, the game starts normally and I am able to load the same save

[FATAL.20240806-200952.27484.log](https://github.com/user-attachments/files/16513754/FATAL.20240806-200952.27484.log)
[INFO.20240806-200907.27484.log](https://github.com/user-attachments/files/16513755/INFO.20240806-200907.27484.log)
[WARNING.20240806-200907.27484.log](https://github.com/user-attachments/files/16513756/WARNING.20240806-200907.27484.log)
[ERROR.20240806-200907.27484.log](https://github.com/user-attachments/files/16513757/ERROR.20240806-200907.27484.log)

**Comment by eggrobin** [comment]
Looks like it is the issue described in #4025; some mod is messing with the terrain system:
`F0806 20:09:52.450951 17528 ksp_plugin_adapter.cs:733] Terrain system returned NaN for altitude at latitude 150.891908356404, longitude -83.5875685995387 for celestial Ceres`

Please give us the list of mods you are using, we are trying to find the culprit.

**Comment by pleroy** [comment]
As @eggrobin said, let's start with your list of mods.

We are probably going to ask you to remove some mods one by one until we reach the point where you can load your save.  This is going to be somewhat tedious, but it will ease the sufferings of humanity 😊

**Comment by Prophett1313** [comment]
\Gamedata directory list attached:
[FolderList.txt](https://github.com/user-attachments/files/16513974/FolderList.txt)


@pleroy I'm happy to help, it's been bugging me for a very long time

**Comment by pleroy** [comment]
Could you try completely removing Parallax?  It surely is one of the mods that could affect the PQS system.  On the one hand it has been around for a long time, on the other hand Principia is pretty good at finding latent bugs...

For the rest, we'll have to wait until @eggrobin is online to see if he has better ideas.

**Comment by Prophett1313** [comment]
@pleroy 

Removing Parallax broke *something*, Kopernicus started screaming at me and default Kerbin loaded in the mm instead of Earth. Seems like it wasn't able to load the Moon due to another `null` reference 

Screenshot and Kopernicus log included just in case it helps
https://imgur.com/DNddqws
https://imgur.com/qAlmqez
[Kopernicus.log](https://github.com/user-attachments/files/16514384/Kopernicus.log)

**Comment by pleroy** [comment]
See https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#rss-reborn.
