### ISSUE TITLE
Crash occurred when trying to load or create saves in stock KSP

### ISSUE THREAD

**Issue by Mortadelyfile** [mockingbirdnest/Principia#4084]
A crash always happens when trying to load a Sandbox save in a competely new last version stock (only the Principia mod installed) KSP installation, it happens in the Loading screen starting by a freeze then Unity Crash Handler. Also happens when using a Default Career save but only when interacting once loaded.
It produces no CRASH log
[INFO.20240831-141217.29132.log](https://github.com/user-attachments/files/16824720/INFO.20240831-141217.29132.log)
[WARNING.20240831-141217.29132.log](https://github.com/user-attachments/files/16824721/WARNING.20240831-141217.29132.log)
[ERROR.20240831-141217.29132.log](https://github.com/user-attachments/files/16824722/ERROR.20240831-141217.29132.log)

**Comment by pleroy** [comment]
> a freeze then Unity Crash Handler.

Please give us the KSP/Unity crash files as explained [here](https://github.com/mockingbirdnest/Principia/blob/master/SUPPORT.md#ksp-or-unity-crashes).

**Comment by Mortadelyfile** [comment]
[crash.dmp](https://github.com/user-attachments/files/16825353/crash.dmp)
[error.log](https://github.com/user-attachments/files/16825354/error.log)
[Player.log](https://github.com/user-attachments/files/16825355/Player.log)
I must say, this might or might not be the same crashes as the logs given above, but I'm fairly certain that they are.

**Comment by pleroy** [comment]
This appears to be the same issue as #4065. 

Please update your Visual C++ redistributable, see https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version as this seems to be a Microsoft bug in version 14.36.32532.0 (which you are using according to your logs).  Please tell us if this fixes the problem.

**Comment by Mortadelyfile** [comment]
It does fix my problem, thank you very much, as now I finally tested tha it Principia works with LunaMP, only the one question, what happens if the Jool system is unstable?

**Comment by Clayell** [comment]
> what happens if the Jool system is unstable?

https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#kopernicus-or-parallax-users
Principia will detect an apocalypse has occurred and spit out a lot of errors.
