### ISSUE TITLE
Crash when switching to Tracking Station from flight

### ISSUE THREAD

**Issue by Krazy0** [mockingbirdnest/Principia#4119]
Had a crash-to-desktop happen twice now. There is a FATAL log: "Check failed: has_deserialized_flight_plan() "
There's no "crash" folder.

[KSP.log](https://github.com/user-attachments/files/17513893/KSP.log)
[Player.log](https://github.com/user-attachments/files/17513895/Player.log)
[glog.zip](https://github.com/user-attachments/files/17513903/glog.zip)

**Comment by pleroy** [comment]
Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/eeaedd30027c16e00dfcd82e0fe90745ba24beff/ksp_plugin/interface_planetarium.cpp#L329-L350  https://github.com/mockingbirdnest/Principia/blob/eeaedd30027c16e00dfcd82e0fe90745ba24beff/ksp_plugin/vessel.cpp#L344-L345

**Comment by pleroy** [comment]
The bug is clear: if `has_flight_plan` returns `true`, there is no guarantee that `flight_plan` will work: the flight plan must be explicitly deserialized.  Figuring out what sequence of clicks leads to this situation is not very interesting, so we'll just fix this without trying to reproduce it.
