### ISSUE TITLE
Crash during first launch

### ISSUE THREAD

**Issue by Qeriik** [mockingbirdnest/Principia#4125]
Fresh install of KSP 1.12.5.3190, including RP-1 and Princpia. Crashes on opening tracking station. Just PR-1 works perfectly fine.
[INFO.20241027-130541.21968.log](https://github.com/user-attachments/files/17533501/INFO.20241027-130541.21968.log)
[WARNING.20241027-130541.21968.log](https://github.com/user-attachments/files/17533503/WARNING.20241027-130541.21968.log)
[ERROR.20241027-130541.21968.log](https://github.com/user-attachments/files/17533504/ERROR.20241027-130541.21968.log)
[ModsInstalled.txt](https://github.com/user-attachments/files/17533507/ModsInstalled.txt)
https://disk.yandex.ru/d/7m4-lsU85gXWbw - other files

**Comment by pleroy** [comment]
This is the dreaded [Visual C++ redistributable incompatibility](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#known-issues): your stack is at `0x00007FF910B92F58 (MSVCP140) Thrd_yield` and you have version `14.36.32532.0` of the redistributable, released in June 2023.  Please update your redistributable.

**Comment by Qeriik** [comment]
Thank you so much, issue solved.
