### ISSUE TITLE
Automated stationkeeping

### ISSUE THREAD

**Issue by kellpossible** [mockingbirdnest/Principia#4128]
It would be nice to have some way to have automated stationkeeping for communication satellite arrays in Principia. Something like an option for a satellite to: "maintain current orbital parameters around Body X", it would then expend RCS or Fuel at the appropriate rate during timewarp in order to maintain the desired orbit.

**Comment by pleroy** [comment]
This has been suggested about a hundred times (recent thread [here](https://discord.com/channels/319857228905447436/480397772248580098/1214278181000052786) on the Principia Discord, older thread [here](https://forum.kerbalspaceprogram.com/topic/162200-wip181-191-1101-1110%E2%80%932-1122%E2%80%935-principia%E2%80%94version-%E2%80%8E%E2%80%8Ekronecker-released-2024-11-01%E2%80%94n-body-and-extended-body-gravitation/page/78/#comment-4158184) on the forum) and it's not going to happen.  Fundamentally the data model of KSP makes this impossible: a vessel that's warping is in a state known as "packed" where all its parts are unloaded and the mod has no idea what engines and tanks exist or their state.

Also, "maintain current orbital parameters" does a lot of work here.  The orbits in Principia are subject to various perturbation (e.g., the Moon) which introduce precessions.  Surely stationkeeping is not going to cancel those (think of stationkeeping a sun-synchronous orbit).  So just specifying the desired station (and attitude) is actually a very complex topic.

**Comment by pleroy** [comment]
> How does this work in real life? 

This question puzzles me.  In real life, there are teams of engineers working 365×24×7 to handle things like stationkeeping (and lots of other stuff, e.g., collision avoidance).  I don't work in this domain, but I am pretty sure that every single burn is the result of a thorough planning and execution process, because every single burn reduces the life expectancy of the vessel (there's only so much fuel).  Surely modelling and telemetry and so on go into the decision process, but there is no big red button "do stationkeeping for me".

**Comment by kellpossible** [comment]
I'm asking these questions with the view to potentially making a
contribution. I'm an engineer in my day job, so it interests me.

Perhaps somewhere on the spectrum between doing nothing and letting the
craft float where it will, and assigning a team to work on it 24/7 there
lies some automatable solutions which still provide value by maintaining
some parameters which are useful? I'll have a bit more of a think about it
over the next few weeks.

**Comment by kellpossible** [comment]
Just to be clear I'm totally fine with something that isn't a "big red
button"
