### ISSUE TITLE
Crash when creating new save; black clouds, and skybox missing on title screen

### ISSUE THREAD

**Issue by imanairconditioner** [mockingbirdnest/Principia#4132]
Logs in order of creation:
[WARNING.20241108-225511.2156.log](https://github.com/user-attachments/files/17685084/WARNING.20241108-225511.2156.log)
[INFO.20241108-225511.2156.log](https://github.com/user-attachments/files/17685082/INFO.20241108-225511.2156.log)
[FATAL.20241108-225559.2156.log](https://github.com/user-attachments/files/17685086/FATAL.20241108-225559.2156.log)
[ERROR.20241108-225511.2156.log](https://github.com/user-attachments/files/17685085/ERROR.20241108-225511.2156.log)

Mods list: [Mods.txt](https://github.com/user-attachments/files/17685061/Mods.txt)

**Comment by imanairconditioner** [comment]
The latest version of the C++ redistributable was installed with a restart shortly before starting the game.

**Comment by imanairconditioner** [comment]
Despite having a config pack installed that makes the Kcalbeloh system stable and seeing several other user posts suggest that Kcalbeloh plays nice with Principia, removing it allowed the game to load and play nominally.

**Comment by pleroy** [comment]
Decoded stack trace below.  From the error message I would not blame Kcalbeloh, but Blueshift, which is [known to be incompatible](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#blueshift-users) with Principia.  In particular, the `NaN` inertia here in the log:
```
E1108 22:55:59.919515  2432 symmetric_bilinear_form_body.hpp:207] Difficult diagonalization: {{-nan(ind) m^2 kg, -nan(ind) m^2 kg, -nan(ind) m^2 kg}, {-nan(ind) m^2 kg, -nan(ind) m^2 kg, -nan(ind) m^2 kg}, {-nan(ind) m^2 kg, -nan(ind) m^2 kg, -nan(ind) m^2 kg}}, stopping with: {{-nan(ind) m^2 kg, -nan(ind) m^2 kg, -nan(ind) m^2 kg}, {-nan(ind) m^2 kg, -nan(ind) m^2 kg, -nan(ind) m^2 kg}, {-nan(ind) m^2 kg, -nan(ind) m^2 kg, -nan(ind) m^2 kg}}
```
is a sure symptom of Blueshift is doing nonsensical physics.
 https://github.com/mockingbirdnest/Principia/blob/6247baed2d43cd8f8bd4ea84ed778e74d9e6977d/ksp_plugin/interface.cpp#L631-L635  https://github.com/mockingbirdnest/Principia/blob/6247baed2d43cd8f8bd4ea84ed778e74d9e6977d/ksp_plugin/plugin.cpp#L573-L645  https://github.com/mockingbirdnest/Principia/blob/6247baed2d43cd8f8bd4ea84ed778e74d9e6977d/ksp_plugin/vessel.cpp#L292-L294  https://github.com/mockingbirdnest/Principia/blob/6247baed2d43cd8f8bd4ea84ed778e74d9e6977d/ksp_plugin/plugin.cpp#L646-L646  https://github.com/mockingbirdnest/Principia/blob/6247baed2d43cd8f8bd4ea84ed778e74d9e6977d/ksp_plugin/part_subsets.cpp#L66-L88  https://github.com/mockingbirdnest/Principia/blob/6247baed2d43cd8f8bd4ea84ed778e74d9e6977d/base/not_null_body.hpp#L203-L203  https://github.com/mockingbirdnest/Principia/blob/6247baed2d43cd8f8bd4ea84ed778e74d9e6977d/ksp_plugin/pile_up.cpp#L71-L89  https://github.com/mockingbirdnest/Principia/blob/6247baed2d43cd8f8bd4ea84ed778e74d9e6977d/ksp_plugin/pile_up.cpp#L422-L424  https://github.com/mockingbirdnest/Principia/blob/6247baed2d43cd8f8bd4ea84ed778e74d9e6977d/physics/euler_solver_body.hpp#L43-L51
