### ISSUE TITLE
DLL error

### ISSUE THREAD

**Issue by FeCocco** [mockingbirdnest/Principia#4138]
i'm using Fedora 41, all the lib's looks fine:

        linux-vdso.so.1 (0x00007fa6eef0b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa6eeeea000)
	libc++.so.1 => /lib64/libc++.so.1 (0x00007fa6eede6000)
	libc++abi.so.1 => /lib64/libc++abi.so.1 (0x00007fa6eedb1000)
	libunwind.so.1 => /lib64/libunwind.so.1 (0x00007fa6ed7e4000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fa6ed6fe000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa6ed6cf000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa6ed4dd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa6eef0d000)
	
but the game keeps giving me that error: 

"The Principia DLL failed to load.
An unknown error occurred; detected OS Unix 6.11.8.300 64-bit; tried loading dll at 'GameData/Principia/Linux64/principia.so', 'GameData/Principia/MacOS64/principia.so'. Note that libc++abi1-17, libc++1-17, and libunwind-17 or later (Linux) or High Sierra or later (MacOS) are required." 

some suggestion on what could it be?

[KSP.log](https://github.com/user-attachments/files/17854328/KSP.log)

**Comment by pleroy** [comment]
Some people have had better luck running KSP manually than running from Stream, see for instance #4131 and in particular [this comment](https://github.com/mockingbirdnest/Principia/issues/4131#issuecomment-2465574556).

This being said, we don't support Fedora and Steam doesn't support Fedora.
