### ISSUE TITLE
Inertial/Rotating Frame Switch Causes Smoke Particle FX Issues

### ISSUE THREAD

**Issue by ferram4** [mockingbirdnest/Principia#461]
Standard Realism Overhaul install, including SmokeScreen for particle FX.

Reliance on using the lowest timewarp cutoff for the rotating/inerital frame switch causes a switch to the inertial reference frame at ~30 km altitude in Real Solar System.  Since this is within the atmosphere, smoke trail particle FX can be influenced by this switch, as shown below:

![particlefxshift](https://cloud.githubusercontent.com/assets/6935754/6367519/122196aa-bca2-11e4-876b-6064b7aab939.png)

Note that the shift occurs at the 30 km mark, that the rocket is flying straight down surface prograde (and so the smoke should be directly behind it).  Should be reproducible with RSS and any particle FX that uses worldspace coordinates for the particles, but is confirmed to be reproducible with any FX defined using Effects nodes for ModuleEnginesFX.

@eggrobin suggested using Max(atmosphere height, timewarp limit [1]) to get around this behavior.

**Comment by eggrobin** [comment]
Actual code: replace [what we currently do](https://github.com/mockingbirdnest/Principia/blob/2015022323-Bernstein/ksp_plugin_adapter/ksp_plugin_adapter.cs#L264-L265) by
```cs
      ApplyToBodyTree(body => body.inverseRotThresholdAltitude =
                                  Math.Max(body.timeWarpAltitudeLimits[1],
                                           body.maxAtmosphereAltitude));
```
