### ISSUE TITLE
Pass functors to the integrator in the benchmarks

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#468]
Currently we pass pointers to [these functions](https://github.com/mockingbirdnest/Principia/blob/2015022814-Bessel/testing_utilities/numerical_analysis.hpp#L27-L33). Function pointers are very unlikely to get inlined, so we measure the overhead of the function calls.

**Comment by pleroy** [comment]
After #499, the integrators take `std::function`, which is less efficient in the harmonic oscillator benchmark, and has no effect on the n-body system benchmark.
