### ISSUE TITLE
prediction traces shown for previous vessel in map view

### ISSUE THREAD

**Issue by Thutmose** [mockingbirdnest/Principia#502]
if vessel is switched, or the map view is opened from the tracking center, the map shows the trace from the last viewed vessel.

http://imgur.com/IArC8c1 sample from switching vessel (first vessel was in Munar orbit)
http://imgur.com/9eDDgUx sample from tracking center (first vessel was at kerbin-mun L5)

**Comment by eggrobin** [comment]
Seems to have been fixed by #506, @Thutmose could not replicate in [Borel](https://github.com/mockingbirdnest/Principia/tree/2015050622-Borel).
