### ISSUE TITLE
Add glog checks to optional

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#637]
Otherwise it's hardly better than having to `CHECK_NOTNULL` all the time.

**Comment by pleroy** [comment]
I started implementing this in the `VC` branch of our fork of `Optional`, but it's not clear if it's a good idea.  We don't insert our own checks in the STL libraries, and when `optional` is officially part of STL we won't be able to do that.  So we might as well live with the real thing.  We can always add our own `CHECK` like we do for pointers.
