### ISSUE TITLE
Predictions should not be recomputed at every frame 

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#761]
Currently the prediction is recomputed at every frame, i.e., at 50 Hz. This is probably too often.

However, in order to properly take advantage of doing it less often, we'd to parallelize, which is a whole other rabbit hole (although at least MSVC now has `shared_lock`).

**Comment by eggrobin** [comment]
A random thought while going through the issues: when the initial state doesn't change due to unpredictable factors (engines/collisions), we definitely shouldn't recompute the prediction often (the only change in the solution there is due to differences in integration methods between the history and prediction).
When things like engines are at play, it might make sense to (empirically) estimate the dependence on initial conditions and recompute based on that. The work on pile-ups should make the behaviour of unpacked vessels in free fall identical to that of packed vessels, so the situation should nicely split between actually no thrust and under thrust.

**Comment by pleroy** [comment]
Finally fixed by #2092.
