### ISSUE TITLE
Gravity models without Cartesian elements

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#884]
This should be allowed, so that modders can easily add oblateness. This probably only requires C#-side changes.
This was brought up by @skalou.

**Comment by skalou** [comment]
Nice!
 now i have to look what this oblateness number mean :p

**Comment by eggrobin** [comment]
No, that's the [flattening](https://en.wikipedia.org/wiki/Flattening), which is a geometrical property.
The gravity models have the *J*<sub>2</sub> zonal harmonic (sometimes known as dynamical oblateness), see the Wikipedia article on [geopotential models](https://en.wikipedia.org/wiki/Geopotential_model#The_deviations_of_Earth.27s_gravitational_field_from_that_of_a_homogeneous_sphere); specifically, it is the dimensionless version mentioned in that article (hence the need for a reference radius).
