### ISSUE TITLE
Custom marshaling for UTF-8 and returned unowned strings

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#901]
At the moment we have to return unowned strings as `IntPtr` and convert them with `Marshal.PtrToStringAnsi`. Moreover, on Windows `Marshal.PtrToStringAnsi` will not use UTF-8 (it will with Mono on Linux).
While waiting for [.NET to add a UTF-8 marshaller](https://github.com/dotnet/coreclr/issues/1012) and for that to percolate into whichever antiquated Mono KSP is using, we could try use libgit2sharp's custom marshalers (MIT licensed) which provide everything we need.
See [Utf8Marshaler.cs](https://github.com/libgit2/libgit2sharp/blob/3010f8373313a47e9a889e8b3e61a30cd2eb359b/LibGit2Sharp/Core/Utf8Marshaler.cs), [EncodingMarshaler.cs](https://github.com/libgit2/libgit2sharp/blob/3010f8373313a47e9a889e8b3e61a30cd2eb359b/LibGit2Sharp/Core/EncodingMarshaler.cs).

**Comment by pleroy** [comment]
Fixed by #909.
