### ISSUE TITLE
Make the maximal step count for the flight plan customizable

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#938]
Requested by Scott Manley.

**Comment by eggrobin** [comment]
We just want to make `max_steps` and possibly the tolerances customizable, not the integrator, thus FlightPlan will need a `GetAdaptiveStepParameters` and `Ephemeris::AdaptiveStepParameters` will need a `set_max_steps`. In addition, accessors (`get_max_steps`, `get_length_integration_tolerance`) will be needed to display the right numbers in the UI.

**Comment by pleroy** [comment]
We should have a "plain old struct" representations of the `...StepParameters` classes for interchange through the interface (this requires new protobufs).

**Comment by eggrobin** [comment]
Probably (although we probably don't want to pass the integrator choice through the interface yet, that's another kettle of fish), but frankly I'm not sure why `Ephemeris::AdaptiveStepParameters` can't be a struct (with public members) itself, since we're going to need to expose its members one way or another.

**Comment by pleroy** [comment]
Reassigning to @eggrobin for the UI part.
