### ISSUE TITLE
The Flight plan UI should report the actual final time

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#962]
Rather that whatever the user asked for but couldn't get because of timeouts.
This probably means that `final_time_` should be the actual final time.

**Comment by pleroy** [comment]
`final_time_` cannot change semantics, it needs to remain the desired final time.  For instance when you call `RemoveLastSegment` it should try to integrate the last coast up to the desired final time.  It seems that the only thing that needs to change here is `final_time()`.

**Comment by eggrobin** [comment]
Perhaps we should keep the current behaviour, and report "timed out after [duration]"; that would make it clearer that the step limit should be raised.
